[package]
name = "crochet-generator"
version = "0.1.0"
edition = "2021"

[dependencies]
three-d = { version = "0.19", features = ["egui-gui"] }
stl_io = "0.11"
anyhow = "1.0.104"
tokio = { version = "1.53", features = ["sync", "rt"] }
nalgebra = "0.35.0"
serde_json = "1.0.151"
serde = { version = "1.0.229", features = ["derive"] }

console_error_panic_hook = "0.1"
wasm-bindgen = "0.2.126"
web-sys = { version = "0.3.103", features = ["Window", "Document", "Element", "HtmlCanvasElement"] }