// This file was not generated by AI

use std::collections::HashMap;

use super::*;

impl Processor {
    pub fn dijkstras(&self, epsilon: f32, seed_pos: PVec3, seed_face: usize) -> Result<(HashMap<Node, (f32, Option<Node>)>, Node)> {
        // Initialise the frontier with the points touching the same face
        let mut frontier = Frontier::new();
        for node in self.get_nodes_connected_to_face(seed_face, epsilon) {
            frontier.update(node, None, (seed_pos - node.pos).magnitude())?;
        }

        let mut final_node = None;
        // Main Dijkstra's loop
        while let Some((node, geo_len)) = frontier.pop_smallest() {
            let nodes = self.get_connected_nodes(node.connectivity, epsilon);
            for updating_node in nodes {
                frontier.update(updating_node, Some(node), geo_len + (updating_node.pos - node.pos).magnitude())?;
            }
            final_node = Some(node)
        }

        Ok((frontier.get_output(), final_node.unwrap()))
    }

    pub fn reverse_traverse(&self, position: Vector<f32>, face_index: usize) -> Result<Output> {
        let Some(info) = &self.info else {
            return Err(Error {
                issue: "Cannot reverse traverse until you have generated stitches.".to_string(),
                fault: ErrorFault::User,
                solution: "First generate the stitches by left clicking.",
            })
        };

        let nodes = &info.nodes;
        let epsilon = &info.epsilon;
        let seed_point = &info.seed_point;
        
        let v = self.model.mesh.faces[face_index].vertices;
        let mut points = v.map(|i| Node { connectivity: Connectivity::OnVertex(i), pos: self.model.mesh.vertices[i].into() }).to_vec();
        for [a, b] in [[v[0], v[1]], [v[1], v[2]], [v[2], v[0]]] {
            points.append(&mut self.spaced_points(a, b, *epsilon).into_iter().map(|pos| Node { connectivity: Connectivity::on_edge(a, b), pos}).collect());
        }
        
        let mut closest = None;
        let mut distance = f32::INFINITY;
        
        for point in points {
            let pos = point.pos;
            let d = (pos - position.into()).magnitude();
            if d < distance {
                distance = d;
                closest = Some(point);
            }
        }
        
        let mut closest = closest.unwrap();
        self.sender.send(DisplayCommand::Clear(Group::ReverseTraverse)).unwrap();
        
        self.sender.send(DisplayCommand::Point {
            pos: closest.pos.into(),
            radius: self.model.radius * 0.02,
            colour: Srgba { r: 240, g: 240, b: 255, a: 255 },
            depth: true,
            group: Group::ReverseTraverse
        }).unwrap();

        let isolines = &info.isolines;
        let map = self.get_isoline_map(isolines);
        
        while let (_geo_len, Some(node)) = nodes.get(&closest).unwrap() {
            let intersections = self.find_intersections(&map, node, &closest, None)?;
            for ((i, j), (p1, _), poss) in intersections {
                match poss {
                    Some((p2, _)) => self.sender.send(DisplayCommand::Edge {
                        a: p1.pos.into(),
                        b: p2.pos.into(),
                        thickness: self.model.radius * 0.03,
                        colour: Srgba::GREEN,
                        depth: true,
                        group: Group::ReverseTraverse,
                    }).unwrap(),
                    None => self.sender.send(DisplayCommand::Point {
                        pos: p1.pos.into(),
                        radius: self.model.radius * 0.03,
                        colour: Srgba::GREEN,
                        depth: true,
                        group: Group::ReverseTraverse,
                    }).unwrap(),
                }
            }
            self.sender.send(DisplayCommand::Edge {
                a: closest.pos.into(),
                b: node.pos.into(),
                thickness: self.model.radius * 0.02,
                colour: Srgba { r: 245, g: 245, b: 245, a: 255 },
                depth: true,
                group: Group::ReverseTraverse
            }).unwrap();
            self.sender.send(DisplayCommand::Point {
                pos: node.pos.into(),
                radius: self.model.radius * 0.02,
                colour: Srgba { r: 240, g: 240, b: 255, a: 255 },
                depth: true,
                group: Group::ReverseTraverse
            }).unwrap();
            closest = *node;
        }
        self.sender.send(DisplayCommand::Edge {
            a: closest.pos.into(),
            b: (*seed_point).into(),
            thickness: self.model.radius * 0.02,
            colour: Srgba { r: 245, g: 245, b: 245, a: 255 },
            depth: true,
            group: Group::ReverseTraverse
        }).unwrap();

        Ok(Output::None)
    }

    /// Find which nodes are connected to which other nodes, for use in Dijkstra's
    pub fn get_connected_nodes(&self, connectivity: Connectivity, epsilon: f32) -> Vec<Node> {
        // Find the faces a node is connected to.
        let faces = match connectivity {
            Connectivity::OnVertex(index) => self.vertex_to_faces[index].clone(),
            Connectivity::OnEdge(v1, v2) => self.get_connected_faces(v1, v2),
        };

        // Find the verticies that lie on these faces
        let verticies: Vec<_> = faces.into_iter().map(|face_index| self.model.mesh.faces[face_index].vertices).collect();

        // Use the verticies in order to find the vertex-pairs describing the edges of the face
        let edges: Vec<_> = verticies.iter().flat_map(|[v1, v2, v3]| [(v1, v2), (v2, v3), (v3, v1)]).collect();

        // Use these vertex-pair edges in order to find the spaced points along this edge
        let spaced_points: Vec<_> = edges.into_iter().flat_map(|(a, b)| {
            let posses = self.spaced_points(*a, *b, epsilon);
            posses.into_iter().map(|pos| Node { connectivity: Connectivity::on_edge(*a, *b), pos })
        }).collect();

        // Remove duplicated verticies
        let mut verticies = remove_duplicates(verticies.into_flattened());
        if let Connectivity::OnVertex(vertex) = connectivity {
            // If our node is on a vertex, remove that from the list we will return
            let index = verticies.iter().position(|v| *v == vertex).expect("The vertex we are finding connections to is connected to the face its connected to.");
            verticies.swap_remove(index);
        };

        let verticies = verticies.into_iter().map(|index|
            Node { connectivity: Connectivity::OnVertex(index), pos: self.model.mesh.vertices[index].into() }
        );
        
        let mut result = spaced_points;
        result.append(&mut verticies.collect());
        result
    }

    /// This is guarunteed to return at least 3 nodes
    pub fn get_nodes_connected_to_face(&self, face_index: usize, epsilon: f32) -> Vec<Node> {
        // Find the verticies that lie on these faces
        let verticies = self.model.mesh.faces[face_index].vertices;

        // Use the verticies in order to find the vertex-pairs describing the edges of the face
        let v1 = verticies[0];
        let v2 = verticies[1];
        let v3 = verticies[2];
        let edges = [(v1, v2), (v2, v3), (v3, v1)];

        // Use these vertex-pair edges in order to find the spaced points along this edge
        let spaced_points: Vec<_> = edges.into_iter().flat_map(|(a, b)| {
            let posses = self.spaced_points(a, b, epsilon);
            posses.into_iter().map(move |pos| Node { connectivity: Connectivity::on_edge(a, b), pos })
        }).collect();

        // This function does not produce duplicates.


        let verticies = verticies.into_iter().map(|index|
            Node { connectivity: Connectivity::OnVertex(index), pos: self.model.mesh.vertices[index].into() }
        );
        
        let mut result = spaced_points;
        result.append(&mut verticies.collect());
        result
    }

    // This function must ensure that the result is consistent (to the exact bit) if the inputs are the same.
    // This is because I use these values in a HashSet.
    // This means I can't use undefined precision functions such as sine and cosine, but sqrt and arithmetic operations are okay.
    // In order to ensure I haven't accidentally used something undefined behind the scenes, I've implemented my own Vec3.
    pub fn spaced_points(&self, a: usize, b: usize, epsilon: f32) -> Vec<PVec3> {
        // This ensures a is always bigger than b for consistent ordering
        let (a, b) = if a > b {
            (a, b)
        } else {
            (b, a)
        };
        let a: PVec3 = self.model.mesh.vertices[a].into();
        let b: PVec3 = self.model.mesh.vertices[b].into();
        let magnitude = (a - b).magnitude();
        let spaces = (magnitude / epsilon).ceil();
        let uspaces = spaces as usize - 1;
        let diff = (a - b) / spaces;
        let mut fin = b;
        let mut result = Vec::with_capacity(uspaces);
        for _ in 0..uspaces {
            fin += diff;
            result.push(fin);
        }
        result
    }

    /// This function also returns the two vertex nodes
    pub fn nodes_on_edge(&self, a: usize, b: usize, epsilon: f32) -> Vec<Node> {
        let mut nodes = Vec::with_capacity(2);
        let node_a = self.node_from_vertex(a);
        let node_b = self.node_from_vertex(b);
        nodes.append(&mut self.spaced_points(a, b, epsilon).into_iter().map(|pos| self.node_from_spacing(a, b, pos)).collect());
        nodes.push(node_a);
        nodes.push(node_b);
        nodes
    }

    /// Takes in a point on a face, and returns the geo-length and previous node.
    /// This returns None if the point is on the same face as the seed point.
    /// # Panics
    /// Panics if self.info is None
    pub fn get_face_point_rev_trav(&self, pos: PVec3, face: usize) -> (f32, Option<Node>) {
        let info = self.get_info_unwrapped();
        let nodes = &info.nodes;
        let epsilon = &info.epsilon;
        let seed_point = &info.seed_point;
        let seed_face = &info.seed_face;

        let mut connected_nodes = self.get_nodes_connected_to_face(face, *epsilon);

        if face == *seed_face {
            return ((*seed_point - pos).magnitude(), None)
        }

        let first = connected_nodes.pop().unwrap();
        let mut min_geo = (first.pos - pos).magnitude() + nodes.get(&first).unwrap().0;
        let mut min_node = first;

        for node in connected_nodes {
            let len = (node.pos - pos).magnitude() + nodes.get(&node).unwrap().0;
            if len < min_geo {
                min_geo = len;
                min_node = node;
            }
        }

        (min_geo, Some(min_node))
    }

    /// Takes in a NodeOnEdge, and returns the geo-length and previous node.
    /// This returns None if the point is on the same face as the seed point.
    /// # Panics
    /// Panics if self.info is None
    pub fn get_on_edge_rev_trav(&self, on_edge: NodeOnEdge) -> Result<(f32, Option<Node>)> {
        let info = self.get_info_unwrapped();
        let nodes = &info.nodes;
        let epsilon = &info.epsilon;
        let seed_point = &info.seed_point;
        let seed_face = &info.seed_face;
        let pos = on_edge.pos;

        let mut faces = self.get_connected_faces(on_edge.edge.a, on_edge.edge.b);
        assert(
            faces.len() == 2,
            "The STL file is not watertight",
            "Chose a different, watertight STL file",
            ErrorFault::File
        )?;
        let face1 = faces.pop().unwrap();
        let face2 = faces.pop().unwrap();
        let mut connected_nodes = self.get_nodes_connected_to_face(face1, *epsilon);
        connected_nodes.append(&mut self.get_nodes_connected_to_face(face2, *epsilon));

        if face1 == *seed_face || face2 == *seed_face {
            return Ok(((*seed_point - pos).magnitude(), None))
        }

        let first = connected_nodes.pop().unwrap();
        let mut min_geo = (first.pos - pos).magnitude() + nodes.get(&first).unwrap().0;
        let mut min_node = first;

        for node in connected_nodes {
            let len = (node.pos - pos).magnitude() + nodes.get(&node).unwrap().0;
            if len < min_geo {
                min_geo = len;
                min_node = node;
            }
        }

        Ok((min_geo, Some(min_node)))
    }
}