// This file was not generated by AI

use std::collections::HashMap;

use super::*;

impl Processor {
    pub fn dijkstras(&self, epsilon: f32, seed_pos: PVec3, seed_face: usize) -> (HashMap<Node, (f32, Option<Node>)>, Node) {
        // Initialise the frontier with the points touching the same face
        let mut frontier = Frontier::new();
        for node in self.get_nodes_connected_to_face(seed_face, epsilon) {
            frontier.update(node, None, (seed_pos - node.pos).magnitude());
        }

        let mut final_node = None;
        // Main Dijkstra's loop
        while let Some((node, geo_len)) = frontier.pop_smallest() {
            let nodes = self.get_connected_nodes(node.connectivity, epsilon);
            for updating_node in nodes {
                frontier.update(updating_node, Some(node), geo_len + (updating_node.pos - node.pos).magnitude());
            }
            final_node = Some(node)
        }

        (frontier.get_output(), final_node.unwrap())
    }

    pub fn reverse_traverse(&self, info: &GeneratedInfo, position: Vector<f32>, face_index: usize) {
        let GeneratedInfo { nodes, stitch_size: _, epsilon, seed_point, seed_face: _ } = info;
        let v = self.model.mesh.faces[face_index].vertices;
        let mut points = v.map(|i| Node { connectivity: Connectivity::OnVertex(i), pos: self.model.mesh.vertices[i].into() }).to_vec();
        for [a, b] in [[v[0], v[1]], [v[1], v[2]], [v[2], v[0]]] {
            points.append(&mut self.spaced_points(a, b, *epsilon).into_iter().map(|pos| Node { connectivity: Connectivity::on_edge(a, b), pos}).collect());
        }

        let mut closest = None;
        let mut distance = f32::INFINITY;

        for point in points {
            let pos = point.pos;
            let d = (pos - position.into()).magnitude();
            if d < distance {
                distance = d;
                closest = Some(point);
            }
        }

        let mut closest = closest.unwrap();
        self.sender.send(DisplayCommand::Clear(Group::ReverseTraverse as usize)).unwrap();

        self.sender.send(DisplayCommand::Point {
            pos: closest.pos.into(),
            radius: self.model.radius * 0.02,
            colour: Srgba { r: 240, g: 240, b: 255, a: 255 },
            depth: true,
            group: Group::ReverseTraverse as usize
        }).unwrap();

        while let (_geo_len, Some(node)) = nodes.get(&closest).unwrap() {
            self.sender.send(DisplayCommand::Edge {
                a: closest.pos.into(),
                b: node.pos.into(),
                thickness: self.model.radius * 0.02,
                colour: Srgba { r: 245, g: 245, b: 245, a: 255 },
                depth: true,
                group: Group::ReverseTraverse as usize
            }).unwrap();
            self.sender.send(DisplayCommand::Point {
                pos: node.pos.into(),
                radius: self.model.radius * 0.02,
                colour: Srgba { r: 240, g: 240, b: 255, a: 255 },
                depth: true,
                group: Group::ReverseTraverse as usize
            }).unwrap();
            closest = *node;
        }
        self.sender.send(DisplayCommand::Edge {
            a: closest.pos.into(),
            b: (*seed_point).into(),
            thickness: self.model.radius * 0.02,
            colour: Srgba { r: 245, g: 245, b: 245, a: 255 },
            depth: true,
            group: Group::ReverseTraverse as usize
        }).unwrap();
    }

    /// Find which nodes are connected to which other nodes, for use in Dijkstra's
    pub fn get_connected_nodes(&self, connectivity: Connectivity, epsilon: f32) -> Vec<Node> {
        // Find the faces a node is connected to.
        let faces = match connectivity {
            Connectivity::OnVertex(index) => self.vertex_to_faces[index].clone(),
            Connectivity::OnEdge(v1, v2) => self.get_connected_faces(v1, v2),
        };

        // Find the verticies that lie on these faces
        let verticies: Vec<_> = faces.into_iter().map(|face_index| self.model.mesh.faces[face_index].vertices).collect();

        // Use the verticies in order to find the vertex-pairs describing the edges of the face
        let edges: Vec<_> = verticies.iter().flat_map(|[v1, v2, v3]| [(v1, v2), (v2, v3), (v3, v1)]).collect();

        // Use these vertex-pair edges in order to find the spaced points along this edge
        let spaced_points: Vec<_> = edges.into_iter().flat_map(|(a, b)| {
            let posses = self.spaced_points(*a, *b, epsilon);
            posses.into_iter().map(|pos| Node { connectivity: Connectivity::on_edge(*a, *b), pos })
        }).collect();

        // Remove duplicated verticies
        let mut verticies = remove_duplicates(verticies.into_flattened());
        if let Connectivity::OnVertex(vertex) = connectivity {
            // If our node is on a vertex, remove that from the list we will return
            let index = verticies.iter().position(|v| *v == vertex).expect("The vertex we are finding connections to is connected to the face its connected to.");
            verticies.swap_remove(index);
        };

        let verticies = verticies.into_iter().map(|index|
            Node { connectivity: Connectivity::OnVertex(index), pos: self.model.mesh.vertices[index].into() }
        );
        
        let mut result = spaced_points;
        result.append(&mut verticies.collect());
        result
    }

    pub fn get_nodes_connected_to_face(&self, face_index: usize, epsilon: f32) -> Vec<Node> {
        // Find the verticies that lie on these faces
        let verticies = self.model.mesh.faces[face_index].vertices;

        // Use the verticies in order to find the vertex-pairs describing the edges of the face
        let v1 = verticies[0];
        let v2 = verticies[1];
        let v3 = verticies[2];
        let edges = [(v1, v2), (v2, v3), (v3, v1)];

        // Use these vertex-pair edges in order to find the spaced points along this edge
        let spaced_points: Vec<_> = edges.into_iter().flat_map(|(a, b)| {
            let posses = self.spaced_points(a, b, epsilon);
            posses.into_iter().map(move |pos| Node { connectivity: Connectivity::on_edge(a, b), pos })
        }).collect();

        // This function does not produce duplicates.


        let verticies = verticies.into_iter().map(|index|
            Node { connectivity: Connectivity::OnVertex(index), pos: self.model.mesh.vertices[index].into() }
        );
        
        let mut result = spaced_points;
        result.append(&mut verticies.collect());
        result
    }

    // This function must ensure that the result is consistent (to the exact bit) if the inputs are the same.
    // This is because I use these values in a HashSet.
    // This means I can't use undefined precision functions such as sine and cosine, but sqrt and arithmetic operations are okay.
    // In order to ensure I haven't accidentally used something undefined behind the scenes, I've implemented my own Vec3.
    pub fn spaced_points(&self, a: usize, b: usize, epsilon: f32) -> Vec<PVec3> {
        // This ensures a is always bigger than b for consistent ordering
        let (a, b) = if a > b {
            (a, b)
        } else {
            (b, a)
        };
        let a: PVec3 = self.model.mesh.vertices[a].into();
        let b: PVec3 = self.model.mesh.vertices[b].into();
        let magnitude = (a - b).magnitude();
        let spaces = (magnitude / epsilon).ceil();
        let uspaces = spaces as usize - 1;
        let diff = (a - b) / spaces;
        let mut fin = b;
        let mut result = Vec::with_capacity(uspaces);
        for _ in 0..uspaces {
            fin += diff;
            result.push(fin);
        }
        result
    }

    /// This function also returns the two vertex nodes
    pub fn nodes_on_edge(&self, a: usize, b: usize, epsilon: f32) -> Vec<Node> {
        let mut nodes = Vec::with_capacity(2);
        let node_a = self.node_from_vertex(a);
        let node_b = self.node_from_vertex(b);
        nodes.append(&mut self.spaced_points(a, b, epsilon).into_iter().map(|pos| self.node_from_spacing(a, b, pos)).collect());
        nodes.push(node_a);
        nodes.push(node_b);
        nodes
    }
}