// This file was not generated by AI

use std::collections::{BTreeSet, HashMap, hash_map::Entry};

use three_d::egui::emath::{Float, OrderedFloat};

use crate::process::{Result, assert_internal};

use super::{Node, assert};


#[derive(Default)]
pub struct Frontier {
    tree: BTreeSet<(OrderedFloat<f32>, Node)>,
    map: HashMap<Node, (f32, Option<Node>)>,
}

enum UpdateStatus {
    Vacant,
    OccupiedUpdate(f32),
    OccupiedNone
}

impl Frontier {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn update(&mut self, node: Node, pre: Option<Node>, geo_len: f32) -> Result<()> {
        let insert = match self.map.entry(node) {
            // If this node hasn't been entered yet, just enter it.
            Entry::Vacant(vacant_entry) => { vacant_entry.insert_entry((geo_len, pre)); UpdateStatus::Vacant },
            // If this node has already been entered, check if the new length is shorter.
            Entry::Occupied(mut occupied_entry) => {
                let prev = occupied_entry.get().0;
                if geo_len < prev {
                    *occupied_entry.get_mut() = (geo_len, pre);
                    UpdateStatus::OccupiedUpdate(prev)
                } else {
                    UpdateStatus::OccupiedNone
                }
            },
        };

        // If this node already existed, first remove it
        if let UpdateStatus::OccupiedUpdate(old) = insert {
            assert_internal::<3>(
                self.tree.remove(&(old.ord(), node)),
                None
            )?;
        }

        // If we are adding / updating a node, push it to the tree
        if matches!(insert, UpdateStatus::OccupiedUpdate(_) | UpdateStatus::Vacant) {
            assert_internal::<4>(
                self.tree.insert((geo_len.ord(), node)),
                None
            )?;
        }

        Ok(())
    }

    pub fn pop_smallest(&mut self) -> Option<(Node, f32)> {
        let (float, node) = self.tree.pop_first()?;
        Some((node, float.0))
    }

    pub fn get_output(self) -> HashMap<Node, (f32, Option<Node>)> {
        self.map
    }
}