// This file was partially generated by AI (one five-line function, one foiur-line function)
// All AI used in this file is documented.

use std::{collections::VecDeque, fmt::Debug};

use crate::{process::{Group, Processor, stitches::{Highlight, InternalStitchCommand}}, viewer::DisplayCommand};

use colored::Colorize;
use three_d::Srgba;

#[derive(PartialEq)]
enum StitchCommand {
    /// # Definition
    /// Inc(n) means put n stitches at the current pointer,
    /// and then move the current pointer one across.
    /// 
    /// # Useful identities
    /// * Inc(1) === sc === Dec(0)
    /// * Inc(0) === Skip(1)
    /// 
    /// ## Note that
    /// Inc(0) is used in the code to represent "nothing".
    /// This is because, how the code works, it assumes
    /// it will move the current pointer one across until
    /// proven otherwise, so when it reaches a state of
    /// "do nothing", it assumes Skip(1) === Inc(0).
    Inc(usize, Vec<Highlight>),
    /// # Definition
    /// Dec(n) means to put a stitch at the current pointer,
    /// then move the current pointer n + 1 across, such that
    /// there are n empty stitches between the two positions.
    /// 
    /// # Useful identities
    /// * Dec(0) === sc === Inc(1)
    Dec(usize, Vec<Highlight>),
    /// # Definition
    /// Skip(n) means do NOT put a stitch at the current pointer.
    /// Instead move it across n stitches (such that there are
    /// n - 1 empty stitches between the two positions).
    /// 
    /// # Useful identities
    /// * Skip(0) === "do nothing"
    /// * Skip(1) === "move to the next stitch"
    /// * sc + Skip(n) === Dec(n)
    /// * Dec(n) + Skip(m) === Dec(n + m)
    Skip(usize, Vec<Highlight>),
    /// # Definition
    /// MagicCircle(n) means create a magic circle with n
    /// stitch points. Do not yet connect off the ends of
    /// this magic circle, as this is handled by NextRow.
    MagicCircle(usize, Vec<Highlight>),
    /// # Definition
    /// Connect the end of the last stitch to the end of the chain,
    /// move the pointer to the next row, at the seam,
    /// and replace the next supposed stitch into a chain.
    NextRow,
}

enum MidStitchCommand {
    Inc(usize, Vec<Highlight>),
    Dec(usize, Vec<Highlight>),
    Skip(usize, Vec<Highlight>),
}

impl MidStitchCommand {
    fn into_stitch_command(self) -> StitchCommand {
        match self {
            Self::Inc(n, highlight) => StitchCommand::Inc(n, highlight),
            Self::Dec(n, highlight) => StitchCommand::Dec(n, highlight),
            Self::Skip(n, highlight) => StitchCommand::Skip(n, highlight)
        }
    }
}

struct CompressedStitchCommand(
    StitchCommand,
    usize
);

#[derive(PartialEq)]
enum MoveStitch {
    Curr,
    Next
}

struct Move {
    stitch: MoveStitch,
    highlight: Highlight,
}

impl Move {
    fn new(stitch: MoveStitch, highlight: Highlight) -> Self {
        Self { stitch, highlight }
    }
}

impl StitchCommand {
    fn from_internal(stitches: Vec<InternalStitchCommand>, magic_circle: usize, magic_highlights: Vec<Highlight>) -> Vec<Self> {
        use InternalStitchCommand as ISC;
        use MoveStitch::*;
        let mut result = vec![Self::MagicCircle(magic_circle, magic_highlights)];
        let mut curr = MidStitchCommand::Inc(1, Vec::new());
        assert!(matches!(stitches[0], ISC::NextRow));
        for [stitch, next_stitch] in stitches.array_windows().map(|[a, b]| [*a, *b]).chain(Some([*stitches.last().unwrap(), ISC::NextRow])) {
            let moving = match stitch {
                ISC::MoveCurr(highlight) => Move::new(Curr, highlight),
                ISC::MoveNext(highlight) => Move::new(Next, highlight),
                ISC::NextRow => {
                    // assert!(matches!(curr, MidStitchCommand::Inc(1, _)));
                    if let MidStitchCommand::Inc(n, highlight) = curr && n > 1 {
                        result.push(Self::Inc(n - 1, highlight))
                    }
                    result.push(Self::NextRow);
                    curr = MidStitchCommand::Inc(1, Vec::new());
                    continue;
                }
            };

            

            if moving.highlight.0.isoline_index == 0 && moving.highlight.1.isoline_index == 0 {
                continue;
            }

            if matches!(moving.stitch, Curr) && matches!(next_stitch, ISC::NextRow) {
                continue;
            }

            match curr {
                MidStitchCommand::Inc(n, mut highlight) => match moving.stitch {
                    Curr => if n == 0 {
                        // This can only happen in the case that curr was an increase n >= 2, and then Move::Curr happened twice in a row.
                        curr = MidStitchCommand::Skip(1, vec![moving.highlight]);
                        if !matches!(next_stitch, ISC::MoveCurr(_)) {
                            result.push(curr.into_stitch_command());
                            curr = MidStitchCommand::Inc(0, Vec::new())
                        }
                    } else if n == 1 {
                        highlight.push(moving.highlight);
                        if matches!(next_stitch, ISC::MoveCurr(_)) {
                            curr = MidStitchCommand::Dec(0, highlight);
                        } else {
                            result.push(StitchCommand::Inc(1, highlight));
                            curr = MidStitchCommand::Inc(0, Vec::new())
                        }
                    } else {
                        highlight.push(moving.highlight);
                        result.push(StitchCommand::Inc(n, highlight));
                        curr = MidStitchCommand::Inc(0, Vec::new());
                    },
                    Next => {
                        highlight.push(moving.highlight);
                        curr = MidStitchCommand::Inc(n + 1, highlight)
                    },
                },
                MidStitchCommand::Dec(n, mut highlight) => match moving.stitch {
                    Curr => {
                        highlight.push(moving.highlight);
                        curr = MidStitchCommand::Dec(n + 1, highlight);
                        if !matches!(next_stitch, ISC::MoveCurr(_)) {
                            result.push(curr.into_stitch_command());
                            curr = MidStitchCommand::Inc(0, Vec::new())
                        }
                    },
                    Next => {
                        panic!();
                        let stitch_command = MidStitchCommand::Dec(n, highlight).into_stitch_command();
                        result.push(stitch_command);
                        curr = MidStitchCommand::Inc(0, vec![moving.highlight])
                    },
                },
                MidStitchCommand::Skip(n, mut highlight) => match moving.stitch {
                    Curr => curr = MidStitchCommand::Skip(n + 1, {highlight.push(moving.highlight); highlight}),
                    Next => panic!("Impossible"),
                }
            };
        }
        
        result
    }
}

impl CompressedStitchCommand {
    fn from_stitch_commands(mut stitches: VecDeque<StitchCommand>) -> Vec<Self> {
        let mut curr = Self(stitches.pop_front().unwrap(), 1);
        let mut result = Vec::new();
        for stitch in stitches {
            if stitch == curr.0 {
                curr.1 += 1
            } else {
                result.push(curr);
                curr = Self(stitch, 1);
            }
        }

        result
    }
}


/// For more information about the semantics of each,
/// check the doc commends in StitchCommand.
#[derive(Clone, Copy, Debug)]
enum ReadableCompressedStitchCommand {
    Sc,
    Inc(usize),
    Dec(usize),
    Skip(usize),
    RepSc(usize),
    RepInc(usize, usize),
    RepDec(usize, usize),
    MagicCircle(usize),
    NextRow,
}


#[derive(Clone)]
pub struct Readable(
    ReadableCompressedStitchCommand,
    Vec<Highlight>
);

impl Debug for Readable {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_tuple("Readable").field(&self.0).finish()
    }
}

impl Readable {
    fn from_compressed_stitch_commands(stitches: Vec<CompressedStitchCommand>) -> Vec<Self> {
        stitches.into_iter().flat_map(Self::from_compressed_stitch_command).collect()
    }

    fn from_compressed_stitch_command(stitch: CompressedStitchCommand) -> Vec<Self> {
        use ReadableCompressedStitchCommand as RCSC;
        match stitch.0 {
            StitchCommand::Inc(v, highlight) => if v == 0 {
                Vec::new()
            } else if stitch.1 == 1 {
                if v == 1 {
                    vec![Self(RCSC::Sc, highlight)]
                } else {
                    vec![Self(RCSC::Inc(v), highlight)]
                }
            } else if v == 1 {
                vec![Self(RCSC::RepSc(stitch.1), highlight)]
            } else {
                vec![Self(RCSC::RepInc(v, stitch.1), highlight)]
            }
            ,
            StitchCommand::Dec(v, highlight) => if stitch.1 == 1 {
                vec![Self(RCSC::Dec(v), highlight)]
            } else {
                vec![Self(RCSC::RepDec(v, stitch.1), highlight)]
            },
            StitchCommand::MagicCircle(v, highlights) => vec![Self(RCSC::MagicCircle(v), highlights); stitch.1],
            StitchCommand::NextRow => vec![Self(RCSC::NextRow, Vec::new()); stitch.1],
            StitchCommand::Skip(n, highlights) => vec![Self(RCSC::Skip(n * stitch.1), highlights)],
        }
    }

    pub fn from_internal(stitches: Vec<InternalStitchCommand>, magic_circle: usize, magic_highlights: Vec<Highlight>) -> Vec<Self> {
        let stitches = StitchCommand::from_internal(stitches, magic_circle, magic_highlights);
        let compressed_stitches = CompressedStitchCommand::from_stitch_commands(stitches.into());
        Self::from_compressed_stitch_commands(compressed_stitches)
    }
}

impl Processor {
    pub fn display_from_vec(&self, vec: &[Readable], index: usize) {
        self.sender.send(DisplayCommand::Clear(Group::HighlightedStitch)).unwrap();
        let mut result = "[ ".to_string();
        let last = vec.last().unwrap();
        for (i, readable) in vec[..vec.len() - 1].iter().enumerate() {
            if i == index {
                result.push_str(&format!("<{:?}>", readable.0).bold().to_string());
                self.send_highlights(&readable.1);
            } else {
                result.push_str(&format!("{:?}", readable.0));
            }
            result.push_str(", ");
        }
        
        if index == vec.len() - 1 {
            result.push_str(&format!("<{:?}>", last.0).bold().to_string());
            self.send_highlights(&last.1);
        } else {
            result.push_str(&format!("{:?}", last.0));
        }
        result.push_str(" ]");

        println!("{result}")
    }

    fn send_highlights(&self, highlights: &[Highlight]) {
        for highlight in highlights {
            self.sender.send(DisplayCommand::Edge {
                a: highlight.0.pos.into(),
                b: highlight.1.pos.into(),
                thickness: self.model.radius * 0.02,
                colour: Srgba::RED,
                depth: false,
                group: Group::HighlightedStitch
            }).unwrap()
        }
    }
}