// This file was partially generated by AI (one five-line function, one four-line function)
// All AI used in this file is documented.

use std::cmp::Ordering;
use std::ops::Deref;

use three_d::Srgba;

use crate::process::{Error, ErrorFault, Group, Processor, Result, assert_internal, failed_assert_internal};
use crate::process::sizes_calculator::FixedHookCalculator;
use crate::process::process_vec3::PVec3;
use crate::viewer::DisplayCommand;
use crate::process::isolines::{NodeOnEdge, OnEdge};
use crate::process::connect::{CircleTree, IsolinesMap};

#[derive(Clone, Copy, PartialEq)]
pub enum InternalStitchCommand {
    MoveCurr(Highlight),
    MoveNext(Highlight),
    NextRow(Highlight, Highlight),
}

fn nearest_stitch_size(relative_size: f32) -> f32 {
    match relative_size {
        0.0..1.25 => 1.0,
        1.25..1.75 => 1.5,
        1.75..2.5 => 2.0,
        2.5.. => 3.0,
        v => panic!("Incorrect value given to nearest_stitch_size: {v}")
    }
}


/// This panics if a == b.
/// 
/// This returns a result such that:
/// a*lambda + b*(1-lambda) is the closest
/// point to p that lies on the LINE ab.
// This function was partially AI generated
fn calc_lambda(p: PVec3, a: PVec3, b: PVec3) -> f32 {
    let v = a - b;
    (p - b).dot(v) / v.dot(v)
}

/// This returns a result such that:
/// a*lambda + b*(1-lambda) is the closest
/// point to p that lies on the SEGMENT ab.
fn calc_clamped_lambda(p: PVec3, a: PVec3, b: PVec3) -> f32 {
    calc_lambda(p, a, b).clamp(0.0, 1.0)
}

/// This returns a result such that:
/// the result is the closest point to p that lies on the SEGMENT ab.
fn calc_nearest_point(p: PVec3, a: PVec3, b: PVec3) -> PVec3 {
    if a == b {
        a
    } else {
        let lambda = calc_clamped_lambda(p, a, b);
        a * lambda + b * (1.0 - lambda)
    }
}

// This function was AI generated.
fn intersect(n: PVec3, a: PVec3, b: PVec3, c: PVec3, d: PVec3) -> PVec3 {
    let r = b - a;
    let t = (c - a).cross(d - c).dot(n) / r.cross(d - c).dot(n);
    a + r * t
}

#[derive(Clone, Copy, PartialEq)]
pub struct Highlight(pub HighlightPoint, pub HighlightPoint);

impl Highlight {
    pub fn null() -> Self {
        let null = HighlightPoint { pos: PVec3::splat(0.0), isoline_index: 0 };
        Self(null, null)
    }
}

#[derive(Clone, Copy, PartialEq)]
pub struct HighlightPoint {
    pub pos: PVec3,
    pub isoline_index: usize
}

impl From<StitchPoint> for HighlightPoint {
    fn from(value: StitchPoint) -> Self {
        Self {
            pos: value.pos,
            isoline_index: value.isoline_index
        }
    }
}

// impl From<PVec3> for HighlightPoint {
//     fn from(value: PVec3) -> Self {
//         Self {
//             pos: value,
//             isoline_index: None
//         }
//     }
// }

impl Processor {
    /// This panics if self.info is None
    pub fn tree_into_stitches(&self, tree: CircleTree, sizes_calculator: FixedHookCalculator, isolines_map: &IsolinesMap) -> Result<(usize, Vec<Highlight>, Vec<InternalStitchCommand>, Vec<StitchPoint>)> {
        let info = self.get_info_unwrapped();
        let furthest_point = info.furthest_point.pos;
        let seed_point = info.seed_point;

        self.sender.send(DisplayCommand::ClearAll).unwrap();
        let scw = sizes_calculator.relative_to_stl(1.0, false);
        let mut internal_result = Vec::new();

        let initial_stitches = (tree.circle_len / scw).round() as usize;

        let mut direction_flag = false;
        
        let mut curr = tree;
        let mut isoline = 0;
        let mut curr_point = StitchPoint {
            face: self.face_connected_to_edges(curr.circle[0].edge, curr.circle[1].edge)?,
            isoline_index: 0,
            pos: curr.circle[0].pos,
        };
        let mut curr_spaced_point_index = 0;

        let spaced_points = |circle_len: f32, start_point: StitchPoint, circle: &[NodeOnEdge], direction_flag: bool| -> Result<Vec<StitchPoint>> {
            let curr_stitches = (circle_len / scw).round() as usize;
            let curr_scw = circle_len / curr_stitches as f32;
            let curr_scw = if direction_flag { -curr_scw } else { curr_scw };
            let mut result = Vec::with_capacity(curr_stitches);
            let mut curr_stitch = start_point;
            result.push(curr_stitch);
            for _ in 0..curr_stitches-1 {
                curr_stitch = self.move_on_circle(circle, curr_stitch.isoline_index, curr_stitch.pos, curr_scw)?;
                result.push(curr_stitch);
            }

            for [a, b] in result.array_windows().map(|[a, b]| [a, b]).chain(Some([result.last().unwrap(), result.first().unwrap()])) {
                self.sender.send(DisplayCommand::Edge {
                    a: a.pos.into(),
                    b: b.pos.into(),
                    thickness: self.model.radius * 0.02,
                    colour: Srgba::BLUE,
                    depth: true,
                    group: Group::StitchRow,
                }).unwrap();
                self.sender.send(DisplayCommand::Point {
                    pos: a.pos.into(),
                    radius: self.model.radius * 0.025,
                    colour: Srgba::RED,
                    depth: true,
                    group: Group::StitchRow
                }).unwrap();
            }
            Ok(result)
        };

        let mut curr_spaced_points = spaced_points(curr.circle_len, curr_point, &curr.circle, false)?;

        let mut magic_highlights = Vec::with_capacity(curr_spaced_points.len());
        for (i, [a, b]) in curr_spaced_points.array_windows().map(|[a, b]| [a, b]).chain(Some([curr_spaced_points.last().unwrap(), curr_spaced_points.first().unwrap()])).enumerate() {
            self.send_stitch(seed_point, b.pos, a.pos);
            magic_highlights.push(Highlight(HighlightPoint { pos: seed_point, isoline_index: 0 }, HighlightPoint { pos: a.pos, isoline_index: i }));
        }

        let mut final_highlights = curr_spaced_points.clone();

        while let Some(next) = curr.children.pop() {
            if curr.children.len() > 1 {
                return Err(Error {
                    issue: "Your object splits into multiple paths that you need to crochet seperately and stitch together.\nThis behaviour is not yet supported.".to_string(),
                    fault: ErrorFault::Code(None),
                    solution: "Chose a seed such that the object won't split, or chose a different object file.",
                })
            }
            
            let cmp_data: (usize, &IsolinesMap, &[NodeOnEdge], f32) = (isoline, isolines_map, &curr.circle, curr.circle_len);
            let curr_len = curr.circle_len;
            let curr_stitches = (curr_len / scw).round();
            let next_len = next.circle_len;
            let next_stitches = (next_len / scw).round();
            let next_scw = next_len / next_stitches;

            let mut next_v = {
                let mut min_i = 0;
                let mut min_d = f32::INFINITY;
                let mut min_n = PVec3::splat(0.0);
                for (i, [a, b]) in next.circle
                    .array_windows()
                    .map(|[a,b]| [a, b]) // Type conversion from &[_; 2] to [&_; 2]
                    .chain(Some([next.circle.last().unwrap(), next.circle.first().unwrap()]))
                    .enumerate()
                {
                    {
                        let face = self.face_connected_to_edges(a.edge, b.edge)?;
                        self.sender.send(DisplayCommand::Point { pos: a.pos.into(), radius: self.model.radius * 0.03, colour: Srgba::GREEN, depth: false, group: Group::Backtrack }).unwrap();
                        self.sender.send(DisplayCommand::Point { pos: b.pos.into(), radius: self.model.radius * 0.03, colour: Srgba::GREEN, depth: false, group: Group::Backtrack }).unwrap();
                        let [a, b, c] = self.model.mesh.faces[face].vertices.map(|i| self.model.mesh.vertices[i]);
                        self.sender.send(DisplayCommand::Face { a, b, c, colour: Srgba::BLUE, depth: true, group: Group::Backtrack }).unwrap();
                        // std::thread::sleep(std::time::Duration::from_secs_f32(1.0));
                        self.sender.send(DisplayCommand::Clear(Group::Backtrack)).unwrap();
                    }
                    // A phase difference POTENTIALLY improves this section.
                    let n = calc_nearest_point(curr_point.pos, a.pos, b.pos);
                    let d = (curr_point.pos - n).magnitude();

                    // This is less than or equal in order to get the right index if the nearest is on vertex.
                    if d <= min_d {
                        min_i = i;
                        min_d = d;
                        min_n = n;
                    }
                }

                StitchPoint {
                    face: self.face_connected_to_edges(next.circle[min_i].edge, next.circle[(min_i + 1) % next.circle.len()].edge)?,
                    isoline_index: min_i,
                    pos: min_n,
                }
            };

            // Find which direction the next row goes in. We do not know this beforehand,
            // as the circles are stored in arbitrary order - the only thing that's guarunteed
            // is that each item in our circle is connected to the item directly before and after it (cyclically),
            // and that no items are repeated.
            let mut next_h = curr_spaced_points[curr_spaced_point_index + 1];
            let (mut next_hv, next_dir_flag) = {
                let same = self.move_on_circle(&next.circle, next_v.isoline_index, next_v.pos, maybe_neg(next_scw, direction_flag))?;
                let opposite = self.move_on_circle(&next.circle, next_v.isoline_index, next_v.pos, maybe_neg(next_scw, !direction_flag))?;

                if self.cmp_horizontal_distance_next(cmp_data, next_h, same, opposite)? == Ordering::Less {
                    (same, direction_flag)
                } else {
                    (opposite, !direction_flag)
                }
            };

            let next_scw = maybe_neg(next_scw, next_dir_flag);

            // We don't want to start at the next stitch point closest to our current stitch point,
            // we want to start at the first stitch we are connecting to our current stitch
            // (which is not necessarily the same)
            // so we walk backwards until finding the first point we DON'T want,
            // before pushing back to the first point we DO want.

            if (next_hv.pos - next_h.pos).magnitude_squared() < (next_hv.pos - curr_point.pos).magnitude_squared() {
                while (next_hv.pos - next_h.pos).magnitude_squared() < (next_hv.pos - curr_point.pos).magnitude_squared() {
                    next_hv = next_v;
                    next_v = self.move_on_circle(&next.circle, next_v.isoline_index, next_v.pos, -next_scw)?;
                }

                // This is the "push-back"
                next_v = next_hv;
                next_hv = self.move_on_circle(&next.circle, next_v.isoline_index, next_v.pos, next_scw)?;
            } else {
                // Other way around, no push back needed
                while (next_hv.pos - next_h.pos).magnitude_squared() > (next_hv.pos - curr_point.pos).magnitude_squared() {
                    next_v = next_hv;
                    next_hv = self.move_on_circle(&next.circle, next_v.isoline_index, next_v.pos, next_scw)?;
                }
            }

            self.sender.send(DisplayCommand::Edge {
                a: curr_point.pos.into(),
                b: next_v.pos.into(),
                thickness: self.model.radius * 0.02,
                colour: Srgba::WHITE,
                depth: true,
                group: Group::Seam,
            }).unwrap();

            self.sender.send(DisplayCommand::Point {
                pos: curr_point.pos.into(),
                radius: self.model.radius * 0.02,
                colour: Srgba::WHITE,
                depth: true,
                group: Group::Seam,
            }).unwrap();

            let next_spaced_points = spaced_points(next_len, next_v, &next.circle, next_dir_flag)?;
            internal_result.push(InternalStitchCommand::NextRow(
                Highlight(HighlightPoint::from(curr_spaced_points[curr_spaced_points.len() - 1]), HighlightPoint::from(curr_spaced_points[0])),
                Highlight(HighlightPoint::from(curr_spaced_points[0]), HighlightPoint::from(next_spaced_points[0]))
            ));

            let mut next_spaced_point_index = 0;
            let mut stop = 0;
            let mut curr_stitch_num = 0.0;
            while curr_stitch_num < curr_stitches {
                stop += 1;
                assert_internal::<13>(stop < 100_000, None)?;
                // std::thread::sleep(std::time::Duration::from_secs_f32(0.3));
                // self.sender.send(DisplayCommand::Clear(Group::Stitch)).unwrap();
                if (next_hv.pos - next_h.pos).magnitude_squared() < (next_hv.pos - curr_point.pos).magnitude_squared() {
                    curr_stitch_num += 1.0;
                    let prev_point = curr_point.pos;
                    curr_point = next_h;
                    curr_spaced_point_index = (curr_spaced_point_index + 1) % curr_spaced_points.len();
                    next_h = curr_spaced_points[(curr_spaced_point_index + 1) % curr_spaced_points.len()];
                    self.send_stitch(curr_point.pos, next_v.pos, prev_point);
                    internal_result.push(InternalStitchCommand::MoveCurr(Highlight(curr_point.into(), next_v.into())));
                } else {
                    next_spaced_point_index = (next_spaced_point_index + 1) % next_spaced_points.len();
                    let prev_point = next_v.pos;
                    next_v = next_hv;
                    next_hv = next_spaced_points[(next_spaced_point_index + 1) % next_spaced_points.len()];
                    self.send_stitch(curr_point.pos, next_v.pos, prev_point);
                    internal_result.push(InternalStitchCommand::MoveNext(Highlight(curr_point.into(), next_v.into())));
                }
            }
            
            while next_spaced_point_index > next_spaced_points.len() / 2 {
                let prev_point = next_spaced_points[next_spaced_point_index].pos;
                next_spaced_point_index = (next_spaced_point_index + 1) % next_spaced_points.len();
                let a = curr_spaced_points[curr_spaced_point_index];
                let b = next_spaced_points[next_spaced_point_index];
                self.send_stitch(a.pos, b.pos, prev_point);
                internal_result.push(InternalStitchCommand::MoveNext(Highlight(a.into(), b.into())));
            }

            // POTENTIALLY to be used (needs further consideration)
            internal_result.push(InternalStitchCommand::MoveCurr(Highlight(curr_spaced_points[0].into(), next_spaced_points[0].into())));

            curr_spaced_points = next_spaced_points;
            curr_point = curr_spaced_points[0];
            curr_spaced_point_index = 0;
            curr = next;
            direction_flag = next_dir_flag;
            isoline += 1;
            final_highlights = curr_spaced_points.clone();
        }


        self.sender.send(DisplayCommand::Point {
            pos: curr_point.pos.into(),
            radius: self.model.radius * 0.02,
            colour: Srgba::WHITE,
            depth: true,
            group: Group::Seam,
        }).unwrap();


        // internal_result.push(InternalStitchCommand::NextRow(
        //     Highlight(HighlightPoint::from(curr_spaced_points[curr_spaced_points.len() - 1]), HighlightPoint::from(curr_spaced_points[0])),
        //     Highlight::null()
        // ));

        for [a, b] in curr_spaced_points.array_windows().map(|[a, b]| [a, b]).chain(Some([curr_spaced_points.last().unwrap(), curr_spaced_points.first().unwrap()])) {
            self.send_stitch(b.pos, furthest_point, a.pos);
            internal_result.push(InternalStitchCommand::MoveCurr(Highlight((*a).into(), HighlightPoint { pos: furthest_point, isoline_index: 0 })));
        }

        self.sender.send(DisplayCommand::Clear(Group::Backtrack)).unwrap();
        self.sender.send(DisplayCommand::MeshVisible(false)).unwrap();
        Ok((initial_stitches, magic_highlights, internal_result, final_highlights))
    }

    fn send_stitch(&self, a: PVec3, b: PVec3, prev_point: PVec3) {
        self.sender.send(DisplayCommand::Edge {
            a: a.into(),
            b: b.into(),
            thickness: self.model.radius * 0.01,
            colour: Srgba::new(80, 80, 0, 192),
            depth: true,
            group: Group::StitchFaceOutline,
        }).unwrap();
        self.sender.send(DisplayCommand::Face {
            a: a.into(),
            b: b.into(),
            c: prev_point.into(),
            colour: Srgba::new(200, 200, 200, 255),
            depth: true,
            group: Group::Stitch,
        }).unwrap();
    }

    /// To be used to compare horizontal distance between a test point
    /// on this isoline, and two points on the next isoline.
    /// # Panics
    /// This panics if self.info is None
    fn cmp_horizontal_distance_next(&self, data: (usize, &IsolinesMap, &[NodeOnEdge], f32), test: StitchPoint, a: StitchPoint, b: StitchPoint) -> Result<Ordering> {
        Ok(self.get_horizontal_distance(data, test, a)?.total_cmp(&self.get_horizontal_distance(data, test, b)?))
    }

    /// To be used to compare horizontal distance between a test point
    /// on the next isoline, and two points on this isoline.
    /// # Panics
    /// This panics if self.info is None
    fn cmp_horizontal_distance_curr(&self, data: (usize, &IsolinesMap, &[NodeOnEdge], f32), test: StitchPoint, a: StitchPoint, b: StitchPoint) -> Result<Ordering> {
        let (intersection, _, (_, _, k)) = self.get_rev_trav_intersection(test.pos, test.face, data.1, data.0)?;
        let da = dist_on_circle(data.2, data.3, k, intersection, a.isoline_index, a.pos);
        let db = dist_on_circle(data.2, data.3, k, intersection, b.isoline_index, b.pos);
        Ok(da.total_cmp(&db))
    }

    /// To be used to find horizontal distance between points on the next isoline.
    fn get_horizontal_distance(&self, (current_isoline, isolines_map, circle, circle_len): (usize, &IsolinesMap, &[NodeOnEdge], f32), test: StitchPoint, a: StitchPoint) -> Result<f32> {
        let (pos, _vert_distance, (_i, _j, k)) = self.get_rev_trav_intersection(a.pos, a.face, isolines_map, current_isoline)?;
        Ok(dist_on_circle(circle, circle_len, k, pos, test.isoline_index, test.pos))
    }
    
    /// The Ok variant returns (intersection_point, len, (i, j, k))
    /// `intersection_point` is where the geodesic of start intersects isoline `current_isoline - 1`.
    /// the intersection point is on edge k - k+1, or exactly touches k.
    /// `len` is the length from start to the intersection point.
    /// # Panics 
    /// This panics if self.info is None
    fn get_rev_trav_intersection(&self, start: PVec3, start_face: usize, isolines_map: &IsolinesMap, current_isoline: usize) -> Result<(PVec3, f32, (usize, usize, usize))> {
        let info = self.get_info_unwrapped();
        let nodes = &info.nodes;

        let (geo_len, Some(mut prev)) = self.get_face_point_rev_trav(start, start_face) else {
            if current_isoline == 0 {
                return Err(Error {
                    issue: "Mesh wasn't dense enough near seed point.".to_string(),
                    fault: ErrorFault::File,
                    solution: "Chose a denser STL file, a different seed point, or increase relative stitch size (by decreasing diameter or increasing hook size).",
                });
            } else {
                return Err(failed_assert_internal::<14>(None))
            }
        };

        self.sender.send(DisplayCommand::Edge {
            a: prev.pos.into(),
            b: start.into(),
            thickness: self.model.radius * 0.03,
            colour: Srgba::RED,
            depth: true,
            group: Group::Backtrack,
        }).unwrap();

        if let Some(((i, j), intersection, [(_, k), _])) = self.find_face_intersections(isolines_map, &prev, start_face, start, Some(current_isoline))?.pop() {
            return Ok((intersection, (intersection - start).magnitude(), (i, j, k)))
        };

        let (((i, j), (node, k), poss), geo1, geo2) = loop {
            self.sender.send(DisplayCommand::Point {
                pos: prev.pos.into(),
                radius: self.model.radius * 0.04,
                colour: Srgba::GREEN,
                depth: false,
                group: Group::Backtrack,
            }).unwrap();
            // std::thread::sleep(std::time::Duration::from_secs_f32(1.0));
            self.sender.send(DisplayCommand::Clear(Group::Backtrack)).unwrap();
            let (_, Some(curr)) = nodes.get(&prev).unwrap() else {
                self.sender.send(DisplayCommand::Clear(Group::Backtrack)).unwrap();
                self.sender.send(DisplayCommand::Point {
                    pos: prev.pos.into(),
                    radius: self.model.radius * 0.04,
                    colour: Srgba::RED,
                    depth: false,
                    group: Group::Backtrack,
                }).unwrap();
                // std::thread::sleep(std::time::Duration::from_secs_f32(1.0));
                // this happens due to a missed intersection.
                return Err(failed_assert_internal::<16>(None));
            };

            self.sender.send(DisplayCommand::Edge {
                a: prev.pos.into(),
                b: curr.pos.into(),
                thickness: self.model.radius * 0.03,
                colour: Srgba::GREEN,
                depth: false,
                group: Group::Backtrack,
            }).unwrap();

            let Some(intersection) = self.find_intersections(isolines_map, &prev, curr, Some(current_isoline))?.pop() else {
                prev = *curr;
                continue;
            };

            let pos = match intersection.2 {
                Some((node2, _)) => {
                    let face = self.face_connected_to_edges(intersection.1.0.edge, node2.edge)?;
                    intersect(self.model.mesh.faces[face].normal.into(), intersection.1.0.pos, node2.pos, prev.pos, curr.pos)
                },
                None => {
                    intersection.1.0.pos
                }
            };

            self.sender.send(DisplayCommand::Point {
                pos: pos.into(),
                radius: self.model.radius * 0.04,
                colour: Srgba::BLUE,
                depth: false,
                group: Group::Backtrack,
            }).unwrap();

            break (intersection, prev, *curr)
        };

        match poss {
            Some((node2, _)) => {
                let face = self.face_connected_to_edges(node.edge, node2.edge)?;
                let intersection_point = intersect(self.model.mesh.faces[face].normal.into(), node.pos, node2.pos, geo1.pos, geo2.pos);
                let finish_geo_len = self.get_face_point_rev_trav(intersection_point, face).0;
                Ok((intersection_point, geo_len - finish_geo_len, (i, j, k)))
            },
            None => {
                Ok((node.pos, self.get_on_edge_rev_trav(node)?.0, (i, j, k)))
            }
        }
    }

    /// This panics if a and b don't share a face.
    fn face_connected_to_edges(&self, a: OnEdge, b: OnEdge) -> Result<usize> {
        let [f1, f2] = self.faces_connected_to_edge(a)?;
        let [f3, f4] = self.faces_connected_to_edge(b)?;
        if f1 == f3 || f1 == f4 {
            Ok(f1)
        } else if f2 == f3 || f2 == f4 {
            Ok(f2)
        } else {
            panic!("a and b don't share a face.")
        }
    }

    // Double check that this works correctly backwards.
    fn move_on_circle(&self, circle: &[NodeOnEdge], mut curr_index: usize, curr_pos: PVec3, mut distance: f32) -> Result<StitchPoint> {
        let rev = distance < 0.0;
        let next_index: Box<dyn Fn(usize) -> usize> = if rev { Box::new(|curr_index| {
            if curr_index == 0 {
                circle.len() - 1
            } else {
                curr_index - 1
            }
        }) } else { Box::new(|curr_index| {
            (curr_index + 1) % circle.len()
        }) };

        distance = distance.abs();

        let mut cmp = if rev {
            circle[curr_index].pos
        } else {
            circle[next_index(curr_index)].pos
        };

        let mut required_distance = (cmp - curr_pos).magnitude();

        if required_distance > distance {
            let normalised = (cmp - curr_pos) / required_distance;
            return Ok(StitchPoint {
                face: self.face_connected_to_edges(circle[curr_index].edge, circle[next_index(curr_index)].edge)?,
                isoline_index: curr_index,
                pos: normalised * distance + curr_pos,
            })
        }

        while distance > required_distance {
            distance -= required_distance;
            curr_index = next_index(curr_index);
            
            cmp = circle[next_index(curr_index)].pos - circle[curr_index].pos;
            required_distance = cmp.magnitude();
        }

        let normalised = cmp / required_distance;
        Ok(StitchPoint {
            face: self.face_connected_to_edges(circle[curr_index].edge, circle[next_index(curr_index)].edge)?,
            isoline_index: curr_index,
            pos: normalised * distance + circle[curr_index].pos
        })
    }
}

fn maybe_neg(float: f32, neg: bool) -> f32 {
    if neg {
        -float
    } else {
        float
    }
}

#[derive(Clone, Copy, PartialEq)]
pub struct StitchPoint {
    face: usize,
    isoline_index: usize,
    pos: PVec3,
}

/// Calculates the horizontal distance between two points on the circle
// This can be optimised not in terms of max time complexity but mean time complexity
// due to the hierustic that pos1 is geographically near pos2.
fn dist_on_circle(circle: &[NodeOnEdge], circle_len: f32, mut index1: usize, mut pos1: PVec3, index2: usize, pos2: PVec3) -> f32 {
    let mut distance = 0.0;
    while index1 != index2 {
        let next_index = (index1 + 1) % circle.len();
        let pos = circle[index1].pos;
        distance += (pos - pos1).magnitude();
        
        pos1 = pos;
        index1 = next_index;
    }
    
    let result = (pos1 - pos2).magnitude() + distance;

    result.min(circle_len - result)
}