// This file was partially generated by AI (one five-line function)
// AI was used in this file to ensure correctness (without writing, unless otherwise documented)
// All AI generated text in this file is documented.

mod tree_preprocess;
use std::cmp::Ordering;
use std::collections::VecDeque;

use three_d::Srgba;

use crate::process::intermediate::tree_preprocess::NodeOnFace;
use crate::process::{Error, ErrorFault, Group, Processor, Result, cyclic_array_windows, failed_assert_internal};
use crate::process::sizes_calculator::FixedHookCalculator;
use crate::process::process_vec3::PVec3;
use crate::viewer::DisplayCommand;
use crate::process::isolines::NodeOnEdge;
use crate::process::connect::{CircleTree, IsolinesMap};

#[derive(Clone, Copy, PartialEq)]
pub enum InternalStitchCommand {
    MoveCurr(Highlight),
    MoveNext(Highlight),
    /// highlights are slip stitch, chain
    NextRow(Highlight, Highlight),
}

// fn nearest_stitch_size(relative_size: f32) -> f32 {
//     match relative_size {
//         0.0..1.25 => 1.0,
//         1.25..1.75 => 1.5,
//         1.75..2.5 => 2.0,
//         2.5.. => 3.0,
//         v => panic!("Incorrect value given to nearest_stitch_size: {v}")
//     }
// }


// This function was AI generated.
fn intersect(n: PVec3, a: PVec3, b: PVec3, c: PVec3, d: PVec3) -> PVec3 {
    let r = b - a;
    let t = (c - a).cross(d - c).dot(n) / r.cross(d - c).dot(n);
    a + r * t
}

#[derive(Clone, Copy, PartialEq)]
pub struct Highlight(pub HighlightPoint, pub HighlightPoint);

impl Highlight {
    pub fn null() -> Self {
        let null = HighlightPoint { pos: PVec3::splat(0.0), isoline_index: 0 };
        Self(null, null)
    }

    fn new(pos1: PVec3, isoline_index1: usize, pos2: PVec3, isoline_index_2: usize) -> Self {
        Self(HighlightPoint { pos: pos1, isoline_index: isoline_index1 }, HighlightPoint { pos: pos2, isoline_index: isoline_index_2 })
    }
}

#[derive(Clone, Copy, PartialEq)]
pub struct HighlightPoint {
    pub pos: PVec3,
    /// The index on the circle of the isoline,
    /// not the index in spaced_points
    pub isoline_index: usize
}

impl From<StitchPoint> for HighlightPoint {
    fn from(value: StitchPoint) -> Self {
        Self {
            pos: value.pos,
            isoline_index: value.isoline_index
        }
    }
}

pub struct BoundaryInfo {
    pub magic_circle: usize,
    pub magic_highlights: Vec<Highlight>,
    pub final_circle: Vec<StitchPoint>
}

impl Processor {
    /// This panics if self.info is None
    pub fn tree_into_stitches(&self, tree: CircleTree, sizes_calculator: FixedHookCalculator, isolines_map: &IsolinesMap) -> Result<(Vec<InternalStitchCommand>, BoundaryInfo)> {
        let info = self.get_info_unwrapped();
        let furthest_point = info.furthest_point.pos;
        let seed_point = info.seed_point;

        self.sender.send(DisplayCommand::ClearAll).unwrap();
        let scw = sizes_calculator.relative_to_stl(1.0, false);
        let sch = sizes_calculator.relative_to_stl(1.0, true);
        let mut internal_result = Vec::new();

        let tree = self.preprocess(tree, isolines_map, scw)?;

        let initial_stitches = tree.spaced_points.len();
        
        let mut curr = tree;
        // In order to change direction of initial stitches:
        const TARGET_DIR: bool = true;

        if let Some(dir) = curr.direction && dir != TARGET_DIR {
            curr.spaced_points = rev(curr.spaced_points)
        }

        let mut isoline = 0;
        let mut curr_point = curr.spaced_points[0];

        let mut magic_highlights = Vec::with_capacity(curr.spaced_points.len());
        for (i, [a, b]) in cyclic_array_windows(&curr.spaced_points).enumerate() {
            self.send_stitch(seed_point, b.pos, a.pos);
            magic_highlights.push(Highlight::new(seed_point, 0, a.pos, i ));
        }

        let mut final_circle = curr.spaced_points.clone();

        fn rev<T>(vec: Vec<T>) -> Vec<T> {
            let len = vec.len();
            let mut vd: VecDeque<T> = vec.into();
            let first = vd.pop_front();
            if let Some(first) = first {
                let mut result = Vec::with_capacity(len);
                result.push(first);
                let mut vec: Vec<T> = vd.into();
                vec.reverse();
                result.append(&mut vec);
                result
            } else {
                Vec::new()
            }
        }

        while let Some(mut next) = curr.children.pop() {
            if next.children.len() > 1 {
                self.sender.send(DisplayCommand::MeshVisible(false)).unwrap();
                return Err(Error {
                    issue: "Your object splits into multiple paths that you need to crochet seperately and stitch together.\nThis behaviour is not yet supported.".to_string(),
                    fault: ErrorFault::Code(None),
                    solution: "Chose a seed such that the object won't split, or chose a different object file.",
                })
            }
            
            let cmp_data: (usize, &IsolinesMap, &[NodeOnEdge], f32) = (isoline, isolines_map, &curr.isoline_points, curr.circle_len);
            let next_v = next.spaced_points[0];

            // Find which direction the next row goes in. We do not know this beforehand,
            // as the circles are stored in arbitrary order - the only things that's guarunteed are:
            // 1. each item in our circle is connected to the item directly before and after it (cyclically),
            // 2. no items are repeated.
            // 3. the item at index 0 in next is closest to the item at index 0 in curr (geodesic-wise)
            // However, we do have a hieuristic which likely worked, which tells us which direction it goes,
            // so we test this first.
            let next_h = curr.spaced_points[1];
            let same = *cyclic_move(&next.spaced_points, 0, false).1;
            let opposite = *cyclic_move(&next.spaced_points, 0, true).1;

            if let Some(dir) = next.direction {
                if dir != TARGET_DIR {
                    next.spaced_points = rev(next.spaced_points)
                }
            } else if self.cmp_horizontal_distance_next(cmp_data, next_h, same, opposite)? == Ordering::Greater {
                next.spaced_points = rev(next.spaced_points);
            }

            self.sender.send(DisplayCommand::Edge {
                a: curr_point.pos,
                b: next_v.pos,
                thickness: self.model.radius * 0.02,
                colour: Srgba::WHITE,
                depth: true,
                group: Group::Seam,
            }).unwrap();

            self.sender.send(DisplayCommand::Point {
                pos: curr_point.pos,
                radius: self.model.radius * 0.02,
                colour: Srgba::WHITE,
                depth: true,
                group: Group::Seam,
            }).unwrap();

            internal_result.push(InternalStitchCommand::NextRow(
                Highlight(HighlightPoint::from(*curr.spaced_points.last().unwrap()), HighlightPoint::from(*curr.spaced_points.first().unwrap())),
                Highlight(HighlightPoint::from(*curr.spaced_points.first().unwrap()), HighlightPoint::from(*next.spaced_points.first().unwrap()))
            ));

            let move_next_table: Vec<Vec<(f32, [StitchPoint; 3])>> = curr.spaced_points.iter().map(|const_p|
                cyclic_array_windows(&next.spaced_points).map(|[a, b]| (cost_function(*a, *b, *const_p), [*a, *b, *const_p])).collect()
            ).collect();

            let move_curr_table: Vec<Vec<(f32, [StitchPoint; 3])>> = cyclic_array_windows(&curr.spaced_points).map(|[a, b]| 
                next.spaced_points.iter().map(|const_p| (cost_function(*a, *b, *const_p), [*a, *b, *const_p])).collect()
            ).collect();

            // This is a 2D array
            let n = next.spaced_points.len(); // This goes with j.
            let m = curr.spaced_points.len(); // This goes with i.
            let mut costs: Vec<(f64, InternalStitchCommand, [StitchPoint; 3])> = Vec::with_capacity((n + 1) * (m + 1));

            let get_index = |i, j| {
                assert!(j <= n); // <= ensures we dont need +1
                // if i > m, this will panic anyway.
                i * (n + 1) + j
            };

            /// a is on the same row as b
            // BEWARE! Changing this function means you need to change the tolerance
            fn cost_function(a: StitchPoint, b: StitchPoint, c: StitchPoint) -> f32 {
                // PVec3::triangle_area(a.pos, b.pos, c.pos)
                (a.pos - c.pos).magnitude_squared() + (b.pos - c.pos).magnitude_squared()
            }
            // let nominal_cost = 

            // This tolerance doesn't just check for floating point error.
            // It also ensures to prefer 2sc as opposed to mildly more "optimal"
            // inc-dec pairs.
            //
            // 0.5 * scw * sch is nominal triangle, with 5% tolerance.
            // let tolerance = 0.05 * 0.5 * scw * sch;
            // 2.0 * (scw * scw + sch * sch) is nominal cost value, with 5% tolerance.
            let tolerance = 2.0 * (scw * scw + sch * sch) * 0.05;
            let tolerance = tolerance as f64;
            // let tolerance = f64::INFINITY;
            for i in 0..m + 1 {
                for j in 0..n + 1 {
                    use InternalStitchCommand::*;
                    // We can afford to do null here because any nulls will be pruned out by a min check.
                    let (i_cost, i_points) = if i == 0 { (f64::INFINITY, [StitchPoint::null(); 3]) } else {
                        let (cost, points) = move_curr_table[i - 1][j % n];
                        (cost as f64 + costs[get_index(i - 1, j)].0, points)
                    };
                    let (j_cost, j_points) = if j == 0 { (f64::INFINITY, [StitchPoint::null(); 3]) } else {
                        let (cost, points) = move_next_table[i % m][j - 1];
                        (cost as f64 + costs[get_index(i, j - 1)].0, points)
                    };

                    if i_cost == j_cost && i_cost == f64::INFINITY {
                        costs.push((0.0, NextRow(Highlight::null(), Highlight::null()), [StitchPoint::null(); 3]));
                        continue;
                    } else if i_cost == f64::INFINITY {
                        costs.push((j_cost, MoveNext(highlight_from_arr(&j_points)), j_points));
                        continue;
                    } else if j_cost == f64::INFINITY {
                        costs.push((i_cost, MoveCurr(highlight_from_arr(&i_points)), i_points));
                        continue;
                    }

                    fn highlight_from_arr(arr: &[StitchPoint; 3]) -> Highlight {
                        // ignores arr[0] as that point is now skipped.
                        Highlight(HighlightPoint::from(arr[1]), HighlightPoint::from(arr[2]))
                    }

                    // Let binding to ensure at compile time that all branches produce an output
                    // Coarse check
                    let value = if i_cost < j_cost {
                        // Check if we need to consider proportions
                        if j_cost - i_cost < tolerance &&
                            // Decide purely based on proportions
                            j as f32 / n as f32 > i as f32 / m as f32
                        {
                            // Both checks passed
                            (j_cost, MoveNext(highlight_from_arr(&j_points)), j_points)
                        } else {
                            // Some check didnt pass
                            (i_cost, MoveCurr(highlight_from_arr(&i_points)), i_points)
                        }
                    } else {
                        // Same thing, other way around
                        if i_cost - j_cost < tolerance &&
                            // This equal is here such that if i / m == j / n, then it produces the same
                            // output. This is important as there is actually a reasonable chance that
                            // they are equal, as the numerators and demoninators are both small integers.
                            // We want it to produce the same output if they are equal so that it produces
                            // a small "staircase" with Next, Curr, Next, Curr, ... instead of a steeper
                            // "staircase" with Next, Next, Curr, Curr, ..., in order to better lean towards 2sc.
                            i as f32 / m as f32 >= j as f32 / n as f32
                        {
                            (i_cost, MoveCurr(highlight_from_arr(&i_points)), i_points)
                        } else {
                            (j_cost, MoveNext(highlight_from_arr(&j_points)), j_points)
                        }
                    };

                    costs.push(value);
                }
            }

            let mut row = Vec::with_capacity(n + m);

            let mut index = (n + 1) * (m + 1) - 1;
            let mut nexts = 0;
            let mut currs = 0;
            let mut result = String::new();
            loop {
                match costs[index].1 {
                    InternalStitchCommand::MoveCurr(_) => {
                        row.push(costs[index]);
                        index -= n + 1;
                        currs += 1;
                        result.push('c');
                    },
                    InternalStitchCommand::MoveNext(_) => {
                        row.push(costs[index]);
                        index -= 1;
                        nexts += 1;
                        result.push('n');
                    },
                    // The highlights in this ISC are null, so they can be ignored.
                    InternalStitchCommand::NextRow(_, _) => break,
                }
            }

            assert_eq!(row.len(), n + m);
            assert_eq!(n, nexts);
            assert_eq!(m, currs);

            while let Some((_cost, item, triangle)) = row.pop() {
                match item {
                    InternalStitchCommand::MoveCurr(_) => self.send_stitch(triangle[1].pos, triangle[2].pos, triangle[0].pos),
                    InternalStitchCommand::MoveNext(_) => self.send_stitch(triangle[0].pos, triangle[2].pos, triangle[1].pos),
                    InternalStitchCommand::NextRow(_, _) => panic!("Impossible")
                }
                internal_result.push(item);
            }

            curr_point = next.spaced_points[0];
            final_circle = next.spaced_points.clone();
            curr = next;
            isoline += 1;
        }

        self.sender.send(DisplayCommand::Point {
            pos: curr_point.pos,
            radius: self.model.radius * 0.02,
            colour: Srgba::WHITE,
            depth: true,
            group: Group::Seam,
        }).unwrap();


        // internal_result.push(InternalStitchCommand::NextRow(
        //     Highlight(HighlightPoint::from(curr.spaced_points[curr.spaced_points.len() - 1]), HighlightPoint::from(curr.spaced_points[0])),
        //     Highlight::null()
        // ));

        for [a, b] in cyclic_array_windows(&curr.spaced_points) {
            self.send_stitch(b.pos, furthest_point, a.pos);
            internal_result.push(InternalStitchCommand::MoveCurr(Highlight((*a).into(), HighlightPoint { pos: furthest_point, isoline_index: 0 })));
        }

        self.sender.send(DisplayCommand::Clear(Group::Backtrack)).unwrap();
        self.sender.send(DisplayCommand::MeshVisible(false)).unwrap();
        Ok((internal_result, BoundaryInfo { magic_circle: initial_stitches, magic_highlights, final_circle }))
    }

    fn send_stitch(&self, a: PVec3, b: PVec3, prev_point: PVec3) {
        self.sender.send(DisplayCommand::Edge {
            a,
            b,
            thickness: self.model.radius * 0.01,
            colour: Srgba::new(80, 80, 0, 192),
            depth: true,
            group: Group::StitchFaceOutline,
        }).unwrap();
        self.sender.send(DisplayCommand::Face {
            a,
            b,
            c: prev_point,
            colour: Srgba::new(200, 200, 200, 255),
            depth: true,
            group: Group::Stitch,
        }).unwrap();
    }

    /// To be used to compare horizontal distance between a test point
    /// on this isoline, and two points on the next isoline.
    /// # Panics
    /// This panics if self.info is None
    fn cmp_horizontal_distance_next(&self, data: (usize, &IsolinesMap, &[NodeOnEdge], f32), test: StitchPoint, a: StitchPoint, b: StitchPoint) -> Result<Ordering> {
        Ok(self.get_horizontal_distance(data, test, a)?.total_cmp(&self.get_horizontal_distance(data, test, b)?))
    }

    // /// To be used to compare horizontal distance between a test point
    // /// on the next isoline, and two points on this isoline.
    // /// # Panics
    // /// This panics if self.info is None
    // fn cmp_horizontal_distance_curr(&self, data: (usize, &IsolinesMap, &[NodeOnEdge], f32), test: StitchPoint, a: StitchPoint, b: StitchPoint) -> Result<Ordering> {
    //     let (intersection, _, (_, _, k)) = self.get_rev_trav_intersection(test.pos, test.face, data.1, data.0)?;
    //     let da = dist_on_circle(data.2, data.3, k, intersection, a.isoline_index, a.pos);
    //     let db = dist_on_circle(data.2, data.3, k, intersection, b.isoline_index, b.pos);
    //     Ok(da.total_cmp(&db))
    // }

    /// To be used to find horizontal distance between points on the next isoline.
    fn get_horizontal_distance(&self, (current_isoline, isolines_map, circle, circle_len): (usize, &IsolinesMap, &[NodeOnEdge], f32), test: StitchPoint, a: StitchPoint) -> Result<f32> {
        let (pos, _vert_distance, (_i, _j, k)) = self.get_rev_trav_intersection(a.into(), isolines_map, Some(current_isoline))?;
        Ok(dist_on_circle(circle, circle_len, k, pos, test.isoline_index, test.pos))
    }

    /// The Ok variant returns `(intersection_point, len, (i, j, k))`
    /// 
    /// `intersection_point` is where the geodesic of start intersects isoline `current_isoline`.
    /// `current_isoline` is 0 indexed and starts on row 1, NOT seed_point. (so, the length of the
    /// geodesic from seed_point to `current_isoline` is `(current_isoline + 1) * sch`)
    /// 
    /// This means that if a current isoline is given, the i value will be the same.
    /// 
    /// the intersection point is on edge `k` - `k+1`, or exactly touches `k`.
    /// 
    /// `len` is the length from start to the intersection point.
    /// # Panics 
    /// This panics if `self.info` is `None`
    pub fn get_rev_trav_intersection(&self, start: NodeOnFace, isolines_map: &IsolinesMap, current_isoline: Option<usize>) -> Result<(PVec3, f32, (usize, usize, usize))> {
        let info = self.get_info_unwrapped();
        let nodes = &info.nodes;
        let seed_face = info.seed_face;
        let seed_point = info.seed_point;
        let start_face = start.face;
        let start = start.pos;

        let (geo_len, Some(mut prev)) = self.get_face_point_rev_trav(start, start_face) else {
            // This has been guarunteed by inspection
            assert_eq!(start_face, seed_face);
            if let Some(((i, j), pos, [(_, k), _])) = self.find_double_face_intersections(isolines_map, start_face, seed_point, start, current_isoline)?.pop() {
                return Ok((pos, (pos - start).magnitude(), (i, j, k)))
            } else {
                return Err(failed_assert_internal::<14>(None))
            }
        };

        self.sender.send(DisplayCommand::Edge {
            a: prev.pos,
            b: start,
            thickness: self.model.radius * 0.03,
            colour: Srgba::RED,
            depth: true,
            group: Group::Backtrack,
        }).unwrap();

        if let Some(((i, j), intersection, [(_, k), _])) = self.find_face_intersections(isolines_map, &prev, start_face, start, current_isoline)?.pop() {
            return Ok((intersection, (intersection - start).magnitude(), (i, j, k)))
        };

        let mut prev_geo_len = geo_len;

        let (((i, j), (node, k), poss), geo1, geo2) = loop {
            self.sender.send(DisplayCommand::Point {
                pos: prev.pos,
                radius: self.model.radius * 0.04,
                colour: Srgba::GREEN,
                depth: false,
                group: Group::Backtrack,
            }).unwrap();
            self.sender.send(DisplayCommand::Clear(Group::Backtrack)).unwrap();
            let (curr_geo_len, Some(curr)) = nodes.get(&prev).unwrap() else {
                if let Some(((i, j), intersection, [(_, k), _])) = self.find_face_intersections(isolines_map, &prev, info.seed_face, info.seed_point, current_isoline)?.pop() {
                    // For low mesh density near seed point
                    return Ok((intersection, (prev.pos - intersection).magnitude() + geo_len - prev_geo_len, (i, j, k)))
                } else {
                    self.sender.send(DisplayCommand::Clear(Group::Backtrack)).unwrap();
                    self.sender.send(DisplayCommand::Point {
                        pos: prev.pos,
                        radius: self.model.radius * 0.04,
                        colour: Srgba::RED,
                        depth: false,
                        group: Group::Backtrack,
                    }).unwrap();
                    // This happens due to a missed intersection.
                    // At this point in time, I'm fairly certain this function never misses intersections,
                    // which means that this arises due to incorrect isoline filters.
                    // If current_isoline is None, this is guarunteed to be a missed intersection, as there is no filter.
                    return Err(failed_assert_internal::<16>(Some(format!("{start:?}, {start_face}, {current_isoline:?}"))));
                };
            };

            self.sender.send(DisplayCommand::Edge {
                a: prev.pos,
                b: curr.pos,
                thickness: self.model.radius * 0.03,
                colour: Srgba::GREEN,
                depth: false,
                group: Group::Backtrack,
            }).unwrap();

            let Some(intersection) = self.find_intersections(isolines_map, &prev, curr, current_isoline)?.pop() else {
                prev = *curr;
                prev_geo_len = *curr_geo_len;
                continue;
            };

            let pos = match intersection.2 {
                Some((node2, _)) => {
                    let face = self.face_connected_to_edges(intersection.1.0.edge, node2.edge)?;
                    intersect(self.model.mesh.faces[face].normal.into(), intersection.1.0.pos, node2.pos, prev.pos, curr.pos)
                },
                None => {
                    intersection.1.0.pos
                }
            };

            self.sender.send(DisplayCommand::Point {
                pos,
                radius: self.model.radius * 0.04,
                colour: Srgba::BLUE,
                depth: false,
                group: Group::Backtrack,
            }).unwrap();

            break (intersection, prev, *curr)
        };

        match poss {
            Some((node2, _)) => {
                let face = self.face_connected_to_edges(node.edge, node2.edge)?;
                let intersection_point = intersect(self.model.mesh.faces[face].normal.into(), node.pos, node2.pos, geo1.pos, geo2.pos);
                let finish_geo_len = self.get_face_point_rev_trav(intersection_point, face).0;
                Ok((intersection_point, geo_len - finish_geo_len, (i, j, k)))
            },
            None => {
                Ok((node.pos, self.get_on_edge_rev_trav(node)?.0, (i, j, k)))
            }
        }
    }

    // Double check that this works correctly backwards.
    fn move_on_circle(&self, circle: &[NodeOnEdge], mut curr_index: usize, curr_pos: PVec3, mut distance: f32) -> Result<StitchPoint> {
        let rev = distance < 0.0;
        let next_index: Box<dyn Fn(usize) -> usize> = if rev { Box::new(|curr_index| {
            if curr_index == 0 {
                circle.len() - 1
            } else {
                curr_index - 1
            }
        }) } else { Box::new(|curr_index| {
            (curr_index + 1) % circle.len()
        }) };

        distance = distance.abs();

        let mut cmp = if rev {
            circle[curr_index].pos
        } else {
            circle[next_index(curr_index)].pos
        };

        let mut required_distance = (cmp - curr_pos).magnitude();

        if required_distance > distance {
            let normalised = (cmp - curr_pos) / required_distance;
            return Ok(StitchPoint {
                face: self.face_connected_to_edges(circle[curr_index].edge, circle[next_index(curr_index)].edge)?,
                isoline_index: curr_index,
                pos: normalised * distance + curr_pos,
            })
        }

        while distance > required_distance {
            distance -= required_distance;
            curr_index = next_index(curr_index);
            
            cmp = circle[next_index(curr_index)].pos - circle[curr_index].pos;
            required_distance = cmp.magnitude();
        }

        let normalised = cmp / required_distance;
        Ok(StitchPoint {
            face: self.face_connected_to_edges(circle[curr_index].edge, circle[next_index(curr_index)].edge)?,
            isoline_index: curr_index,
            pos: normalised * distance + circle[curr_index].pos
        })
    }
}

#[derive(Clone, Copy, PartialEq)]
pub struct StitchPoint {
    face: usize,
    /// The index on the circle of the isoline,
    /// not the index in spaced_points
    isoline_index: usize,
    pos: PVec3,
}

impl StitchPoint {
    fn null() -> Self {
        Self {
            face: 0,
            isoline_index: 0,
            pos: PVec3::splat(0.0),
        }
    }
}

/// Calculates the horizontal distance between two points on the circle
// This can be optimised not in terms of max time complexity but mean time complexity
// due to the hierustic that pos1 is geographically near pos2.
fn dist_on_circle(circle: &[NodeOnEdge], circle_len: f32, mut index1: usize, mut pos1: PVec3, index2: usize, pos2: PVec3) -> f32 {
    let mut distance = 0.0;
    while index1 != index2 {
        let next_index = (index1 + 1) % circle.len();
        let pos = circle[index1].pos;
        distance += (pos - pos1).magnitude();
        
        pos1 = pos;
        index1 = next_index;
    }
    
    let result = (pos1 - pos2).magnitude() + distance;

    result.min(circle_len - result)
}

// fn cyclic_index<T, I: Into<isize>>(vec: &[T], curr: usize, offset: I) -> (usize, &T) {
//     let offset = (offset.into() % vec.len() as isize) as usize;
//     let index = (curr + offset) % vec.len();
//     (index, &vec[index])
// }

fn cyclic_move<T>(vec: &[T], curr: usize, left: bool) -> (usize, &T) {
    if curr == 0 && left {
        (vec.len() - 1, vec.last().unwrap())
    } else {
        let index = if left { curr - 1 } else { (curr + 1) % vec.len() };
        (index, &vec[index])
    }
}