// This file was not generated by AI

use std::collections::{HashMap, HashSet};

use three_d::egui::emath::Float;

use super::*;

impl Processor {
    /// The output of this function is a list of all isolines, connected in a circle, e.g.
    /// ```
    /// [ // <- Outer list
    ///     [ // <- Isolines at geodesic length w
    ///         [Node1, Node2, Node3], // <- Circle 1
    ///         [Node4, Node5, Node6] // <- Circle 2
    ///         // (the fact that there are multiple lists in this list means the isoline is split)
    ///     ], 
    ///     [ // <- Isolines at geodesic length w * 2
    ///         [Node7, Node8, Node9] // <- Circle 3
    ///     ]
    /// ]
    /// ```
    pub fn isolines(&mut self, nodes: Vec<(OrderedFloat<f32>, Node)>, stitch_size: f32, epsilon: f32) -> Vec<Vec<Vec<NodeOnEdge>>> {
        let points = self.get_isoline_points(nodes, stitch_size, epsilon);
        let faces = self.connect_isoline_faces(points);
        self.connect_isoline_points(faces)
    }

    fn get_isoline_points(&mut self, nodes: Vec<(OrderedFloat<f32>, Node)>, stitch_size: f32, epsilon: f32) -> Vec<HashMap<OnEdge, Vec<PVec3>>> {
        // This could be optimised by moving this type conversion into dijkstras.rs immediately.
        // However, we need to store the longest length alongside this data, if this optimisation is used.
        let len = nodes[nodes.len() - 1].0.0;
        let old_ss = stitch_size;
        let total_lines = (len / old_ss).round();
        let stitch_size = len / total_lines;
        let div_1_stitch_size = 1.0 / stitch_size;
        println!("Stitch size off by {:.2}%", 100.0 * (1.0 - stitch_size / old_ss).abs());
        let mut map = HashMap::new();
        for (geo_len, node) in nodes {
            map.entry(node).insert_entry(geo_len);
        }

        let edges: HashSet<_> = self.model.mesh.faces.iter().flat_map(|face| {
            let v = face.vertices;
            [OnEdge::new(v[0], v[1]), OnEdge::new(v[1], v[2]), OnEdge::new(v[2], v[0])]
        }).collect();

        let mut isoline_points = vec![HashMap::new(); total_lines as usize];
        for OnEdge { a, b } in edges {
            let mut nodes = Vec::with_capacity(1);
            let node_a = self.node_from_vertex(a);
            let node_b = self.node_from_vertex(b);
            nodes.append(&mut self.spaced_points(a, b, epsilon).into_iter().map(|pos| {
                let node = self.node_from_spacing(a, b, pos);
                let geo_len = map.get(&node).unwrap();
                (node, geo_len.0)
            }).collect());
            nodes.push((node_a, map.get(&node_a).unwrap().0));

            let mut prev_line = map.get(&node_b).unwrap().0 * div_1_stitch_size;
            let mut prev_line_floor = prev_line.floor();
            let mut prev_node = node_b;

            for (node, len) in nodes {
                let pos = node.pos;
                let prev_pos = prev_node.pos;
                let line = len * div_1_stitch_size;
                let line_floor = line.floor();
                if line_floor != prev_line_floor {
                    assert_eq!((line_floor - prev_line_floor).abs(), 1.0);
                    let mid = line_floor.max(prev_line_floor);
                    let ib = (mid - prev_line) / (line - prev_line);
                    let ia = 1.0 - ib;

                    // This match ensures that the connectivity of our interpolated node is on the edge of our previous and current node.
                    let connectivity = match node.connectivity {
                        Connectivity::OnVertex(a) => match prev_node.connectivity {
                            Connectivity::OnVertex(b) => OnEdge::new(a, b),
                            Connectivity::OnEdge(a, b) => OnEdge::new(a, b),
                        },
                        Connectivity::OnEdge(a, b) => OnEdge::new(a, b),
                    };

                    // This `mid as usize` indexing might cause problems as, with float arithmetic, a * b / b != a
                    // In order to fix, store the furthest point or deal with it immediately instead.
                    isoline_points[mid as usize - 1].entry(connectivity).or_insert(Vec::with_capacity(1)).push(prev_pos * ia + pos * ib);
                    self.sender.send(DisplayCommand::Point { pos: (prev_pos * ia + pos * ib).into(), radius: self.model.radius * 0.025, colour: Srgba::WHITE, depth: true, temp: false }).unwrap();
                }
                prev_line = line;
                prev_line_floor = line_floor;
                prev_node = node;
            }
        }
        isoline_points
    }

    fn connect_isoline_faces(&self, points: Vec<HashMap<OnEdge, Vec<PVec3>>>) -> Vec<HashMap<usize, Vec<[NodeOnEdge; 2]>>> {
        let mut result = vec![HashMap::new(); points.len()];
        for (row, isoline) in points.into_iter().enumerate() {
            let mut faces = HashSet::new();
            for key in isoline.keys() {
                let [a,b ] = self.faces(*key);
                faces.insert(a);
                faces.insert(b);
            }

            for face in faces {
                let [v1, v2, v3] = self.model.mesh.faces[face].vertices;
                let connectivities = [[v1, v2], [v2, v3], [v3, v1]].map(|[a, b]| {
                    (self.model.mesh.vertices[a].into(), OnEdge::new(a, b))
                });
                let edges = connectivities.map(|(v, con)| (v, con, isoline.get(&con).cloned().unwrap_or_default()));

                // This is the sorted nodes, with each node "next to" the next.
                // This list is cyclical and might need a parity shift in some cases.
                // The wrong parity could lead to buggy behaviour down the line.
                let sorted_nodes: Vec<NodeOnEdge> = edges.into_iter().flat_map(|(v, con, mut vec)| {vec.sort_by_cached_key(|curr| (*curr - v).magnitude_squared().ord()); vec.into_iter().map(move |v| NodeOnEdge { edge: con, pos: v })}).collect();

                if sorted_nodes.is_empty() { continue; }
                assert!(sorted_nodes.len().is_multiple_of(2)); // Each face has an isoline going into and out of it.
                let returned = result[row].insert(face, (0..sorted_nodes.len()/2).map(|i| [sorted_nodes[i*2], sorted_nodes[i*2+1]]).collect());
                assert!(returned.is_none());
            }
        }

        result
    }

    fn connect_isoline_points(&mut self, faces: Vec<HashMap<usize, Vec<[NodeOnEdge; 2]>>>) -> Vec<Vec<Vec<NodeOnEdge>>> {
        let mut result = vec![Vec::new(); faces.len()];
        for (i, mut isoline) in faces.into_iter().enumerate() {
            while let Some(face) = isoline.keys().next() {
                let mut face = *face;
                let mut circle = Vec::new();
                let entry = isoline.get_mut(&face).unwrap();
                if entry.is_empty() { // superglue
                    isoline.remove(&face);
                    continue;
                }
                let line = entry.pop().unwrap();
                if entry.is_empty() {
                    isoline.remove(&face);
                }
                circle.push(line[0]);
                let mut next = line[1];
                while let Some((point, index)) = {
                    let index = self.other_face(face, next.edge);
                    let entry = isoline.get_mut(&index);
                    match entry {
                        Some(entry) => {
                            match entry.iter().position(|line| {
                                line.contains(&next)
                            }) {
                                Some(i) => {
                                    let value = entry.remove(i);
                                    let point = if value[0] == next {
                                        value[1]
                                    } else {
                                        value[0]
                                    };
        
                                    if entry.is_empty() {
                                        isoline.remove(&index);
                                    }
        
                                    Some((point, index))
                                },
                                None => None
                            }
                        },
                        None => None,
                    }
                } {
                    self.sender.send(DisplayCommand::Edge { a: point.pos.into(), b: next.pos.into(), thickness: self.model.radius * 0.02, colour: Srgba::BLUE, depth: true, temp: false }).unwrap();
                    next = point;
                    face = index;
                    circle.push(next);
                }
                self.sender.send(DisplayCommand::Edge { a: circle.first().unwrap().pos.into(), b: circle.last().unwrap().pos.into(), thickness: self.model.radius * 0.02, colour: Srgba::BLUE, depth: true, temp: false }).unwrap();
                result[i].push(circle);
            }
        }

        result
    }

    fn node_from_vertex(&self, index: usize) -> Node {
        Node { connectivity: Connectivity::OnVertex(index), pos: self.model.mesh.vertices[index].into() }
    }

    fn node_from_spacing(&self, a: usize, b: usize, pos: PVec3) -> Node {
        Node { connectivity: Connectivity::on_edge(a, b), pos }
    }

    fn other_face(&self, face: usize, edge: OnEdge) -> usize {
        let v1 = edge.a;
        let v2 = edge.b;
        let mut faces1 = self.vertex_to_faces[v1].clone();
        let faces2 = &self.vertex_to_faces[v2];
        assert!(faces1.contains(&face));
        faces1.retain(|curr| faces2.contains(curr) && *curr != face);
        assert!(faces1.len() == 1); // This could be possible if the STL file is degenerate, specifically not watertight.
        faces1.pop().unwrap()
    }

    fn faces(&self, edge: OnEdge) -> [usize; 2] {
        let v1 = edge.a;
        let v2 = edge.b;
        let mut faces1 = self.vertex_to_faces[v1].clone();
        let faces2 = &self.vertex_to_faces[v2];
        faces1.retain(|curr| faces2.contains(curr));
        assert!(faces1.len() == 2); // This could be possible if the STL file is degenerate, specifically not watertight.
        [faces1.pop().unwrap(), faces1.pop().unwrap()]
    }
}

#[derive(Debug, Copy, Clone, PartialEq, Eq, Hash, PartialOrd, Ord)]
struct OnEdge {
    a: usize,
    b: usize
}

impl OnEdge {
    fn new(a: usize, b: usize) -> Self {
        let (a, b) = if a >= b {
            (a, b)
        } else {
            (b, a)
        };
        Self { a, b }
    }
}

#[derive(Debug, Copy, Clone, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct NodeOnEdge {
    edge: OnEdge,
    pos: PVec3,
}