// This file was not generated by AI

use std::collections::HashSet;

use three_d::egui::emath::Float;

use super::*;

#[derive(Clone, Debug)]
pub struct Circle {
    pub len: f32,
    pub nodes: Vec<NodeOnEdge>,
    pub direction: Option<bool>,
}

type NoDirIsolinesVec = Vec<Vec<(f32, Vec<NodeOnEdge>)>>;
pub type IsolinesVec = Vec<Vec<Circle>>;
pub type IsolinesOnEdgeMap = Vec<DetHashMap<OnEdge, Vec<PVec3>>>;

impl Processor {
    /// The output of this function is a list of all isolines, connected in a circle, e.g.
    /// ```
    /// [ // <- Outer list
    ///     [ // <- Isolines at geodesic length w
    ///         [Node1, Node2, Node3], // <- Circle 1
    ///         [Node4, Node5, Node6] // <- Circle 2
    ///         // (the fact that there are multiple lists in this list means the isoline is split)
    ///     ], 
    ///     [ // <- Isolines at geodesic length w * 2
    ///         [Node7, Node8, Node9] // <- Circle 3
    ///     ]
    /// ]
    /// ```
    pub fn isolines(&self, dijkstras: &DijkstrasMap, furthest_len: f32, furthest_point: Node, stitch_size: f32, epsilon: f32) -> Result<(IsolinesVec, Node)> {
        let (points, furthest_point) = self.get_isoline_points(dijkstras, furthest_len, furthest_point, stitch_size, epsilon)?;
        let faces = self.connect_isoline_faces(points)?;
        let isolines = self.connect_isoline_points(faces)?;
        let isolines_lens: NoDirIsolinesVec = isolines.into_iter().map(|row|
            row.into_iter().map(|circle|
                (get_circle_len(&circle), circle)
            ).collect()
        ).collect();
        let result = self.prune_isolines(isolines_lens, stitch_size)?;
        let mut new = Vec::with_capacity(result.len());
        for isoline in result {
            let mut result = Vec::with_capacity(isoline.len());
            for (len, nodes) in isoline {
                result.push(Circle {
                    len,
                    direction: self.check_circle_direction(epsilon, dijkstras, &nodes)?,
                    nodes,
                });
            }
            new.push(result);
        };
        Ok((new, furthest_point))
    }

    fn get_isoline_points(&self, map: &DijkstrasMap, len: f32, furthest_point: Node, stitch_size: f32, epsilon: f32) -> Result<(IsolinesOnEdgeMap, Node)> {
        let old_ss = stitch_size;
        let total_lines = (len / old_ss).round();
        let utotal_lines = total_lines as usize;
        let stitch_size = len / total_lines;
        let div_1_stitch_size = 1.0 / stitch_size;
        println!("Stitch size off by {:.2}%", 100.0 * (1.0 - stitch_size / old_ss).abs());

        let edges: HashSet<_> = self.model.mesh.faces.iter().flat_map(|face| {
            let v = face.vertices;
            [OnEdge::new(v[0], v[1]), OnEdge::new(v[1], v[2]), OnEdge::new(v[2], v[0])]
        }).collect();

        let mut isoline_points = vec![DetHashMap::default(); utotal_lines - 1];
        for OnEdge { a, b } in edges {
            let mut nodes = Vec::with_capacity(1);
            let node_a = self.node_from_vertex(a);
            let node_b = self.node_from_vertex(b);
            nodes.append(&mut self.spaced_points(a, b, epsilon).into_iter().map(|pos| {
                let node = self.node_from_spacing(a, b, pos);
                let geo_len = map.get(&node).unwrap();
                (node, geo_len.0)
            }).collect());
            nodes.push((node_a, map.get(&node_a).unwrap().0));

            let mut prev_line = map.get(&node_b).unwrap().0 * div_1_stitch_size;
            let mut prev_line_floor = prev_line.floor();
            let mut prev_node = node_b;

            for (node, len) in nodes {
                let pos = node.pos;
                let prev_pos = prev_node.pos;
                let line = len * div_1_stitch_size;
                let line_floor = line.floor();
                if line_floor != prev_line_floor {
                    assert_internal::<5>(
                        (line_floor - prev_line_floor).abs() == 1.0,
                        Some(format!("{}", line_floor - prev_line_floor))
                    )?;
                    let mid = line_floor.max(prev_line_floor);
                    let ib = (mid - prev_line) / (line - prev_line);
                    let ia = 1.0 - ib;

                    // This match ensures that the connectivity of our interpolated node is on the edge of our previous and current node.
                    let connectivity = match node.connectivity {
                        Connectivity::OnVertex(a) => match prev_node.connectivity {
                            Connectivity::OnVertex(b) => OnEdge::new(a, b),
                            Connectivity::OnEdge(a, b) => OnEdge::new(a, b),
                        },
                        Connectivity::OnEdge(a, b) => OnEdge::new(a, b),
                    };

                    if mid as usize == utotal_lines { continue; }
                    isoline_points[mid as usize - 1].entry(connectivity).or_insert(Vec::with_capacity(1)).push(prev_pos * ia + pos * ib);
                    self.sender.send(DisplayCommand::Point { pos: prev_pos * ia + pos * ib, radius: self.model.radius * 0.025, colour: Srgba::WHITE, depth: true, group: Group::IsolinePoints }).unwrap();
                }
                prev_line = line;
                prev_line_floor = line_floor;
                prev_node = node;
            }
        }
        Ok((isoline_points, furthest_point))
    }

    fn connect_isoline_faces(&self, points: IsolinesOnEdgeMap) -> Result<Vec<DetHashMap<usize, Vec<[NodeOnEdge; 2]>>>> {
        let mut result = vec![DetHashMap::default(); points.len()];
        for (row, isoline) in points.into_iter().enumerate() {
            let mut faces = HashSet::new();
            for key in isoline.keys() {
                let [a, b] = self.faces_connected_to_edge(*key)?;
                faces.insert(a);
                faces.insert(b);
            }

            for face in faces {
                let [v1, v2, v3] = self.model.mesh.faces[face].vertices;
                let connectivities = [[v1, v2], [v2, v3], [v3, v1]].map(|[a, b]| {
                    (self.model.mesh.vertices[a].into(), OnEdge::new(a, b))
                });
                let edges = connectivities.map(|(v, con)| (v, con, isoline.get(&con).cloned().unwrap_or_default()));

                // This is the sorted nodes, with each node "next to" the next.
                // This list is cyclical and might need a parity shift in some cases.
                // The wrong parity could lead to buggy behaviour down the line.
                let sorted_nodes: Vec<NodeOnEdge> = edges.into_iter().flat_map(|(v, con, mut vec)| {vec.sort_by_cached_key(|curr| (*curr - v).magnitude_squared().ord()); vec.into_iter().map(move |v| NodeOnEdge { edge: con, pos: v })}).collect();
                
                if sorted_nodes.is_empty() { continue; }

                assert_internal::<6>(
                    sorted_nodes.len().is_multiple_of(2),
                    Some(format!("Each face has an isoline going into and out of it.\nlen: {}", sorted_nodes.len()))
                )?;

                // Estimate for correct parity by minimising total lengths.
                let parity_checked_sorted_nodes: Vec<NodeOnEdge>;
                if sorted_nodes.len() > 2 {
                    let curr_total = sorted_nodes.as_chunks().0.iter().map(|[a, b]| (a.pos - b.pos).magnitude()).sum::<f32>();
                    let other_total = sorted_nodes[1..].as_chunks().0.iter().map(|[a, b]| (a.pos - b.pos).magnitude()).sum::<f32>()
                                        + (sorted_nodes.first().unwrap().pos - sorted_nodes.last().unwrap().pos).magnitude();
                    if curr_total < other_total {
                        parity_checked_sorted_nodes = sorted_nodes;
                    } else {
                        let mut sorted_nodes = sorted_nodes;
                        let element = sorted_nodes.pop().unwrap();
                        sorted_nodes.insert(0, element);
                        parity_checked_sorted_nodes = sorted_nodes;
                    }
                } else {
                    parity_checked_sorted_nodes = sorted_nodes;
                }

                let returned = result[row].insert(face, (0..parity_checked_sorted_nodes.len()/2).map(|i| [parity_checked_sorted_nodes[i*2], parity_checked_sorted_nodes[i*2+1]]).collect());
                assert_internal::<7>(
                    returned.is_none(),
                    Some(format!("returned: {:?}", returned))
                )?;
            }
        }

        Ok(result)
    }

    fn connect_isoline_points(&self, faces: Vec<DetHashMap<usize, Vec<[NodeOnEdge; 2]>>>) -> Result<Vec<Vec<Vec<NodeOnEdge>>>> {
        let mut result = vec![Vec::new(); faces.len()];
        for (i, mut isoline) in faces.into_iter().enumerate() {
            while let Some(face) = isoline.keys().next() {
                let mut face = *face;
                let mut circle = Vec::new();
                let entry = isoline.get_mut(&face).unwrap();
                if entry.is_empty() { // superglue
                    isoline.remove(&face);
                    continue;
                }
                let line = entry.pop().unwrap();
                if entry.is_empty() {
                    isoline.remove(&face);
                }
                // circle.push(line[0]);
                let mut next = line[1];
                while let Some((point, index)) = {
                    let index = self.other_face(face, next.edge)?;
                    let entry = isoline.get_mut(&index);
                    match entry {
                        Some(entry) => {
                            match entry.iter().position(|line| {
                                line.contains(&next)
                            }) {
                                Some(i) => {
                                    let value = entry.remove(i);
                                    let point = if value[0] == next {
                                        value[1]
                                    } else {
                                        value[0]
                                    };
        
                                    if entry.is_empty() {
                                        isoline.remove(&index);
                                    }
        
                                    Some((point, index))
                                },
                                None => None
                            }
                        },
                        None => None,
                    }
                } {
                    self.sender.send(DisplayCommand::Edge {
                        a: point.pos,
                        b: next.pos,
                        thickness: self.model.radius * 0.02,
                        colour: Srgba::BLUE,
                        depth: true,
                        group: Group::IsolineConnectors
                    }).unwrap();
                    circle.push(next);
                    next = point;
                    face = index;
                }
                circle.push(next);

                self.sender.send(DisplayCommand::Edge {
                    a: circle.first().unwrap().pos,
                    b: circle.last().unwrap().pos,
                    thickness: self.model.radius * 0.02,
                    colour: Srgba::BLUE,
                    depth: true,
                    group: Group::IsolineConnectors
                }).unwrap();
                result[i].push(circle);
            }
        }

        Ok(result)
    }

    /// Some(true) is CW, Some(false) is CCW,
    /// None is a failure due to a degenerate file
    /// or due to insufficient information
    fn check_circle_direction(&self, epsilon: f32, dijkstras: &DijkstrasMap, circle: &[NodeOnEdge]) -> Result<Option<bool>> {
        let mut cw_votes = 0;
        let mut ccw_votes = 0;
        for [a, b] in cyclic_array_windows(circle) {
            if a.edge == b.edge { continue; };
            let face = self.face_connected_to_edges(a.edge, b.edge)?;
            // these infinity and null values are known to be overwritten, as the for loop is at least length 1
            // due to the chain.
            let mut min_len = f32::INFINITY;
            // this is a node "below" the isoline, for comparison
            let mut min_node = Node { connectivity: Connectivity::OnVertex(0), pos: PVec3::splat(0.0) };
            for [a, b] in self.edges_on_face(face) {
                let nodes = self.spaced_points(a, b, epsilon)
                    .into_iter()
                    .map(|pos| Node { connectivity: Connectivity::on_edge(a, b), pos })
                    .chain(Some(self.node_from_vertex(b)));
                for node in nodes {
                    let len = dijkstras.get(&node).unwrap().0;
                    if len < min_len {
                        min_len = len;
                        min_node = node;
                    }
                }
            }

            let verticies = self.model.mesh.faces[face].vertices;
            let index = |vertex| { verticies.iter().position(|v| *v == vertex).unwrap() };
            let indexed_a = [index(a.edge.a), index(a.edge.b)];
            let indexed_b = [index(b.edge.a), index(b.edge.b)];

            let sort = |[a, b]: [usize; 2]| {
                let ap = a.min(b);
                let bp = a.max(b);
                if ap + 1 == bp {
                    [ap, bp]
                } else {
                    [bp, ap]
                }
            };
            let sorted_indexed_a = sort(indexed_a);
            let sorted_indexed_b = sort(indexed_b);

            // Check if the start point and point a lies on the same edge, in this case no loop is required, and we
            // must check the distance to the start point.
            if let Connectivity::OnEdge(ea, eb) = min_node.connectivity && a.edge == (OnEdge { a: ea, b: eb }) {
                let start_pos = self.model.mesh.vertices[verticies[sorted_indexed_a[0]]].into();
                let diff = (min_node.pos - start_pos).magnitude_squared() - (a.pos - start_pos).magnitude_squared();
                if diff < 0.0 {
                    ccw_votes += 1;
                } else if diff > 0.0 {
                    cw_votes += 1;
                }
                continue;
            }

            // OnEdge order is constant
            if let Connectivity::OnEdge(ea, eb) = min_node.connectivity && b.edge == (OnEdge { a: ea, b: eb }) {
                let start_pos = self.model.mesh.vertices[verticies[sorted_indexed_b[0]]].into();
                let diff = (min_node.pos - start_pos).magnitude_squared() - (b.pos - start_pos).magnitude_squared();
                if diff < 0.0 {
                    cw_votes += 1;
                } else if diff > 0.0 {
                    ccw_votes += 1;
                }
                continue;
            }

            let vertex = match min_node.connectivity {
                Connectivity::OnVertex(a) => a,
                Connectivity::OnEdge(a, _) => a,
            };
            let min_i = index(vertex);

            let mut curr = sorted_indexed_a[1];
            let end = sorted_indexed_b[1];
            let mut broken = false;
            while curr != end {
                if curr == min_i {
                    cw_votes += 1;
                    broken = true;
                    break;
                }
                curr += 1;
                if curr == 3 {
                    curr = 0;
                }
            };

            if !broken {
                ccw_votes += 1;
            }
        }

        Ok(if cw_votes > ccw_votes {
            if cw_votes as f32 * 0.7 > ccw_votes as f32 {
                Some(true)
            } else {
                None
            }
        } else {
            if ccw_votes as f32 * 0.7 > cw_votes as f32 {
                Some(false)
            } else {
                None
            }
        })
    }

    fn prune_isolines(&self, isolines: NoDirIsolinesVec, stitch_size: f32) -> Result<NoDirIsolinesVec> {
        let draw_edge_point = |a: NodeOnEdge, b: NodeOnEdge, pruned| {
            let (group, edges, points, size) = if pruned {
                (Group::IsolineConnectors, Srgba::RED, Srgba::RED, 0.01 * self.model.radius)
            } else {
                (Group::IsolinePruned, Srgba::BLUE, Srgba::WHITE, 0.02 * self.model.radius)
            };
            self.sender.send(DisplayCommand::Edge {
                a: b.pos,
                b: (a.pos + b.pos) / 2.0,
                thickness: self.model.radius * 0.002 + size,
                colour: Srgba { r: 200, g: 255, b: 255, a: 255 },
                depth: !pruned,
                group
            }).unwrap();
            self.sender.send(DisplayCommand::Edge {
                a: a.pos,
                b: b.pos,
                thickness: size,
                colour: edges,
                depth: !pruned,
                group
            }).unwrap();
            self.sender.send(DisplayCommand::Point {
                pos: a.pos,
                radius: size,
                colour: points,
                depth: !pruned,
                group
            }).unwrap();
        };

        let mut result = vec![Vec::new(); isolines.len()];
        for (i, row) in isolines.into_iter().enumerate() {
            for (len, circle) in row {
                let circle_len = circle.len();
                if circle_len <= 2 || len < stitch_size * 1.5 {
                    for i in 0..circle_len {
                        draw_edge_point(circle[i], circle[(i + 1) % circle_len], true);
                    }
                    continue;
                }

                for i in 0..circle_len {
                    draw_edge_point(circle[i], circle[(i + 1) % circle_len], false);
                }


                self.sender.send(DisplayCommand::Edge {
                    a: circle[0].pos,
                    b: circle[circle.len() - 1].pos,
                    thickness: 0.024 * self.model.radius,
                    colour: Srgba { r: 255, g: 20, b: 255, a: 255 },
                    depth: true,
                    group: Group::IsolinePruned
                }).unwrap();

                result[i].push((len, circle));
            }
        }

        let len = result.len();
        for (i, row) in result.iter().enumerate() {
            assert_internal::<8>(
                !row.is_empty(),
                Some(format!("Empty isoline vec at {i} / {len}"))
            )?;
        }

        Ok(result)
    }

    pub fn node_from_vertex(&self, index: usize) -> Node {
        Node { connectivity: Connectivity::OnVertex(index), pos: self.model.mesh.vertices[index].into() }
    }

    pub fn node_from_spacing(&self, a: usize, b: usize, pos: PVec3) -> Node {
        Node { connectivity: Connectivity::on_edge(a, b), pos }
    }

    fn other_face(&self, face: usize, edge: OnEdge) -> Result<usize> {
        let v1 = edge.a;
        let v2 = edge.b;
        let mut faces1 = self.vertex_to_faces[v1].clone();
        let faces2 = &self.vertex_to_faces[v2];
        assert_internal::<9>(
            faces1.contains(&face),
            None
        )?;
        faces1.retain(|curr| faces2.contains(curr) && *curr != face);
        assert(
            faces1.len() == 1,
            "STL file is not watertight.",
            "Choose a different, watertight STL file.",
            ErrorFault::File
        )?;
        Ok(faces1.pop().unwrap())
    }

    pub(super) fn faces_connected_to_edge(&self, edge: OnEdge) -> Result<[usize; 2]> {
        let v1 = edge.a;
        let v2 = edge.b;
        let mut faces1 = self.vertex_to_faces[v1].clone();
        let faces2 = &self.vertex_to_faces[v2];
        faces1.retain(|curr| faces2.contains(curr));
        assert(
            faces1.len() == 2,
            "STL file is not watertight.",
            "Choose a different, watertight STL file.",
            ErrorFault::File
        )?;
        Ok([faces1.pop().unwrap(), faces1.pop().unwrap()])
    }
}

#[derive(Debug, Copy, Clone, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct OnEdge {
    pub a: usize,
    pub b: usize
}

impl OnEdge {
    pub fn new(a: usize, b: usize) -> Self {
        let (a, b) = if a >= b {
            (a, b)
        } else {
            (b, a)
        };
        Self { a, b }
    }

    // pub fn matching_vertex(&self, other: &Self) -> Option<usize> {
    //     if self.a == other.a || self.a == other.b {
    //         Some(self.a)
    //     } else if self.b == other.a || self.b == other.b {
    //         Some(self.b)
    //     } else {
    //         None
    //     }
    // }
}

#[derive(Debug, Copy, Clone, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct NodeOnEdge {
    pub edge: OnEdge,
    pub pos: PVec3,
}

// impl NodeOnEdge {
//     pub fn matching_vertex(&self, other: &Self) -> Option<usize> {
//         self.edge.matching_vertex(&other.edge)
//     }
// }

fn get_circle_len(circle: &[NodeOnEdge]) -> f32 {
    let mut result = 0.0;
    let len = circle.len();
    for i in 0..len {
        result += (circle[i].pos - circle[(i+1) % len].pos).magnitude()
    }

    result
}