// This file was not generated by AI

use std::{collections::HashMap, fmt::Display, sync::{Arc, Mutex}};

use three_d::{Srgba, egui::epaint::Hsva};
use tokio::sync::mpsc;
mod process_vec3;
pub use process_vec3::PVec3;
mod dijkstras;
mod isolines;
use isolines::NodeOnEdge;
mod connect;
mod intermediate;
mod sizes_calculator;
pub use sizes_calculator::{Measurement, SizesCalculator, FixedHookCalculator, MEASUREMENTS};
mod find_intersections;
mod stitches;
mod human_readable;

use crate::{model::Model, process::{isolines::IsolinesVec, stitches::{StitchCommand, StitchDisplay}}, viewer::DisplayCommand};
use std::result::Result as StdResult;

pub type Result<T> = StdResult<T, Error>;
#[cfg(debug_assertions)]
pub type DetHashMap<K, V> = HashMap<K, V, std::hash::BuildHasherDefault<std::hash::DefaultHasher>>;
#[cfg(not(debug_assertions))]
pub type DetHashMap<K, V> = HashMap<K, V>;
pub type DijkstrasMap = DetHashMap<Node, (f32, Option<Node>)>;

#[derive(Debug, serde::Serialize)]
pub struct Error {
    pub issue: String,
    pub fault: ErrorFault,
    pub solution: &'static str,
}

impl Display for Error {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let fault_text = match &self.fault {
            ErrorFault::Code(debug) => {
                match debug {
                    Some(debug) => format!("This is due to the code failing.\nDebug details:\n{debug}"),
                    None => "This is due to the code failing.\nThere are no debug details.".to_string(),
                }
            },
            ErrorFault::User => "This is due to a user error.".to_string(),
            ErrorFault::File => "This is due to a file error.".to_string(),
        };

        let issue = &self.issue;
        let solution = &self.solution;

        write!(f, "{issue}\n{fault_text}\n{solution}")
    }
}

#[derive(Debug, serde::Serialize)]
pub enum ErrorFault {
    Code(Option<String>),
    User,
    File,
}

fn assert(assertion: bool, issue: &'static str, solution: &'static str, fault: ErrorFault) -> Result<()> {
    if assertion {
        Result::Ok(())
    } else {
        Result::Err(Error { issue: issue.to_string(), fault, solution })
    }
}

fn assert_internal<const ERROR_NUM: u8>(assertion: bool, debug: Option<String>) -> Result<()> {
    if assertion {
        Result::Ok(())
    } else {
        Err(failed_assert_internal::<ERROR_NUM>(debug))
    }
}

fn failed_assert_internal<const ERROR_NUM: u8>(debug: Option<String>) -> Error {
    Error {
        issue: format!("Internal Error #{ERROR_NUM:0>3}"),
        fault: ErrorFault::Code(debug),
        solution: "Try again, or try moving the seed point slightly.",
    }
}

pub struct Processor {
    model: Arc<Model>,
    vertex_to_faces: Vec<Vec<usize>>,
    info: Option<GeneratedInfo>,
    sender: mpsc::UnboundedSender<DisplayCommand>,
    readable_commands: Option<StitchDisplay>,
    current_stitch_index: Arc<Mutex<Option<usize>>>,
}

#[derive(Debug, Copy, Clone, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum Connectivity {
    OnVertex(usize),
    /// Not to be used manually, as it leads to duplicates if the usizes are swapped.
    OnEdge(usize, usize)
}

impl Connectivity {
    fn on_edge(a: usize, b: usize) -> Self {
        let (a, b) = if a >= b {
            (a, b)
        } else {
            (b, a)
        };
        Self::OnEdge(a, b)
    }
}

#[derive(Debug, Copy, Clone, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct Node {
    connectivity: Connectivity,
    pos: PVec3,
}

pub enum ProcessorCommand {
    Generate {
        face_index: usize,
        position: PVec3,
        calculator: FixedHookCalculator,
    },
    ReverseTraverse {
        face_index: usize,
        position: PVec3,
    },
    HighlightStitch,
}



#[derive(Clone, Copy)]
pub enum Group {
    Seed,
    Dijkstras,
    IsolinePoints,
    IsolineConnectors,
    IsolinePruned,
    ReverseTraverse,
    Backtrack,
    Seam,
    StitchFaceOutline,
    Stitch,
    HighlightedStitch,
    StitchRow,
}

struct GeneratedInfo {
    /// Hashmap with some node, the geo-length to it from the seed point, and its potential predecessor.
    nodes: DijkstrasMap,
    epsilon: f32,
    seed_point: PVec3,
    seed_face: usize,
    isolines: IsolinesVec,
    furthest_point: Node,
}

#[derive(Debug, serde::Serialize)]
pub enum Output {
    None,
    /// String is already html encoded
    /// bool is whether it overwrites previous
    StitchCommands(String, bool),
}

#[derive(Clone)]
pub enum Sizes {
    RadiusDivisor(f32),
    Calculator {
        data: Vec<Measurement>,
        actual_diameter_cm: f32,
        hook_size_mm: f32
    }
}

impl Sizes {
    pub fn fixed_calculator(&self, model_radius: f32) -> Result<FixedHookCalculator> {
        match self {
            Sizes::RadiusDivisor(divisor) => {
                // This is some funky maths to get the scalars right.
                let calculator = SizesCalculator::new(&MEASUREMENTS, 1.0, 1.0)?;
                let predicted = calculator.relative_to_stl(1.0, 4.5, true);
                let calculator = SizesCalculator::new(&MEASUREMENTS, model_radius, divisor * predicted)?;
                let fixed_calculator = FixedHookCalculator::from_sizes_calculator(calculator, 4.5)?;
                Ok(fixed_calculator)
            },
            Sizes::Calculator { data, actual_diameter_cm, hook_size_mm } => {
                let calculator = SizesCalculator::new(data, model_radius * 2.0, *actual_diameter_cm)?;
                let fixed_calculator = FixedHookCalculator::from_sizes_calculator(calculator, *hook_size_mm)?;
                Ok(fixed_calculator)
            },
        }
    }
}

impl Processor {
    pub fn new(model: Arc<Model>, sender: mpsc::UnboundedSender<DisplayCommand>, current_stitch_index: Arc<Mutex<Option<usize>>>) -> Self {
        let mut vertex_to_faces: Vec<Vec<usize>> = std::iter::repeat_with(Vec::new).take(model.mesh.vertices.len()).collect();
        for (i, face) in model.mesh.faces.iter().enumerate() {
            for vertex in face.vertices {
                vertex_to_faces[vertex].push(i)
            }
        }
        vertex_to_faces.shrink_to_fit();
        Self { model, vertex_to_faces, sender, info: None, readable_commands: None, current_stitch_index }
    }

    pub fn run(&mut self, command: ProcessorCommand) -> Result<Output> {
        match command {
            ProcessorCommand::Generate { face_index, position, calculator } => self.generate_from_seed(position, face_index, calculator),
            ProcessorCommand::ReverseTraverse { face_index, position } => self.reverse_traverse(position, face_index),
            ProcessorCommand::HighlightStitch => self.highlight_stitch(),
        }
    }

    fn generate_from_seed(&mut self, position: PVec3, face_index: usize, calculator: FixedHookCalculator) -> Result<Output> {
        println!("{position:?} {face_index}");
        #[cfg(all(debug_assertions, not(target_arch = "wasm32")))]
        let position = PVec3::from([70.41322, 5.5, 68.19897]);
        // let position = Vector([69.16377, 5.500004, 69.32267]);
        #[cfg(all(debug_assertions, not(target_arch = "wasm32")))]
        let face_index = 0;
        // let face_index = 417;
        const STITCH_SIZE_EPSILON_MULTIPLIER: f32 = 0.25;
        
        let stitch_size = calculator.relative_to_stl(1.0, true);

        self.sender.send(DisplayCommand::ClearAll).unwrap();
        self.sender.send(DisplayCommand::Point { pos: position, radius: self.model.radius * 0.02, colour: Srgba::BLUE, depth: true, group: Group::Seed }).unwrap();
        let epsilon = stitch_size * STITCH_SIZE_EPSILON_MULTIPLIER;
        let (nodes, furthest_point) = self.dijkstras(epsilon, position, face_index)?;
        let furthest_len = nodes.get(&furthest_point).unwrap().0;
        println!("Diameter: {}; furthest_len: {furthest_len:?}", self.model.radius * 2.0);
        for (node, (geo_len, _pre)) in &nodes {
            // tokio::time::sleep(Duration::from_secs_f32(6.0 / len as f32)).await;
            self.sender.send(
                DisplayCommand::Point {
                    pos: node.pos,
                    radius: self.model.radius * 0.007,
                    colour: hsv(3.0 * geo_len / furthest_len, 1.0, 1.0),
                    depth: true,
                    group: Group::Dijkstras
                    
                }).unwrap()
            }
        
        let (isolines, furthest_point) = self.isolines(&nodes, furthest_len, furthest_point, stitch_size, stitch_size * STITCH_SIZE_EPSILON_MULTIPLIER)?;

        self.info = Some(GeneratedInfo { nodes, epsilon, seed_point: position, seed_face: face_index, isolines, furthest_point });
        let isolines = &self.info.as_ref().unwrap().isolines;

        let map = self.get_isoline_map(isolines);
        let tree = self.connect(&map, isolines)?;
        let (internal_stitches, boundary_info) = self.tree_into_stitches(tree, calculator, &map)?;
        let stitch_commands = StitchCommand::from_internal(internal_stitches, boundary_info.magic_circle, boundary_info.magic_highlights);
        let readable_commands = StitchDisplay::from_internal(stitches::StitchFormatChoice::Worded, stitch_commands, boundary_info.final_circle);
        self.overwrite_debug_stitches(&readable_commands);
        let result = format!("{readable_commands}");
        self.readable_commands = Some(readable_commands);
        Ok(Output::StitchCommands(result, false))
    }

    fn highlight_stitch(&self) -> Result<Output> {
        let Some(stitches) = &self.readable_commands else {
            return Err(Error {
                issue: "Cannot highlight stitches until you have generated stitches.".to_string(),
                fault: ErrorFault::User,
                solution: "First generate the stitches by left clicking.",
            })
        };

        let mut binding = self.current_stitch_index.lock().unwrap();
        let Some(index) = binding.as_mut() else {
            drop(binding);
            let result = self.display_from_value(stitches, None);
            return Ok(Output::StitchCommands(result, true))
        };
        
        if *index >= stitches.len() {
            *index = stitches.len() - 1;
        }

        let index = *index;
        drop(binding);

        let result = self.display_from_value(stitches, Some(index));

        Ok(Output::StitchCommands(result, true))
    }

    /// Takes verticies as inputs
    fn get_connected_faces(&self, v1: usize, v2: usize) -> Vec<usize> {
        let mut faces1 = self.vertex_to_faces[v1].clone();
        let faces2 = &self.vertex_to_faces[v2];
        faces1.retain(|face| faces2.contains(face));
        faces1
    }

    fn edges_on_face(&self, face: usize) -> [[usize; 2]; 3] {
        let v = self.model.mesh.faces[face].vertices;
        [[v[0], v[1]], [v[1], v[2]], [v[2], v[0]]]
    }

    /// Unwraps self.info with error message
    fn get_info_unwrapped(&self) -> &GeneratedInfo {
        self.info.as_ref().expect("This function should only be called after self.info has been set.")
    }
}

fn remove_duplicates<T: PartialEq>(vec: Vec<T>) -> Vec<T> {
    let mut new = Vec::new();
    for item in vec {
        if !new.contains(&item) {
            new.push(item);
        }
    }
    new
}

fn hsv(h: f32, s: f32, v: f32) -> Srgba {
    Hsva::new(h, s, v, 1.0).to_srgb().into()
}