// This file was not generated by AI

use std::{cell::RefCell, f32, sync::{Arc, Mutex}, time::Duration};

use stl_io::Vector;
use three_d::{Srgba, egui::{emath::OrderedFloat, epaint::Hsva}};
use tokio::sync::mpsc;
mod process_vec3;
use process_vec3::PVec3;
mod frontier;
use frontier::Frontier;

use crate::{model::Model, viewer::DisplayCommand};

type V3 = Vector<f32>;

pub async fn main(model: Arc<Model>, sender: mpsc::UnboundedSender<DisplayCommand>, receiver: mpsc::UnboundedReceiver<ProcessorCommand>) {
    let mut processor = Processor::new(sender, receiver, model);
    
    processor.run().await;
}

struct Processor {
    sender: mpsc::UnboundedSender<DisplayCommand>,
    receiver: mpsc::UnboundedReceiver<ProcessorCommand>,
    model: Arc<Model>,
    vertex_to_faces: Vec<Vec<usize>>
}

#[derive(Clone, Copy)]
struct Metadata {
    stitch_size: f32,
    seed_pos: PVec3,
    seed_face: usize
}

#[derive(Debug, Copy, Clone, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum Connectivity {
    OnVertex(usize),
    /// Not to be used manually, as it leads to duplicates if the usizes are swapped.
    OnEdge(usize, usize)
}

impl Connectivity {
    fn on_edge(a: usize, b: usize) -> Self {
        let (a, b) = if a >= b {
            (a, b)
        } else {
            (b, a)
        };
        Self::OnEdge(a, b)
    }
}

#[derive(Debug, Copy, Clone, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct Node {
    connectivity: Connectivity,
    pos: PVec3,
}

pub enum ProcessorCommand {
    MouseDownOnPoint {
        face_index: usize,
        position: V3
    }
}

impl Processor {
    fn new(sender: mpsc::UnboundedSender<DisplayCommand>, receiver: mpsc::UnboundedReceiver<ProcessorCommand>, model: Arc<Model>) -> Self {
        let mut vertex_to_faces: Vec<Vec<usize>> = std::iter::repeat_with(Vec::new).take(model.mesh.vertices.len()).collect();
        for (i, face) in model.mesh.faces.iter().enumerate() {
            for vertex in face.vertices {
                vertex_to_faces[vertex].push(i)
            }
        }
        Self { sender, receiver, model, vertex_to_faces }
    }

    async fn run(&mut self) {
        let ProcessorCommand::MouseDownOnPoint { face_index, position } = self.receiver.recv().await.unwrap();
        self.sender.send(DisplayCommand::Point { pos: position, radius: self.model.radius * 0.02, colour: Srgba::BLUE, depth: true, temp: false }).unwrap();
        let metadata = Metadata { stitch_size: self.model.radius / 15.0, seed_pos: position.into(), seed_face: face_index };
        let nodes = self.dijkstras(metadata);
        let furthest_len = nodes.last().unwrap().0;
        let len = nodes.len();
        println!("Diameter: {}; furthest_len: {furthest_len:?}", self.model.radius * 2.0);
        for (geo_len, node) in &nodes {
            // tokio::time::sleep(Duration::from_secs_f32(6.0 / len as f32)).await;
            self.sender.send(
                DisplayCommand::Point {
                    pos: node.pos.into(),
                    radius: self.model.radius * 0.007,
                    colour: Hsva::new(3.0 * geo_len.0 / furthest_len.0, 1.0, 1.0, 1.0).to_srgb().into(),
                    depth: true,
                    temp: false
            }).unwrap()
        }
    }

    fn dijkstras(&self, metadata: Metadata) -> Vec<(OrderedFloat<f32>, Node)> {
        let epsilon = metadata.stitch_size / 2.0;

        // Initialise the frontier with the points touching the same face
        let mut frontier = Frontier::new();
        for node in self.get_nodes_connected_to_face(metadata.seed_face, epsilon) {
            frontier.update(node, (metadata.seed_pos - node.pos).magnitude());
        }

        // Main Dijkstra's loop
        while let Some((node, geo_len)) = frontier.pop_store_smallest() {
            let nodes = self.get_connected_nodes(node.connectivity, epsilon);
            for updating_node in nodes {
                frontier.update(updating_node, geo_len + (updating_node.pos - node.pos).magnitude());
            }
        }

        frontier.get_output()
    }

    /// Find which nodes are connected to which other nodes, for use in Dijkstra's
    fn get_connected_nodes(&self, connectivity: Connectivity, epsilon: f32) -> Vec<Node> {
        // Find the faces a node is connected to.
        let faces = match connectivity {
            Connectivity::OnVertex(index) => self.vertex_to_faces[index].clone(),
            Connectivity::OnEdge(v1, v2) => self.get_connected_faces(v1, v2),
        };

        // Find the verticies that lie on these faces
        let verticies: Vec<_> = faces.into_iter().map(|face_index| self.model.mesh.faces[face_index].vertices).collect();

        // Use the verticies in order to find the vertex-pairs describing the edges of the face
        let edges: Vec<_> = if let Connectivity::OnEdge(exempt1, exempt2) = connectivity {
            verticies.iter().flat_map(|verticies|
                if verticies.iter().map(|v| (*v == exempt1 || *v == exempt2) as u8).sum::<u8>() < 2 {
                    let [v1, v2, v3] = verticies;
                    vec![(v1, v2), (v2, v3), (v3, v1)]
                } else {
                    // Ignore this edge if our node is on the same edge
                    vec![]
                }
            ).collect()
        } else {
            verticies.iter().flat_map(|[v1, v2, v3]| [(v1, v2), (v2, v3), (v3, v1)]).collect()
        };

        // Use these vertex-pair edges in order to find the spaced points along this edge
        let spaced_points: Vec<_> = edges.into_iter().flat_map(|(a, b)| {
            let pos_a = self.model.mesh.vertices[*a];
            let pos_b = self.model.mesh.vertices[*b];
            let posses = spaced_points(pos_a, pos_b, epsilon);
            posses.into_iter().map(|pos| Node { connectivity: Connectivity::on_edge(*a, *b), pos })
        }).collect();

        // Remove duplicated verticies
        let mut verticies = remove_duplicates(verticies.into_flattened());
        if let Connectivity::OnVertex(vertex) = connectivity {
            // If our node is on a vertex, remove that from the list we will return
            let index = verticies.iter().position(|v| *v == vertex).expect("The vertex we are finding connections to is connected to the face its connected to.");
            verticies.swap_remove(index);
        };

        let verticies = verticies.into_iter().map(|index|
            Node { connectivity: Connectivity::OnVertex(index), pos: self.model.mesh.vertices[index].into() }
        );
        
        let mut result = spaced_points;
        result.append(&mut verticies.collect());
        result
    }

    fn get_nodes_connected_to_face(&self, face_index: usize, epsilon: f32) -> Vec<Node> {
        // Find the verticies that lie on these faces
        let verticies = self.model.mesh.faces[face_index].vertices;

        // Use the verticies in order to find the vertex-pairs describing the edges of the face
        let v1 = verticies[0];
        let v2 = verticies[1];
        let v3 = verticies[2];
        let edges = [(v1, v2), (v2, v3), (v3, v1)];

        // Use these vertex-pair edges in order to find the spaced points along this edge
        let spaced_points: Vec<_> = edges.into_iter().flat_map(|(a, b)| {
            let pos_a = self.model.mesh.vertices[a];
            let pos_b = self.model.mesh.vertices[b];
            let posses = spaced_points(pos_a, pos_b, epsilon);
            posses.into_iter().map(move |pos| Node { connectivity: Connectivity::on_edge(a, b), pos })
        }).collect();

        // This function does not produce duplicates.


        let verticies = verticies.into_iter().map(|index|
            Node { connectivity: Connectivity::OnVertex(index), pos: self.model.mesh.vertices[index].into() }
        );
        
        let mut result = spaced_points;
        result.append(&mut verticies.collect());
        result
    }

    fn get_connected_faces(&self, v1: usize, v2: usize) -> Vec<usize> {
        let mut faces1 = self.vertex_to_faces[v1].clone();
        let faces2 = &self.vertex_to_faces[v2];
        faces1.retain(|face| faces2.contains(face));
        faces1
    }

    fn deref_face(&self, face_index: usize) -> [V3; 3] {
        let is = self.model.mesh.faces[face_index].vertices;
        is.map(|i| self.model.mesh.vertices[i])
    }

    fn send_indexed_face_command(&self, face_index: usize, colour: Srgba, depth: bool, temp: bool) {
        let [a, b, c] = self.deref_face(face_index);
        self.sender.send(DisplayCommand::Face { a, b, c, colour, depth, temp }).unwrap()
    }
}

// This function must ensure that the result is consistent (to the exact bit) if the inputs are the same.
// This is because I use these values in a HashSet.
// This means I can't use undefined precision functions such as sine and cosine, but sqrt and arithmetic operations are okay.
// In order to ensure I haven't accidentally used something undefined behind the scenes, I've implemented my own Vec3.
fn spaced_points(a: V3, b: V3, epsilon: f32) -> Vec<PVec3> {
    let a = PVec3::from(a);
    let b = PVec3::from(b);
    // This ensures a is always bigger than b
    let (a, b) = if a > b {
        (a, b)
    } else {
        (b, a)
    };
    let magnitude = (a - b).magnitude();
    let spaces = (magnitude / epsilon).ceil();
    let uspaces = spaces as usize - 1;
    let diff = (a - b) / spaces;
    let mut fin = b;
    let mut result = Vec::with_capacity(uspaces);
    for _ in 0..uspaces {
        fin += diff;
        result.push(fin);
    }
    result
}

fn remove_duplicates<T: PartialEq>(vec: Vec<T>) -> Vec<T> {
    let mut new = Vec::new();
    for item in vec {
        if !new.contains(&item) {
            new.push(item);
        }
    }
    new
}