// This file was not generated by AI

use std::{hash::Hash, ops::{Add, AddAssign, Div, Mul, MulAssign, Sub}};

use stl_io::Vector;
use three_d::Vec3;

#[derive(Debug, Copy, Clone, PartialEq)]
pub struct PVec3 {
    vec: [f32; 3]
}

impl Add for PVec3 {
    type Output = Self;

    fn add(self, rhs: Self) -> Self::Output {
        Self {
            vec: [self.vec[0] + rhs.vec[0], self.vec[1] + rhs.vec[1], self.vec[2] + rhs.vec[2]]
        }
    }
}

impl Sub for PVec3 {
    type Output = Self;

    fn sub(self, rhs: Self) -> Self::Output {
        
        Self {
            vec: [self.vec[0] - rhs.vec[0], self.vec[1] - rhs.vec[1], self.vec[2] - rhs.vec[2]]
        }
    }
}

impl Mul<f32> for PVec3 {
    type Output = Self;

    fn mul(self, rhs: f32) -> Self::Output {
        Self {
            vec: [self.vec[0] * rhs, self.vec[1] * rhs, self.vec[2] * rhs]
        }
    }
}

impl Mul<PVec3> for f32 {
    type Output = PVec3;

    fn mul(self, rhs: PVec3) -> Self::Output {
        rhs * self
    }
}

impl Div<f32> for PVec3 {
    type Output = Self;

    fn div(self, rhs: f32) -> Self::Output {
        let mul = 1.0 / rhs;
        self * mul
    }
}

impl AddAssign for PVec3 {
    fn add_assign(&mut self, rhs: Self) {
        *self = *self + rhs;
    }
}

impl MulAssign<f32> for PVec3 {
    fn mul_assign(&mut self, rhs: f32) {
        *self = *self * rhs;
    }
}

impl PVec3 {
    pub fn splat(value: f32) -> Self {
        Self { vec: [value; 3] }
    }

    pub fn magnitude(self) -> f32 {
        self.magnitude_squared().sqrt()
    }

    pub fn magnitude_squared(self) -> f32 {
        self.vec[0] * self.vec[0] + self.vec[1] * self.vec[1] + self.vec[2] * self.vec[2]
    }

    pub fn dot(self, other: Self) -> f32 {
        self.vec[0] * other.vec[0] +
        self.vec[1] * other.vec[1] +
        self.vec[2] * other.vec[2]
    }
}

impl From<Vector<f32>> for PVec3 {
    fn from(value: Vector<f32>) -> Self {
        Self {
            vec: value.0
        }
    }
}

impl From<Vec3> for PVec3 {
    fn from(value: Vec3) -> Self {
        Self {
            vec: [value.x, value.y, value.z]
        }
    }
}

impl From<PVec3> for Vector<f32> {
    fn from(val: PVec3) -> Self {
        Vector::<f32>::new(val.vec)
    }
}

impl From<PVec3> for Vec3 {
    fn from(val: PVec3) -> Self {
        Vec3::new(val.vec[0], val.vec[1], val.vec[2])
    }
}

use std::cmp::Ordering;

impl Ord for PVec3 {
    fn cmp(&self, other: &Self) -> Ordering {
        match self.vec[0].total_cmp(&other.vec[0]) {
            Ordering::Less => return Ordering::Less,
            Ordering::Greater => return Ordering::Greater,
            Ordering::Equal => (),
        }
        match self.vec[1].total_cmp(&other.vec[1]) {
            Ordering::Less => return Ordering::Less,
            Ordering::Greater => return Ordering::Greater,
            Ordering::Equal => (),
        }
        self.vec[2].total_cmp(&other.vec[2])
    }
}

impl PartialOrd for PVec3 {
    fn partial_cmp(&self, other: &Self) -> Option<Ordering> {
        Some(self.cmp(other))
    }
}

impl Eq for PVec3 {}

impl Hash for PVec3 {
    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
        self.vec.map(|f| f.to_bits()).hash(state);
    }
}