// This file was not generated by AI

use std::{hash::Hash, ops::{Add, AddAssign, Div, Mul, MulAssign, Sub}};

use stl_io::Vector;
use three_d::Vec3;

#[derive(Debug, Copy, Clone, PartialEq)]
pub struct PVec3 {
    vec: [f32; 3]
}

impl Add for PVec3 {
    type Output = Self;

    fn add(self, rhs: Self) -> Self::Output {
        Self {
            vec: [self.x() + rhs.vec[0], self.y() + rhs.vec[1], self.z() + rhs.vec[2]]
        }
    }
}

impl Sub for PVec3 {
    type Output = Self;

    fn sub(self, rhs: Self) -> Self::Output {
        
        Self {
            vec: [self.x() - rhs.vec[0], self.y() - rhs.vec[1], self.z() - rhs.vec[2]]
        }
    }
}

impl Mul<f32> for PVec3 {
    type Output = Self;

    fn mul(self, rhs: f32) -> Self::Output {
        Self {
            vec: [self.x() * rhs, self.y() * rhs, self.z() * rhs]
        }
    }
}

impl Mul<PVec3> for f32 {
    type Output = PVec3;

    fn mul(self, rhs: PVec3) -> Self::Output {
        rhs * self
    }
}

impl Div<f32> for PVec3 {
    type Output = Self;

    fn div(self, rhs: f32) -> Self::Output {
        let mul = 1.0 / rhs;
        self * mul
    }
}

impl AddAssign for PVec3 {
    fn add_assign(&mut self, rhs: Self) {
        *self = *self + rhs;
    }
}

impl MulAssign<f32> for PVec3 {
    fn mul_assign(&mut self, rhs: f32) {
        *self = *self * rhs;
    }
}

impl PVec3 {
    pub fn new(x: f32, y: f32, z: f32) -> Self {
        Self {
            vec: [x, y, z]
        }
    }

    pub fn splat(value: f32) -> Self {
        Self { vec: [value; 3] }
    }

    pub fn magnitude(self) -> f32 {
        self.magnitude_squared().sqrt()
    }

    pub fn magnitude_squared(self) -> f32 {
        self.x() * self.x() + self.y() * self.y() + self.z() * self.z()
    }

    pub fn dot(self, other: Self) -> f32 {
        self.x() * other.x() +
        self.y() * other.y() +
        self.z() * other.z()
    }

    #[inline(always)]
    pub fn x(&self) -> f32 {
        self.vec[0]
    }

    #[inline(always)]
    pub fn y(&self) -> f32 {
        self.vec[1]
    }

    #[inline(always)]
    pub fn z(&self) -> f32 {
        self.vec[2]
    }

    pub fn cross(self, other: Self) -> Self {
        Self { vec: [
            self.y() * other.z() - self.z() * other.y(),
            self.z() * other.x() - self.x() * other.z(),
            self.x() * other.y() - self.y() * other.x()
        ] }
    }

    pub fn triangle_area(a: Self, b: Self, c: Self) -> f32 {
        0.5 * (a - b).cross(a - c).magnitude()
    }
}

impl From<Vector<f32>> for PVec3 {
    fn from(value: Vector<f32>) -> Self {
        Self {
            vec: value.0
        }
    }
}

impl From<[f32; 3]> for PVec3 {
    fn from(value: [f32; 3]) -> Self {
        Self {
            vec: value
        }
    }
}

impl From<Vec3> for PVec3 {
    fn from(value: Vec3) -> Self {
        Self {
            vec: [value.x, value.y, value.z]
        }
    }
}

impl From<PVec3> for Vector<f32> {
    fn from(val: PVec3) -> Self {
        Vector::<f32>::new(val.vec)
    }
}

impl From<PVec3> for Vec3 {
    fn from(val: PVec3) -> Self {
        Vec3::new(val.vec[0], val.vec[1], val.vec[2])
    }
}

use std::cmp::Ordering;

impl Ord for PVec3 {
    fn cmp(&self, other: &Self) -> Ordering {
        match self.x().total_cmp(&other.x()) {
            Ordering::Less => return Ordering::Less,
            Ordering::Greater => return Ordering::Greater,
            Ordering::Equal => (),
        }
        match self.y().total_cmp(&other.y()) {
            Ordering::Less => return Ordering::Less,
            Ordering::Greater => return Ordering::Greater,
            Ordering::Equal => (),
        }
        self.z().total_cmp(&other.z())
    }
}

impl PartialOrd for PVec3 {
    fn partial_cmp(&self, other: &Self) -> Option<Ordering> {
        Some(self.cmp(other))
    }
}

impl Eq for PVec3 {}

impl Hash for PVec3 {
    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
        self.vec.map(|f| f.to_bits()).hash(state);
    }
}