// This file was partially generated by AI
// All AI used in this file is documented.

use std::println;

use crate::process::{Error, ErrorFault, Result, assert};

// This function was mostly written by AI
fn fit_plane(x1: &[f32], x2: &[f32], z: &[f32]) -> Result<nalgebra::Matrix<f32, nalgebra::Const<3>, nalgebra::Const<1>, nalgebra::ArrayStorage<f32, 3, 1>>> {
    use nalgebra::{OMatrix, Dyn, U3};
    
    type DesignMatrix = OMatrix<f32, Dyn, U3>;

    let n = x1.len();
    let mut x_data = Vec::with_capacity(n * 3);
    for i in 0..n {
        x_data.push(1.0);
        x_data.push(x1[i]);
        x_data.push(x2[i]);
    }
    let x = DesignMatrix::from_row_slice(&x_data);       // Dyn × U3, n inferred from x_data.len()/3
    let z = nalgebra::DVector::from_row_slice(z);         // still Dyn — length n

    let xt = x.transpose();       // U3 × Dyn
    let xtx = &xt * &x;           // U3 × U3

    match xtx.try_inverse() {
        Some(v) => Ok(v* &xt * z),
        None => Err(Error {
            issue: "Insufficient or inconsistent data in measurements.".to_string(),
            fault: ErrorFault::User,
            solution: "Double check and modify data, or revert to defaults."
        }),
    }  // U3 — statically length-3
}

pub struct Measurement {
    relative_size: f32,
    hook_size_mm: f32,
    measured_width_cm: f32,
    measured_height_cm: f32
}

impl Measurement {
    pub const fn new(relative_size: f32, hook_size_mm: f32, measured_width_cm: f32, measured_height_cm: f32) -> Self {
        Self { relative_size, hook_size_mm, measured_width_cm, measured_height_cm }
    }
}

#[derive(Debug)]
pub struct SizesCalculator {
    height_coeffs: (f32, f32, f32),
    width_coeffs: (f32, f32, f32),
}

impl SizesCalculator {
    pub fn new(data: &[Measurement], stl_diameter: f32, actual_diameter_cm: f32) -> Result<Self> {
        let mult_factor = stl_diameter / actual_diameter_cm;

        for measurement in data {
            let Measurement { relative_size, hook_size_mm, measured_width_cm, measured_height_cm } = measurement;
            println!("({relative_size}, {hook_size_mm}, {measured_width_cm})");
            println!("({relative_size}, {hook_size_mm}, {measured_height_cm})");
        }
        let x1 = data.iter().map(|measurement| measurement.relative_size).collect::<Vec<_>>();
        let x2 = data.iter().map(|measurement| measurement.hook_size_mm).collect::<Vec<_>>();
        let z = data.iter().map(|measurement| measurement.measured_height_cm).collect::<Vec<_>>();
        let height_coeffs = fit_plane(&x1, &x2, &z)? * mult_factor;
        
        let x1 = data.iter().map(|measurement| measurement.relative_size).collect::<Vec<_>>();
        let x2 = data.iter().map(|measurement| measurement.hook_size_mm).collect::<Vec<_>>();
        let z = data.iter().map(|measurement| measurement.measured_width_cm).collect::<Vec<_>>();
        let width_coeffs = fit_plane(&x1, &x2, &z)? * mult_factor;

        let result = Self {
            height_coeffs: (height_coeffs.x, height_coeffs.y, height_coeffs.z),
            width_coeffs: (width_coeffs.x, width_coeffs.y, width_coeffs.z),
        };

        let tests = [
            result.to_stl_units(1.0, 4.0, true),
            result.to_stl_units(3.0, 4.0, true),
            result.to_stl_units(1.0, 4.0, false),
            result.to_stl_units(3.0, 4.0, false),
            result.to_stl_units(1.0, 9.0, true),
            result.to_stl_units(3.0, 9.0, true),
            result.to_stl_units(1.0, 9.0, false),
            result.to_stl_units(3.0, 9.0, false),
        ];
        assert(
            tests.iter().all(|v| *v > 0.0),
            "Measurement values are predicting negative or zero lengths.",
            "Correct measurement values or revert to defaults.",
            ErrorFault::User
        )?;

        Ok(result)
    }

    pub fn to_stl_units(&self, relative_size: f32, hook_size_mm: f32, height: bool) -> f32 {
        if height {
            self.height_coeffs.0 + self.height_coeffs.1 * relative_size + self.height_coeffs.2 * hook_size_mm
        } else {
            self.width_coeffs.0 + self.width_coeffs.1 * relative_size + self.width_coeffs.2 * hook_size_mm
        }
    }
}

pub struct FixedHookCalculator {
    height_coeffs: (f32, f32),
    width_coeffs: (f32, f32),
}

impl FixedHookCalculator {
    pub fn from_sizes_calculator(calculator: SizesCalculator, hook_size_mm: f32) -> Result<Self> {
        let result = Self {
            height_coeffs: (calculator.height_coeffs.0 + calculator.height_coeffs.2 * hook_size_mm, calculator.height_coeffs.1),
            width_coeffs: (calculator.width_coeffs.0 + calculator.width_coeffs.2 * hook_size_mm, calculator.width_coeffs.1),
        };
        
        let tests = [
            result.to_stl_units(1.0, true),
            result.to_stl_units(3.0, true),
            result.to_stl_units(1.0, false),
            result.to_stl_units(3.0, false),
        ];
        assert(
            tests.iter().all(|v| *v > 0.0),
            "Measurement values are predicting negative or zero lengths.",
            "Correct measurement values or revert to defaults.",
            ErrorFault::User
        )?;

        Ok(result)
    }

    pub fn to_stl_units(&self, relative_size: f32, height: bool) -> f32 {
        if height {
            self.height_coeffs.0 + self.height_coeffs.1 * relative_size
        } else {
            self.width_coeffs.0 + self.width_coeffs.1 * relative_size
        }
    }

    pub fn from_stl_units(&self, stl_units: f32, height: bool) -> f32 {
        if height {
            (stl_units - self.height_coeffs.0) / self.height_coeffs.1
        } else {
            (stl_units - self.width_coeffs.0) / self.width_coeffs.1
        }
    }
}

const fn average(a: f32, b: f32) -> f32 {
    (a + b) * 0.5
}

pub const MEASUREMENTS: [Measurement; 7] = [
    Measurement::new(1.0, average(4.0, 4.5), 0.652444, 0.68469113),
    Measurement::new(1.0, average(5.5, 7.0), 0.832444, 0.97358),
    Measurement::new(1.0, 9.0, 1.052444, 1.1513578),
    Measurement::new(2.0, average(4.0, 4.5), 0.782444, 1.532444),
    Measurement::new(2.0, average(5.5, 7.0), 0.8703576, 1.94716),
    Measurement::new(3.0, average(4.0, 4.5), 0.7476764, 2.240555),
    Measurement::new(3.0, average(5.5, 7.0), 0.90827113, 2.92074),
];