// This file was not generated by AI

use std::{fmt::Display, ops::{Deref, DerefMut}};

use crate::{process::{Group, Processor, intermediate::{Highlight, HighlightPoint, InternalStitchCommand, StitchPoint}, representations::*, stitches::StitchCommand::Inc}, viewer::DisplayCommand};

#[cfg(not(target_arch = "wasm32"))]
use colored::Colorize;
use three_d::Srgba;

// TODO - update highlights to be more readable for the user
#[derive(PartialEq)]
pub enum StitchCommand {
    /// # Definition
    /// Inc(n) means put n stitches at the current pointer,
    /// and then move the current pointer one across.
    /// 
    /// # Useful identities
    /// * Inc(1) === sc === Dec(0)
    /// * Inc(0) === Skip(1)
    /// 
    /// ## Note that
    /// Inc(0) is used in the code to represent "nothing".
    /// This is because, how the code works, it assumes
    /// it will move the current pointer one across until
    /// proven otherwise, so when it reaches a state of
    /// "do nothing", it assumes Skip(1) === Inc(0).
    Inc(usize, Vec<Highlight>),
    /// # Definition
    /// Dec(n) means to put a stitch at the current pointer,
    /// then move the current pointer n + 1 across, such that
    /// there are n empty stitches between the two positions.
    /// 
    /// # Useful identities
    /// * Dec(0) === sc === Inc(1)
    Dec(usize, Vec<Highlight>),
    /// # Definition
    /// Skip(n) means do NOT put a stitch at the current pointer.
    /// Instead move it across n stitches (such that there are
    /// n - 1 empty stitches between the two positions).
    /// 
    /// # Useful identities
    /// * Skip(0) === "do nothing"
    /// * Skip(1) === "move to the next stitch"
    /// * sc + Skip(n) === Dec(n)
    /// * Dec(n) + Skip(m) === Dec(n + m)
    Skip(usize, Vec<Highlight>),
    /// # Definition
    /// MagicCircle(n) means create a magic circle with n
    /// stitch points. Do not yet connect off the ends of
    /// this magic circle, as this is handled by NextRow.
    MagicCircle(usize, Vec<Highlight>),
    /// # Definition
    /// Connect the end of the last stitch to the end of the chain,
    /// move the pointer to the next row, at the seam,
    /// and replace the next supposed stitch into a chain.
    NextRow(Vec<Highlight>),
}

#[derive(PartialEq, Debug, Clone, Copy)]
enum MoveStitch {
    Curr,
    Next
}

#[derive(Clone, Copy)]
struct Move {
    stitch: MoveStitch,
    highlight: Highlight,
}

impl Move {
    fn new(stitch: MoveStitch, highlight: Highlight) -> Self {
        Self { stitch, highlight }
    }
}

impl StitchCommand {
    fn row_to_stitches(chain: Highlight, row: &[Move]) -> Vec<Self> {
        let mut nexts: Vec<(HighlightPoint, Vec<(HighlightPoint, usize)>)> = Vec::new();
        let mut curr = 0;
        for i in row {
            if matches!(i.stitch, MoveStitch::Curr) {
                curr += 1;
            }
            if let Some((next, v)) = nexts.last_mut() && *next == i.highlight.1 {
                v.push((i.highlight.0, curr));
            } else {
                nexts.push((i.highlight.1, vec![(i.highlight.0, curr)]));
            }
        }

        let mut stitches = Vec::new();
        for (reference, vec) in &nexts {
            let ref_pos = reference.pos;
            let mut min_d = f32::INFINITY;
            let mut min_i = usize::MAX;
            let mut min_ii = usize::MAX;
            for (inner_index, &(check, index)) in vec.iter().enumerate() {
                let d = (ref_pos - check.pos).magnitude_squared();
                if d < min_d {
                    min_d = d;
                    min_i = index;
                    min_ii = inner_index;
                }
            }
            stitches.push((min_i, Highlight(vec[min_ii].0, *reference)));
        }
        
        let mut result = Vec::new();
        let mut prev_n;
        let start = stitches.first().unwrap().1;
        let mut prev_h;
        if start.0 == chain.0 {
            prev_h = vec![chain, start];
            prev_n = 2;
        } else {
            result.push(Inc(1, vec![chain]));
            prev_h = vec![start];
            prev_n = 1;
        }
        // Potentially push a 0 to the front of stitches.
        for &[(pa, _ha), (pb, hb)] in stitches.array_windows() {
            let d = pb - pa;
            if d == 0 {
                prev_h.push(hb);
                prev_n += 1;
            } else if d == 1 {
                result.push(Self::Inc(prev_n, prev_h));
                prev_n = 1;
                prev_h = vec![hb];
            } else if prev_n == 1 {
                result.push(Self::Dec(d - 1, prev_h));
                prev_n = 1;
                prev_h = vec![hb];
            } else {
                result.push(Self::Inc(prev_n, prev_h));
                result.push(Self::Skip(d - 1, vec![]));
                prev_n = 1;
                prev_h = vec![hb];
            }
        }
        result
    }

    pub fn from_internal(stitches: Vec<InternalStitchCommand>, magic_circle: usize, magic_highlights: Vec<Highlight>) -> Vec<Self> {
        use InternalStitchCommand as ISC;
        use MoveStitch::*;
        let mut result = vec![Self::MagicCircle(magic_circle, magic_highlights)];
        let ISC::NextRow(_, mut chain) = stitches[0] else { panic!("Impossible") };
        let mut currv = Vec::new();
        for stitch in stitches {
            let moving = match stitch {
                ISC::MoveCurr(highlight) => Move::new(Curr, highlight),
                ISC::MoveNext(highlight) => Move::new(Next, highlight),
                ISC::NextRow(ss, next_chain) => {
                    if !currv.is_empty() {
                        result.append(&mut Self::row_to_stitches(chain, &currv));
                        currv.clear();
                    }
                    chain = next_chain;
                    result.push(Self::NextRow(vec![ss]));
                    continue;
                }
            };
            currv.push(moving);
        }

        result.append(&mut Self::row_to_stitches(chain, &currv));
        
        result
    }
}

impl Processor {
    pub fn display_from_value(&self, display: &StitchDisplay, index: Option<usize>) -> String {
        let (string, highlights) = display.highlight_value(index);

        self.sender.send(DisplayCommand::Clear(Group::HighlightedStitch)).unwrap();

        for highlight in highlights {
            self.sender.send(DisplayCommand::Edge {
                a: highlight.0.pos,
                b: highlight.1.pos,
                thickness: self.model.radius * 0.02,
                colour: Srgba::RED,
                depth: false,
                group: Group::HighlightedStitch
            }).unwrap();
            self.sender.send(DisplayCommand::Point {
                pos: highlight.0.pos,
                radius: self.model.radius * 0.02,
                colour: Srgba::RED,
                depth: false,
                group: Group::HighlightedStitch
            }).unwrap();
            self.sender.send(DisplayCommand::Point {
                pos: highlight.1.pos,
                radius: self.model.radius * 0.02,
                colour: Srgba::RED,
                depth: false,
                group: Group::HighlightedStitch
            }).unwrap();
        }

        string
    }

    pub fn overwrite_debug_stitches(&self, display: &StitchDisplay) {
        self.sender.send(DisplayCommand::Clear(Group::StitchFaceOutline)).unwrap();

        for highlight in display.iter().flat_map(|(_, highlight, _)| highlight) {
            self.sender.send(DisplayCommand::Edge {
                a: highlight.0.pos,
                b: highlight.1.pos,
                thickness: self.model.radius * 0.015,
                colour: Srgba::new(80, 80, 0, 192),
                depth: true,
                group: Group::Stitch
            }).unwrap()
        }
    }
}

pub enum StitchFormatter {
    StitchPoint(Vec<(StitchPointFormat, Vec<Highlight>)>),
    Worded(Vec<(WordedFormat, Vec<Highlight>)>),
    CrochetParade(Vec<(CrochetParadeFormat, Vec<Highlight>)>),
}

impl StitchFormatter {
    fn from_intermediate(format: StitchFormatChoice, vec: Vec<StitchCommand>, final_highlights: Vec<StitchPoint>) -> Self {
        match format {
            StitchFormatChoice::StitchPoint => Self::StitchPoint(StitchPointFormat::from_intermediate(vec.into())),
            StitchFormatChoice::Worded => Self::Worded(WordedFormat::from_intermediate(vec.into(), final_highlights)),
            StitchFormatChoice::CrochetParade => Self::CrochetParade(CrochetParadeFormat::from_intermediate(vec.into())),
        }
    }
}

pub struct StitchDisplay {
    vec: Vec<(String, Vec<Highlight>, HighlightConf)>,
    seperator: &'static str
}

impl StitchDisplay {
    fn from_formatter(formatter: StitchFormatter) -> Self {
        let (vec, seperator) = match formatter {
            StitchFormatter::StitchPoint(items) => (
                items.into_iter().map(|(v, h)| (v.to_string(), h, v.get_conf())).collect(),
                StitchPointFormat::SEPERATOR
            ),
            StitchFormatter::Worded(items) => (
                items.into_iter().map(|(v, h)| (v.to_string(), h, v.get_conf())).collect(),
                WordedFormat::SEPERATOR
            ),
            StitchFormatter::CrochetParade(items) => (
                items.into_iter().map(|(v, h)| (v.to_string(), h, v.get_conf())).collect(),
                CrochetParadeFormat::SEPERATOR
            ),
        };

        Self { vec, seperator }
    }

    pub fn from_internal(format: StitchFormatChoice, vec: Vec<StitchCommand>, final_highlights: Vec<StitchPoint>) -> Self {
        let formatter = StitchFormatter::from_intermediate(format, vec, final_highlights);
        Self::from_formatter(formatter)
    }

    pub fn highlight_value(&self, index: Option<usize>) -> (String, Vec<Highlight>) {
        let mut result_str = String::new();
        let mut result_highlights = Vec::new();
        for (i, (string, highlights, config)) in self.vec.iter().enumerate() {
            result_str.push_str(&config.prefix);
            if Some(i) == index {
                #[cfg(target_arch = "wasm32")]
                result_str.push_str(&format!("<b>&lt;{}&gt;</b>", string));
                #[cfg(not(target_arch = "wasm32"))]
                result_str.push_str(&format!("<{}>", string).bold().to_string());
                result_highlights.append(&mut highlights.clone());
            } else {
                result_str.push_str(string);
            }
            result_str.push_str(&config.suffix);

            if config.seperator_follows && i != self.vec.len() - 1 && self.vec[i+1].2.seperator_predecesses {
                result_str.push_str(self.seperator);
            }
        }

        (result_str, result_highlights)
    }
}

impl Deref for StitchDisplay {
    type Target = Vec<(String, Vec<Highlight>, HighlightConf)>;

    fn deref(&self) -> &Self::Target {
        &self.vec
    }
}

impl DerefMut for StitchDisplay {
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.vec
    }
}

impl Display for StitchDisplay {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.highlight_value(None).0)
    }
}

#[derive(Clone)]
pub struct HighlightConf {
    /// This is not highlighted
    prefix: String,
    /// This is not highlighted
    suffix: String,
    seperator_predecesses: bool,
    seperator_follows: bool,
}

impl HighlightConf {
    pub fn new(prefix: String, suffix: String, seperator_predecesses: bool, seperator_follows: bool) -> Self {
        Self { prefix, suffix, seperator_predecesses, seperator_follows }
    }

    // pub fn no_seperator() -> Self {
    //     Self { seperator_follows: false, ..Default::default() }
    // }

    pub fn space_seperator() -> Self {
        Self { prefix: String::new(), suffix: " ".to_string(), seperator_predecesses: true, seperator_follows: false}
    }
}

impl Default for HighlightConf {
    fn default() -> Self {
        Self { prefix: String::new(), suffix: String::new(), seperator_predecesses: true, seperator_follows: true }
    }
}