// This file was not generated by AI

use crate::process::{Error, ErrorFault, Processor, Result, connect::CircleTree, process_vec3::PVec3, sizes_calculator::FixedHookCalculator};

pub enum StitchCommand {
    Single,
    Inc(usize),
    Dec(usize),
    MagicCircle(usize),
}

fn nearest_stitch_size(relative_size: f32) -> f32 {
    match relative_size {
        0.0..1.25 => 1.0,
        1.25..1.75 => 1.5,
        1.75..2.5 => 2.0,
        2.5.. => 3.0,
        v => panic!("Incorrect value given to nearest_stitch_size: {v}")
    }
}


/// This panics if a == b.
/// 
/// This returns a result such that:
/// a*lambda + b*(1-lambda) is the closest
/// point to p that lies on the LINE ab.
fn calc_lambda(p: PVec3, a: PVec3, b: PVec3) -> f32 {
    let v = a - b;
    (p - b).dot(v) / v.dot(v)
}

/// This returns a result such that:
/// a*lambda + b*(1-lambda) is the closest
/// point to p that lies on the SEGMENT ab.
fn calc_clamped_lambda(p: PVec3, a: PVec3, b: PVec3) -> f32 {
    calc_lambda(p, a, b).clamp(0.0, 1.0)
}

/// This returns a result such that:
/// the result is the closest point to p that lies on the SEGMENT ab.
fn calc_nearest_point(p: PVec3, a: PVec3, b: PVec3) -> PVec3 {
    if a == b {
        a
    } else {
        let lambda = calc_clamped_lambda(p, a, b);
        a * lambda + b * (1.0 - lambda)
    }
}

use StitchCommand as SC;

impl Processor {
    pub fn tree_into_stitches(&self, tree: CircleTree, sizes_calculator: FixedHookCalculator) -> Result<Vec<StitchCommand>> {
        let scw = sizes_calculator.to_stl_units(1.0, false);
        let sch = sizes_calculator.to_stl_units(1.0, true);
        
        let mut result = Vec::new();
        let initial_stitches = (tree.circle_len / scw).round();
        result.push(SC::MagicCircle(initial_stitches as usize));
    
        let mut curr = tree;
        while let Some(next) = curr.children.pop() {
            if curr.children.len() > 1 {
                return Err(Error {
                    issue: "Your object splits into multiple paths that you need to crochet seperately and stitch together.\nThis behaviour is not yet supported.".to_string(),
                    fault: ErrorFault::Code(None),
                    solution: "Chose a seed such that the object won't split, or chose a different object file.",
                })
            }

            let curr_len = curr.circle_len;
            let next_v_len = next.circle_len;

            let mut curr_point_index = 0;
            let mut curr_point = curr.circle[curr_point_index];
            let (mut next_v_point_index, mut next_v_point) = {
                let mut min_i = 0;
                let mut min_d = f32::INFINITY;
                let mut min_n = PVec3::splat(0.0);
                let comparison_pos = curr_point.pos;
                for (i, [a, b]) in next.circle
                    .array_windows()
                    .map(|[a,b]| [a, b]) // Type conversion from &[_; 2] to [&_; 2]
                    .chain(Some([next.circle.last().unwrap(), next.circle.first().unwrap()]))
                    .enumerate()
                {
                    let n = calc_nearest_point(comparison_pos, a.pos, b.pos);
                    let d = (comparison_pos - n).magnitude_squared();
                    // This is less than or equal in order to get the right index if the nearest is on vertex.
                    if d <= min_d {
                        min_i = i;
                        min_d = d;
                        min_n = n;
                    }
                }
                (min_i, min_n)
            };

            curr = next;
        }
        // todo!()
        Err(Error { issue: "".to_string(), fault: ErrorFault::User, solution: "no solution" })
    }
}