// This file was not generated by AI

use std::{collections::VecDeque, fmt::Display};

use crate::process::{intermediate::Highlight, stitches::{HighlightConf, StitchCommand}};


pub enum Format {
    /// ring\nsc<n>inc
    MagicCircle(usize),
    /// sc
    Sc,
    /// sc<n>inc
    Inc(usize),
    /// sc,<n>sk  -- OR with tog: sc<n+1>tog
    Dec(usize),
    /// <n>sk
    Skip(usize),
    /// \n
    NextRow,
    /// @[-1,0]
    Anchor,
}

impl Format {
    pub const SEPERATOR: &str = ",";

    pub fn from_intermediate(mut vec: VecDeque<StitchCommand>) -> Vec<(Self, Vec<Highlight>)> {
        let mut result = Vec::new();
        let StitchCommand::MagicCircle(circle, highlights) = vec.pop_front().unwrap() else { panic!("Unexpected stitch") };
        result.push((Self::MagicCircle(circle), highlights));
        let StitchCommand::NextRow(highlights) = vec.pop_front().unwrap() else { panic!("Unexpected stitch") };
        result.push((Self::NextRow, highlights));
        let mut nr = 0;

        for item in vec {
            match item {
                StitchCommand::Inc(n, highlights) => if n == 1 {
                    result.push((Self::Sc, highlights))
                } else {
                    result.push((Self::Inc(n), highlights))
                },
                StitchCommand::Dec(n, highlights) => result.push((Self::Dec(n), highlights)),
                StitchCommand::Skip(n, highlights) => result.push((Self::Skip(n), highlights)),
                StitchCommand::NextRow(highlights) => {result.push((Self::NextRow, highlights)); nr = 2},
                StitchCommand::MagicCircle(_n, _highlights) => panic!("Unexpected magic circle."),
            }
            if nr == 1 {
                result.push((Self::Anchor, Vec::new()));
            }
            if nr > 0 {
                nr -= 1;
            }
        }

        result
    }

    pub fn get_conf(&self) -> HighlightConf {
        match self {
            Format::NextRow => HighlightConf::new(String::new(), String::new(), false, false),
            Format::Anchor => HighlightConf::new(String::new(), String::new(), false, true),
            _ => HighlightConf::default()
        }
    }
}


impl Display for Format {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Format::MagicCircle(n) => write!(f, "ring\nsc{n}inc"),
            Format::Sc => write!(f, "sc"),
            Format::Inc(n) => write!(f, "sc{n}inc"),
            Format::Dec(n) => write!(f, "sc,{n}sk"),
            Format::Skip(n) => write!(f, "{n}sk"),
            #[allow(clippy::write_with_newline)] // For clarity and consistency
            Format::NextRow => write!(f, "\n"),
            Format::Anchor => write!(f, "@[-1,0]"),
        }
    }
}