// This file was not generated by AI

use std::{collections::HashSet, sync::Arc, time::Duration};

use stl_io::Vector;
use three_d::Srgba;
use tokio::sync::mpsc;

use crate::{model::Model, viewer::DisplayCommand};

pub enum ProcessorCommand {
    MouseDownOnPoint {
        face_index: usize,
        position: Vector<f32>
    }
}

pub async fn main(model: Arc<Model>, sender: mpsc::UnboundedSender<DisplayCommand>, receiver: mpsc::UnboundedReceiver<ProcessorCommand>) {
    let mut vertex_to_faces: Vec<Vec<usize>> = std::iter::repeat_with(Vec::new).take(model.mesh.vertices.len()).collect();
    for (i, face) in model.mesh.faces.iter().enumerate() {
        for vertex in face.vertices {
            vertex_to_faces[vertex].push(i)
        }
    }
    let mut processor = Processor { sender, receiver, model, vertex_to_faces };

    processor.run().await;
}

struct Processor {
    sender: mpsc::UnboundedSender<DisplayCommand>,
    receiver: mpsc::UnboundedReceiver<ProcessorCommand>,
    model: Arc<Model>,
    vertex_to_faces: Vec<Vec<usize>>
}

impl Processor {
    async fn run(&mut self) {
        let ProcessorCommand::MouseDownOnPoint { face_index, position } = self.receiver.recv().await.unwrap();
        self.sender.send(DisplayCommand::Point { pos: position, radius: self.model.radius * 0.02, colour: Srgba::BLUE, depth: true, temp: false }).unwrap();
        let mut faces = HashSet::new();
        let mut edge_faces = HashSet::new();
        edge_faces.insert(face_index);
        self.send_indexed_face_command(face_index, Srgba::GREEN, true, true);
        loop {
            tokio::time::sleep(Duration::from_secs(1)).await;
            self.sender.send(DisplayCommand::ClearTempFaces).unwrap();
            let mut verticies = Vec::new();
            for face_index in &edge_faces {
                self.send_indexed_face_command(*face_index, Srgba::RED, true, false);
                for vertex in self.model.mesh.faces[*face_index].vertices {
                    verticies.push(vertex);
                }
                faces.insert(*face_index);
            }
            for vertex in verticies {
                for face in &self.vertex_to_faces[vertex] {
                    edge_faces.insert(*face);
                }
            }
            edge_faces = edge_faces.difference(&faces).cloned().collect();
            for face_index in &edge_faces {
                self.send_indexed_face_command(*face_index, Srgba::GREEN, true, true);
            }
        }
    }

    fn get_connected_faces(&self, v1: usize, v2: usize) -> Vec<usize> {
        let mut faces1 = self.vertex_to_faces[v1].clone();
        let faces2 = &self.vertex_to_faces[v2];
        faces1.retain(|face| faces2.contains(face));
        faces1
    }

    fn deref_face(&self, face_index: usize) -> [Vector<f32>; 3] {
        let is = self.model.mesh.faces[face_index].vertices;
        is.map(|i| self.model.mesh.vertices[i])
    }

    fn send_indexed_face_command(&self, face_index: usize, colour: Srgba, depth: bool, temp: bool) {
        let [a, b, c] = self.deref_face(face_index);
        self.sender.send(DisplayCommand::Face { a, b, c, colour, depth, temp }).unwrap()
    }
}
