// This file was mostly generated by AI

use three_d::*;
pub struct OrbitCamera {
    pub camera: Camera,
    control: OrbitControl,
    target: Vec3,
    fov: Degrees,
    #[cfg(debug_assertions)]
    radius: f32,
}

impl OrbitCamera {
    pub fn new(viewport: Viewport, centre: Vec3, radius: f32) -> Self {
        let fov = degrees(45.0);

        let camera = Camera::new_perspective(
            viewport,
            centre + vec3(radius * 2.5, radius * 1.5, radius * 2.5),
            centre,
            vec3(0.0, 1.0, 0.0),
            fov,
            0.01,
            radius * 20.0,
        );

        let control = OrbitControl::new(centre, radius * 0.1, radius * 20.0);

        Self { camera, control, target: centre, fov, #[cfg(debug_assertions)] radius }
    }

    #[cfg(debug_assertions)]
    pub fn distance(&self) -> f32 {
        self.target.distance(self.camera.position())
    }

    pub fn update(&mut self, events: &mut [Event]) -> bool {
        self.control.handle_events(&mut self.camera, events)
    }

    pub fn resize(&mut self, viewport: Viewport) {
        self.camera.set_viewport(viewport);
    }

    // pub fn recentre(&mut self, centre: Vec3, radius: f32) {
    //     self.camera.set_view(
    //         centre + vec3(radius * 2.5, radius * 1.5, radius * 2.5),
    //         centre,
    //         vec3(0.0, 1.0, 0.0),
    //     );
    //     self.control = OrbitControl::new(centre, radius * 0.1, radius * 10.0);
    //     self.target = centre;
    //     self.radius = radius
    // }

    /// The camera's horizontal right and forward axes.
    ///
    /// `right` comes from view_direction × camera_up. Those two are orthogonal
    /// by construction, so unlike view_direction × world_up this never
    /// degenerates — including when looking straight up or down.
    #[cfg(debug_assertions)]
    fn horizontal_axes(&self) -> (Vec3, Vec3) {
        let world_up = vec3(0.0, 1.0, 0.0);
        let right = self.camera.view_direction().cross(self.camera.up()).normalize();
        let forward = world_up.cross(right);
        (right, forward)
    }
    
    #[cfg(debug_assertions)]
    pub fn forwards(&mut self, distance: f32) {
        let (_, forward) = self.horizontal_axes();
        self.translate(forward * distance);
    }
    
    #[cfg(debug_assertions)]
    pub fn rightwards(&mut self, distance: f32) {
        let (right, _) = self.horizontal_axes();
        self.translate(right * distance);
    }
    
    #[cfg(debug_assertions)]
    pub fn upwards(&mut self, distance: f32) {
        self.translate(vec3(0.0, distance, 0.0));
    }
    
    /// Shift target and eye by the same offset, so the orbit distance and
    /// angle are preserved — the camera pans rather than swinging around.
    #[cfg(debug_assertions)]
    fn translate(&mut self, offset: Vec3) {
        self.target += offset;
        let position = self.camera.position() + offset;
        self.camera.set_view(
            position,
            self.target,
            vec3(0.0, 1.0, 0.0),
        );
        self.control = OrbitControl::new(self.target, self.radius * 0.1, self.radius * 10.0)
    }

    /// Call once per frame after `update()` to keep near/far tight
    /// around the current orbit distance — fixes z-fighting that gets
    /// worse the farther the near plane is from the far plane.
    pub fn tighten_clip_planes(&mut self, radius: f32) {
        let distance = self.target.distance(self.camera.position());
        let near = (distance - radius * 2.0).max(radius * 0.001);
        let far = distance + radius * 4.0;
        self.camera.set_perspective_projection(self.fov, near, far);
    }
}