// This file was mostly generated by AI

use three_d::*;

use crate::model::LIGHT_DIR;

const CHUNK_SIZE: usize = 1024;

/* ============================================================
   DEBUG RENDERER
============================================================ */
/* ============================================================
   TEMP (PER-FRAME) RENDERERS
============================================================ */

struct TempPointRenderer {
    instances: Vec<PointInstance>,
    mesh: Gm<InstancedMesh, ColorMaterial>,
}

impl TempPointRenderer {
    fn new(context: &Context, depth: bool) -> Self {
        let cpu = CpuMesh::sphere(8);

        let mesh = Gm::new(
            InstancedMesh::new(context, &Instances::default(), &cpu),
            ColorMaterial {
                color: Srgba::WHITE,
                render_states: RenderStates {
                    depth_test: if depth {
                        DepthTest::Less
                    } else {
                        DepthTest::Always
                    },
                    cull: Cull::None,
                    ..Default::default()
                },
                ..Default::default()
            },
        );

        Self {
            instances: Vec::new(),
            mesh,
        }
    }

    fn upload(&mut self) {
        let mut transforms = Vec::with_capacity(self.instances.len());
        let mut colors = Vec::with_capacity(self.instances.len());

        for i in &self.instances {
            transforms.push(
                Mat4::from_translation(i.position)
                    * Mat4::from_scale(i.radius),
            );
            colors.push(i.color);
        }

        self.mesh.geometry.set_instances(&Instances {
            transformations: transforms,
            colors: Some(colors),
            texture_transformations: None,
        });
    }
}

struct TempLineRenderer {
    instances: Vec<LineInstance>,
    mesh: Gm<InstancedMesh, ColorMaterial>,
}

impl TempLineRenderer {
    fn new(context: &Context, depth: bool) -> Self {
        let cpu = CpuMesh::cylinder(8);

        let mesh = Gm::new(
            InstancedMesh::new(context, &Instances::default(), &cpu),
            ColorMaterial {
                color: Srgba::WHITE,
                render_states: RenderStates {
                    depth_test: if depth {
                        DepthTest::Less
                    } else {
                        DepthTest::Always
                    },
                    cull: Cull::None,
                    ..Default::default()
                },
                ..Default::default()
            },
        );

        Self {
            instances: Vec::new(),
            mesh,
        }
    }

    fn upload(&mut self) {
        let mut transforms = Vec::with_capacity(self.instances.len());
        let mut colors = Vec::with_capacity(self.instances.len());

        for i in &self.instances {
            let dir = i.b - i.a;
            let len = dir.magnitude();
            if len < 1e-6 { continue; }

            let dir = dir / len;
            let rot = Quaternion::from_arc(Vec3::unit_x(), dir, None);

            let transform =
                Mat4::from_translation(i.a)
                * Mat4::from(rot)
                * Mat4::from_nonuniform_scale(len, i.thickness, i.thickness);

            transforms.push(transform);
            colors.push(i.color);
        }

        self.mesh.geometry.set_instances(&Instances {
            transformations: transforms,
            colors: Some(colors),
            texture_transformations: None,
        });
    }
}

struct TempFaceRenderer {
    instances: Vec<FaceInstance>,
    mesh: Gm<InstancedMesh, ColorMaterial>,
}

impl TempFaceRenderer {
    fn new(context: &Context, depth: bool) -> Self {
        let cpu = CpuMesh {
            positions: Positions::F32(vec![
                Vec3::new(0.0, 0.0, 0.0),
                Vec3::new(1.0, 0.0, 0.0),
                Vec3::new(0.0, 1.0, 0.0),
            ]),
            indices: Indices::U32(vec![0, 1, 2]),
            normals: None,
            tangents: None,
            uvs: None,
            colors: None,
        };

        let mesh = Gm::new(
            InstancedMesh::new(context, &Instances::default(), &cpu),
            ColorMaterial {
                color: Srgba::WHITE,
                render_states: RenderStates {
                    depth_test: if depth {
                        DepthTest::LessOrEqual
                    } else {
                        DepthTest::Always
                    },
                    cull: Cull::None,
                    ..Default::default()
                },
                ..Default::default()
            },
        );

        Self {
            instances: Vec::new(),
            mesh,
        }
    }

    fn upload(&mut self) {
        let mut transforms = Vec::with_capacity(self.instances.len());
        let mut colors = Vec::with_capacity(self.instances.len());

        for i in &self.instances {
            let ab = i.b - i.a;
            let ac = i.c - i.a;

            let transform =
                Mat4::from_translation(i.a)
                * Mat4::from(Mat3::from_cols(ab, ac, Vec3::unit_z()));

            transforms.push(transform);
            colors.push(i.color);
        }

        self.mesh.geometry.set_instances(&Instances {
            transformations: transforms,
            colors: Some(colors),
            texture_transformations: None,
        });
    }
}

pub struct DebugRenderer {
    context: Context,

    points_occluded: Vec<PointChunk>,
    points_overlay: Vec<PointChunk>,

    lines_occluded: Vec<LineChunk>,
    lines_overlay: Vec<LineChunk>,

    faces_occluded: Vec<FaceChunk>,
    faces_overlay: Vec<FaceChunk>,

    temp_points_occluded: TempPointRenderer,
    temp_points_overlay: TempPointRenderer,

    temp_lines_occluded: TempLineRenderer,
    temp_lines_overlay: TempLineRenderer,

    temp_faces_occluded: TempFaceRenderer,
    temp_faces_overlay: TempFaceRenderer,
}

impl DebugRenderer {
    pub fn new(context: &Context) -> Self {
        Self {
            context: Clone::clone(context),
            points_occluded: Vec::new(),
            points_overlay: Vec::new(),
            lines_occluded: Vec::new(),
            lines_overlay: Vec::new(),
            faces_occluded: Vec::new(),
            faces_overlay: Vec::new(),

            temp_points_occluded: TempPointRenderer::new(context, true),
            temp_points_overlay: TempPointRenderer::new(context, false),
            temp_lines_occluded: TempLineRenderer::new(context, true),
            temp_lines_overlay: TempLineRenderer::new(context, false),
            temp_faces_occluded: TempFaceRenderer::new(context, true),
            temp_faces_overlay: TempFaceRenderer::new(context, false),
        }
    }

    pub fn clear(&mut self) {
        self.points_occluded.clear();
        self.points_overlay.clear();
        self.lines_occluded.clear();
        self.lines_overlay.clear();
        self.faces_occluded.clear();
        self.faces_overlay.clear();
    }

    pub fn temp_point(&mut self, position: Vec3, radius: f32, color: Srgba, depth: bool) {
        let t = if depth {
            &mut self.temp_points_occluded
        } else {
            &mut self.temp_points_overlay
        };

        t.instances.push(PointInstance { position, radius, color });
    }

    pub fn temp_edge(&mut self, a: Vec3, b: Vec3, thickness: f32, color: Srgba, depth: bool) {
        let t = if depth {
            &mut self.temp_lines_occluded
        } else {
            &mut self.temp_lines_overlay
        };

        t.instances.push(LineInstance { a, b, thickness, color });
    }

    pub fn temp_face(&mut self, a: Vec3, b: Vec3, c: Vec3, color: Srgba, depth: bool) {
        let t = if depth {
            &mut self.temp_faces_occluded
        } else {
            &mut self.temp_faces_overlay
        };

        t.instances.push(FaceInstance { a, b, c, color });
    }

    pub fn clear_temp_points(&mut self) {
        self.temp_points_occluded.instances.clear();
        self.temp_points_overlay.instances.clear();
    }

    pub fn clear_temp_edges(&mut self) {
        self.temp_lines_occluded.instances.clear();
        self.temp_lines_overlay.instances.clear();
    }

    pub fn clear_temp_faces(&mut self) {
        self.temp_faces_occluded.instances.clear();
        self.temp_faces_overlay.instances.clear();
    }
    
    /* ============================================================
    POINTS
    ============================================================ */
    
    pub fn point(&mut self, position: Vec3, radius: f32, color: Srgba, depth: bool) {
        let chunks = if depth {
            &mut self.points_occluded
        } else {
            &mut self.points_overlay
        };

        if chunks.is_empty() || chunks.last().unwrap().instances.len() >= CHUNK_SIZE {
            chunks.push(PointChunk::new(&self.context, depth));
        }

        let chunk = chunks.last_mut().unwrap();

        chunk.instances.push(PointInstance {
            position,
            radius,
            color,
        });

        chunk.dirty = true;
    }

    /* ============================================================
       LINES
    ============================================================ */

    pub fn edge(&mut self, a: Vec3, b: Vec3, thickness: f32, color: Srgba, depth: bool) {
        let chunks = if depth {
            &mut self.lines_occluded
        } else {
            &mut self.lines_overlay
        };

        if chunks.is_empty() || chunks.last().unwrap().instances.len() >= CHUNK_SIZE {
            chunks.push(LineChunk::new(&self.context, depth));
        }
        
        let chunk = chunks.last_mut().unwrap();
        
        chunk.instances.push(LineInstance {
            a,
            b,
            thickness,
            color,
        });

        chunk.dirty = true;
    }

    pub fn face(&mut self, a: Vec3, b: Vec3, c: Vec3, color: Srgba, depth: bool) {
        let chunks = if depth {
            &mut self.faces_occluded
        } else {
            &mut self.faces_overlay
        };

        if chunks.is_empty() || chunks.last().unwrap().instances.len() >= CHUNK_SIZE {
            chunks.push(FaceChunk::new(&self.context, depth));
        }
        
        let chunk = chunks.last_mut().unwrap();

        chunk.instances.push(FaceInstance { a, b, c, color });
        chunk.dirty = true;
    }

    /* ============================================================
       GPU UPLOAD
       ============================================================ */
       
       pub fn upload(&mut self) {
           for c in &mut self.points_occluded {
            c.upload(&self.context);
        }
        for c in &mut self.points_overlay {
            c.upload(&self.context);
        }
        for c in &mut self.lines_occluded {
            c.upload(&self.context);
        }
        for c in &mut self.lines_overlay {
            c.upload(&self.context);
        }
        for c in &mut self.faces_occluded {
            c.upload(&self.context);
        }
        for c in &mut self.faces_overlay {
            c.upload(&self.context);
        }

        self.temp_points_occluded.upload();
        self.temp_points_overlay.upload();

        self.temp_lines_occluded.upload();
        self.temp_lines_overlay.upload();

        self.temp_faces_occluded.upload();
        self.temp_faces_overlay.upload();
    }

    /* ============================================================
       RENDER STREAMS
    ============================================================ */

    pub fn occluded(&self) -> impl Iterator<Item = &dyn Object> {
        self.points_occluded
            .iter()
            .map(|c| &c.mesh as &dyn Object)
            .chain(self.lines_occluded.iter().map(|c| &c.mesh as &dyn Object))
            .chain(self.faces_occluded.iter().map(|c| &c.mesh as &dyn Object))
            .chain(std::iter::once(&self.temp_points_occluded.mesh as &dyn Object))
            .chain(std::iter::once(&self.temp_lines_occluded.mesh as &dyn Object))
            .chain(std::iter::once(&self.temp_faces_occluded.mesh as &dyn Object))
    }

    pub fn overlay(&self) -> impl Iterator<Item = &dyn Object> {
        self.points_overlay
        .iter()
        .map(|c| &c.mesh as &dyn Object)
            .chain(self.lines_overlay.iter().map(|c| &c.mesh as &dyn Object))
            .chain(self.faces_overlay.iter().map(|c| &c.mesh as &dyn Object))
            .chain(std::iter::once(&self.temp_points_overlay.mesh as &dyn Object))
            .chain(std::iter::once(&self.temp_lines_overlay.mesh as &dyn Object))
            .chain(std::iter::once(&self.temp_faces_overlay.mesh as &dyn Object))
    }
}

/* ============================================================
   POINTS
============================================================ */

struct PointInstance {
    position: Vec3,
    radius: f32,
    color: Srgba,
}

struct PointChunk {
    instances: Vec<PointInstance>,
    mesh: Gm<InstancedMesh, ColorMaterial>,
    dirty: bool,
}

impl PointChunk {
    fn new(context: &Context, depth: bool) -> Self {
        let cpu = CpuMesh::sphere(8);

        let mesh = Gm::new(
            InstancedMesh::new(context, &Instances::default(), &cpu),
            ColorMaterial {
                color: Srgba::WHITE,
                render_states: RenderStates {
                    depth_test: if depth {
                        DepthTest::Less
                    } else {
                        DepthTest::Always
                    },
                    cull: Cull::None,
                    ..Default::default()
                },
                ..Default::default()
            },
        );

        Self {
            instances: Vec::new(),
            mesh,
            dirty: true,
        }
    }

    fn upload(&mut self, _context: &Context) {
        if !self.dirty {
            return;
        }

        let mut transforms = Vec::with_capacity(self.instances.len());
        let mut colors = Vec::with_capacity(self.instances.len());

        for i in &self.instances {
            transforms.push(
                Mat4::from_translation(i.position)
                    * Mat4::from_scale(i.radius),
            );

            colors.push(i.color);
        }

        let instances = Instances {
            transformations: transforms,
            colors: Some(colors),
            texture_transformations: None,
        };

        self.mesh.geometry.set_instances(&instances);
        self.dirty = false;
    }
}

/* ============================================================
   LINES (FIXED + STABLE CYLINDER ORIENTATION)
============================================================ */

struct LineInstance {
    a: Vec3,
    b: Vec3,
    thickness: f32,
    color: Srgba,
}

struct LineChunk {
    instances: Vec<LineInstance>,
    mesh: Gm<InstancedMesh, ColorMaterial>,
    dirty: bool,
}

impl LineChunk {
    fn new(context: &Context, depth: bool) -> Self {
        let cpu = CpuMesh::cylinder(8);

        let mesh = Gm::new(
            InstancedMesh::new(context, &Instances::default(), &cpu),
            ColorMaterial {
                color: Srgba::WHITE,
                render_states: RenderStates {
                    depth_test: if depth {
                        DepthTest::Less
                    } else {
                        DepthTest::Always
                    },
                    cull: Cull::None,
                    ..Default::default()
                },
                ..Default::default()
            },
        );

        Self {
            instances: Vec::new(),
            mesh,
            dirty: true,
        }
    }

    fn upload(&mut self, _context: &Context) {
        if !self.dirty {
            return;
        }

        let mut transforms = Vec::with_capacity(self.instances.len());
        let mut colors = Vec::with_capacity(self.instances.len());

        for i in &self.instances {
            let dir = i.b - i.a;
            let len = dir.magnitude();

            if len < 1e-6 {
                continue;
            }

            let dir_norm = dir / len;

            // three-d cylinder is Z-axis aligned – rotate Z to the edge direction,
            // using the horizontal perpendicular as the fallback to keep the
            // thickness directions horizontal (Y or X will align with horiz_perp).
            let rotation = Quaternion::from_arc(Vec3::unit_x(), dir_norm, None);

            // Scale: X and Y are the radius (thickness), Z is the length
            let transform =
                Mat4::from_translation(i.a)
                * Mat4::from(rotation)
                * Mat4::from_nonuniform_scale(
                    len,           // X → now aligned to the edge
                    i.thickness,   // Y
                    i.thickness,   // Z
                )
                ;
                
            transforms.push(transform);
            colors.push(i.color);
        }

        let instances = Instances {
            transformations: transforms,
            colors: Some(colors),
            texture_transformations: None,
        };

        self.mesh.geometry.set_instances(&instances);
        self.dirty = false;
    }
}

struct FaceInstance {
    a: Vec3,
    b: Vec3,
    c: Vec3,
    color: Srgba,
}

struct FaceChunk {
    instances: Vec<FaceInstance>,
    mesh: Gm<InstancedMesh, ColorMaterial>,
    dirty: bool,
}

impl FaceChunk {
    fn new(context: &Context, depth: bool) -> Self {
        let cpu = CpuMesh {
            positions: Positions::F32(vec![
                Vec3::new(0.0, 0.0, 0.0),
                Vec3::new(1.0, 0.0, 0.0),
                Vec3::new(0.0, 1.0, 0.0),
            ]),
            indices: Indices::U32(vec![0, 1, 2]),
            normals: None,
            tangents: None,
            uvs: None,
            colors: None,
        };

        let mesh = Gm::new(
            InstancedMesh::new(context, &Instances::default(), &cpu),
            ColorMaterial {
                color: Srgba::WHITE,
                render_states: RenderStates {
                    depth_test: if depth {
                        DepthTest::LessOrEqual
                    } else {
                        DepthTest::Always
                    },
                    cull: Cull::None,
                    ..Default::default()
                },
                ..Default::default()
            },
        );

        Self {
            instances: Vec::new(),
            mesh,
            dirty: true,
        }
    }

    fn upload(&mut self, _context: &Context) {
        if !self.dirty {
            return;
        }

        let mut transforms = Vec::new();
        let mut colors = Vec::new();

        for i in &self.instances {
            let a = i.a;
            let b = i.b;
            let c = i.c;

            let ab = b - a;
            let ac = c - a;

            let normal = ab.cross(ac);
            let n_len = normal.magnitude();

            if n_len < 1e-8 {
                continue;
            }

            let n = normal / n_len;

            // -------------------------
            // LIGHTING (per instance)
            // -------------------------
            let brightness = (n.dot(LIGHT_DIR) * 0.45 + 0.55)
                .sqrt()
                .clamp(0.0, 1.0);

            let shade = (brightness * 255.0) as u8;

            let final_color = Srgba::new(
                (i.color.r as u16 * shade as u16 / 255) as u8,
                (i.color.g as u16 * shade as u16 / 255) as u8,
                (i.color.b as u16 * shade as u16 / 255) as u8,
                i.color.a,
            );

            // -------------------------
            // TRANSFORM
            // -------------------------
            let transform =
                Mat4::from_translation(a)
                * Mat4::from(Mat3::from_cols(ab, ac, Vec3::unit_z()));

            transforms.push(transform);
            colors.push(final_color);
        }

        self.mesh.geometry.set_instances(&Instances {
            transformations: transforms,
            colors: Some(colors),
            texture_transformations: None,
        });

        self.dirty = false;
    }
}