// This file was mostly generated by AI

use std::collections::HashMap;
use three_d::*;

use crate::model::LIGHT_DIR;

const CHUNK_SIZE: usize = 1024;

pub struct DebugRenderer {
    context: Context,
    groups: HashMap<usize, FeatureGroup>,
}

struct FeatureGroup {
    points_occluded: Vec<PointChunk>,
    points_overlay: Vec<PointChunk>,

    lines_occluded: Vec<LineChunk>,
    lines_overlay: Vec<LineChunk>,

    faces_occluded: Vec<FaceChunk>,
    faces_overlay: Vec<FaceChunk>,
}

impl FeatureGroup {
    fn new() -> Self {
        Self {
            points_occluded: Vec::new(),
            points_overlay: Vec::new(),
            lines_occluded: Vec::new(),
            lines_overlay: Vec::new(),
            faces_occluded: Vec::new(),
            faces_overlay: Vec::new(),
        }
    }
}

impl DebugRenderer {
    pub fn new(context: &Context) -> Self {
        Self {
            context: Clone::clone(context),
            groups: HashMap::new(),
        }
    }

    /// Remove every feature drawn under `name`.
    pub fn clear(&mut self, name: usize) {
        self.groups.remove(&name);
    }

    /// Remove every feature under every name.
    pub fn clear_all(&mut self) {
        self.groups.clear();
    }

    /* ============================================================
       POINTS
    ============================================================ */

    pub fn point(&mut self, name: usize, position: Vec3, radius: f32, color: Srgba, depth: bool) {
        let group = self.groups.entry(name).or_insert_with(FeatureGroup::new);

        let chunks = if depth {
            &mut group.points_occluded
        } else {
            &mut group.points_overlay
        };

        if chunks.is_empty() || chunks.last().unwrap().instances.len() >= CHUNK_SIZE {
            chunks.push(PointChunk::new(&self.context, depth));
        }

        let chunk = chunks.last_mut().unwrap();

        chunk.instances.push(PointInstance {
            position,
            radius,
            color,
        });

        chunk.dirty = true;
    }

    /* ============================================================
       LINES
    ============================================================ */

    pub fn edge(
        &mut self,
        name: usize,
        a: Vec3,
        b: Vec3,
        thickness: f32,
        color: Srgba,
        depth: bool,
    ) {
        let group = self.groups.entry(name).or_insert_with(FeatureGroup::new);

        let chunks = if depth {
            &mut group.lines_occluded
        } else {
            &mut group.lines_overlay
        };

        if chunks.is_empty() || chunks.last().unwrap().instances.len() >= CHUNK_SIZE {
            chunks.push(LineChunk::new(&self.context, depth));
        }

        let chunk = chunks.last_mut().unwrap();

        chunk.instances.push(LineInstance {
            a,
            b,
            thickness,
            color,
        });

        chunk.dirty = true;
    }

    /* ============================================================
       FACES
    ============================================================ */

    pub fn face(&mut self, name: usize, a: Vec3, b: Vec3, c: Vec3, color: Srgba, depth: bool) {
        let group = self.groups.entry(name).or_insert_with(FeatureGroup::new);

        let chunks = if depth {
            &mut group.faces_occluded
        } else {
            &mut group.faces_overlay
        };

        if chunks.is_empty() || chunks.last().unwrap().instances.len() >= CHUNK_SIZE {
            chunks.push(FaceChunk::new(&self.context, depth));
        }

        let chunk = chunks.last_mut().unwrap();

        chunk.instances.push(FaceInstance { a, b, c, color });
        chunk.dirty = true;
    }

    /* ============================================================
       GPU UPLOAD
    ============================================================ */

    pub fn upload(&mut self) {
        for group in self.groups.values_mut() {
            for c in &mut group.points_occluded {
                c.upload(&self.context);
            }
            for c in &mut group.points_overlay {
                c.upload(&self.context);
            }
            for c in &mut group.lines_occluded {
                c.upload(&self.context);
            }
            for c in &mut group.lines_overlay {
                c.upload(&self.context);
            }
            for c in &mut group.faces_occluded {
                c.upload(&self.context);
            }
            for c in &mut group.faces_overlay {
                c.upload(&self.context);
            }
        }
    }

    /* ============================================================
       RENDER STREAMS
    ============================================================ */

    pub fn occluded(&self) -> impl Iterator<Item = &dyn Object> {
        self.groups.values().flat_map(|group| {
            group
                .points_occluded
                .iter()
                .map(|c| &c.mesh as &dyn Object)
                .chain(group.lines_occluded.iter().map(|c| &c.mesh as &dyn Object))
                .chain(group.faces_occluded.iter().map(|c| &c.mesh as &dyn Object))
        })
    }

    pub fn overlay(&self) -> impl Iterator<Item = &dyn Object> {
        self.groups.values().flat_map(|group| {
            group
                .points_overlay
                .iter()
                .map(|c| &c.mesh as &dyn Object)
                .chain(group.lines_overlay.iter().map(|c| &c.mesh as &dyn Object))
                .chain(group.faces_overlay.iter().map(|c| &c.mesh as &dyn Object))
        })
    }
}

/* ============================================================
   POINTS
============================================================ */

struct PointInstance {
    position: Vec3,
    radius: f32,
    color: Srgba,
}

struct PointChunk {
    instances: Vec<PointInstance>,
    mesh: Gm<InstancedMesh, ColorMaterial>,
    dirty: bool,
}

impl PointChunk {
    fn new(context: &Context, depth: bool) -> Self {
        let cpu = CpuMesh::sphere(8);

        let mesh = Gm::new(
            InstancedMesh::new(context, &Instances::default(), &cpu),
            ColorMaterial {
                color: Srgba::WHITE,
                render_states: RenderStates {
                    depth_test: if depth {
                        DepthTest::Less
                    } else {
                        DepthTest::Always
                    },
                    cull: Cull::None,
                    ..Default::default()
                },
                ..Default::default()
            },
        );

        Self {
            instances: Vec::new(),
            mesh,
            dirty: true,
        }
    }

    fn upload(&mut self, _context: &Context) {
        if !self.dirty {
            return;
        }

        let mut transforms = Vec::with_capacity(self.instances.len());
        let mut colors = Vec::with_capacity(self.instances.len());

        for i in &self.instances {
            transforms.push(Mat4::from_translation(i.position) * Mat4::from_scale(i.radius));

            colors.push(i.color);
        }

        let instances = Instances {
            transformations: transforms,
            colors: Some(colors),
            texture_transformations: None,
        };

        self.mesh.geometry.set_instances(&instances);
        self.dirty = false;
    }
}

/* ============================================================
   LINES (FIXED + STABLE CYLINDER ORIENTATION)
============================================================ */

struct LineInstance {
    a: Vec3,
    b: Vec3,
    thickness: f32,
    color: Srgba,
}

struct LineChunk {
    instances: Vec<LineInstance>,
    mesh: Gm<InstancedMesh, ColorMaterial>,
    dirty: bool,
}

impl LineChunk {
    fn new(context: &Context, depth: bool) -> Self {
        let cpu = CpuMesh::cylinder(8);

        let mesh = Gm::new(
            InstancedMesh::new(context, &Instances::default(), &cpu),
            ColorMaterial {
                color: Srgba::WHITE,
                render_states: RenderStates {
                    depth_test: if depth {
                        DepthTest::Less
                    } else {
                        DepthTest::Always
                    },
                    cull: Cull::None,
                    ..Default::default()
                },
                ..Default::default()
            },
        );

        Self {
            instances: Vec::new(),
            mesh,
            dirty: true,
        }
    }

    fn upload(&mut self, _context: &Context) {
        if !self.dirty {
            return;
        }

        let mut transforms = Vec::with_capacity(self.instances.len());
        let mut colors = Vec::with_capacity(self.instances.len());

        for i in &self.instances {
            let dir = i.b - i.a;
            let len = dir.magnitude();

            if len < 1e-6 {
                continue;
            }

            let dir_norm = dir / len;

            // three-d cylinder is Z-axis aligned – rotate X to the edge direction,
            // scale X by length, Y/Z by thickness.
            let rotation = Quaternion::from_arc(Vec3::unit_x(), dir_norm, None);

            let transform = Mat4::from_translation(i.a)
                * Mat4::from(rotation)
                * Mat4::from_nonuniform_scale(len, i.thickness, i.thickness);

            transforms.push(transform);
            colors.push(i.color);
        }

        let instances = Instances {
            transformations: transforms,
            colors: Some(colors),
            texture_transformations: None,
        };

        self.mesh.geometry.set_instances(&instances);
        self.dirty = false;
    }
}

/* ============================================================
   FACES
============================================================ */

struct FaceInstance {
    a: Vec3,
    b: Vec3,
    c: Vec3,
    color: Srgba,
}

struct FaceChunk {
    instances: Vec<FaceInstance>,
    mesh: Gm<InstancedMesh, ColorMaterial>,
    dirty: bool,
}

impl FaceChunk {
    fn new(context: &Context, depth: bool) -> Self {
        let cpu = CpuMesh {
            positions: Positions::F32(vec![
                Vec3::new(0.0, 0.0, 0.0),
                Vec3::new(1.0, 0.0, 0.0),
                Vec3::new(0.0, 1.0, 0.0),
            ]),
            indices: Indices::U32(vec![0, 1, 2]),
            normals: None,
            tangents: None,
            uvs: None,
            colors: None,
        };

        let mesh = Gm::new(
            InstancedMesh::new(context, &Instances::default(), &cpu),
            ColorMaterial {
                color: Srgba::WHITE,
                render_states: RenderStates {
                    depth_test: if depth {
                        DepthTest::LessOrEqual
                    } else {
                        DepthTest::Always
                    },
                    cull: Cull::None,
                    ..Default::default()
                },
                ..Default::default()
            },
        );

        Self {
            instances: Vec::new(),
            mesh,
            dirty: true,
        }
    }

    fn upload(&mut self, _context: &Context) {
        if !self.dirty {
            return;
        }

        let mut transforms = Vec::new();
        let mut colors = Vec::new();

        for i in &self.instances {
            let a = i.a;
            let b = i.b;
            let c = i.c;

            let ab = b - a;
            let ac = c - a;

            let normal = ab.cross(ac);
            let n_len = normal.magnitude();

            if n_len < 1e-8 {
                continue;
            }

            let n = normal / n_len;

            // -------------------------
            // LIGHTING (per instance)
            // -------------------------
            let brightness = (n.dot(LIGHT_DIR) * 0.45 + 0.55).sqrt().clamp(0.0, 1.0);

            let shade = (brightness * 255.0) as u8;

            let final_color = Srgba::new(
                (i.color.r as u16 * shade as u16 / 255) as u8,
                (i.color.g as u16 * shade as u16 / 255) as u8,
                (i.color.b as u16 * shade as u16 / 255) as u8,
                i.color.a,
            );

            // -------------------------
            // TRANSFORM
            // -------------------------
            let transform =
                Mat4::from_translation(a) * Mat4::from(Mat3::from_cols(ab, ac, Vec3::unit_z()));

            transforms.push(transform);
            colors.push(final_color);
        }

        self.mesh.geometry.set_instances(&Instances {
            transformations: transforms,
            colors: Some(colors),
            texture_transformations: None,
        });

        self.dirty = false;
    }
}