// This file was partially generated by AI

mod camera;
mod debug;
mod model;
mod viewer;
mod app;

use std::sync::Arc;

use tokio::sync::mpsc;
use viewer::Viewer;

#[tokio::main()]
async fn main() {
    let path = std::env::args()
        .nth(1)
        .unwrap_or_else(|| "model.stl".to_string());

    let (display_sender, display_receiver) = mpsc::unbounded_channel();
    let (process_sender, process_receiver) = mpsc::unbounded_channel();
    let viewer = Viewer::new(&path, display_receiver, process_sender).unwrap();
    tokio::spawn(app::main(Arc::clone(&viewer.model), display_sender, process_receiver));

    viewer.run()
}