// This file was not generated by AI

mod camera;
mod debug;
mod model;
mod viewer;
mod process;
#[cfg(target_arch = "wasm32")]
mod web_glue;

use viewer::Viewer;

#[cfg(target_arch = "wasm32")]
use web_glue::push_server_message;

fn main() {
    #[cfg(not(target_arch = "wasm32"))]
    Viewer::from_default_path().unwrap().run();
}

#[cfg(target_arch = "wasm32")]
fn on_stl_loaded(bytes: Vec<u8>) {
    console_error_panic_hook::set_once();
    let viewer = Viewer::from_bytes(&bytes).unwrap();
    push_server_message(&web_glue::ServerMessage::MeshLoaded {
        vertex_count: viewer.model.mesh.vertices.len() as u32,
        face_count: viewer.model.mesh.faces.len() as u32,
    });

    viewer.run();
}