// This file was mostly generated by AI

use three_d::InnerSpace;
use anyhow::{Context, Result};
use stl_io::{IndexedMesh, Vector};
#[cfg(not(target_arch = "wasm32"))]
use std::{fs::File, io::BufReader};

use three_d::{
    CpuMesh,
    Indices,
    Positions,
    Vec3,
    Srgba,
};

#[inline]
fn zup_to_yup(v: Vector<f32>) -> Vector<f32> {
    Vector::new([v[0], v[2], -v[1]])
}

pub struct Model {
    pub mesh: IndexedMesh,
    pub centre: Vec3,
    pub radius: f32,

    // NEW: baked render mesh
    pub baked_mesh: CpuMesh,
}

impl Model {
    #[cfg(not(target_arch = "wasm32"))]
    pub fn from_path(path: &str) -> Result<Self> {
        let file = File::open(path)
            .with_context(|| format!("Couldn't open STL file '{}'", path))?;

        let mut read = BufReader::new(file);
        Self::from_read(&mut read)
    }
    
    pub fn from_bytes(bytes: &[u8]) -> Result<Self> {
        let mut read = std::io::Cursor::new(bytes);
        Self::from_read(&mut read)
    }

    pub fn from_read<R: std::io::Read + std::io::Seek>(read: &mut R) -> Result<Self> {
        let mesh = stl_io::read_stl(read)
            .context("Couldn't parse STL")?;

        Ok(Self::from_mesh(mesh))
    }

    pub fn from_mesh(mut mesh: IndexedMesh) -> Self {
        for v in &mut mesh.vertices {
            *v = zup_to_yup(*v);
        }

        for face in &mut mesh.faces {
            face.normal = zup_to_yup(face.normal);
        }

        let (centre, radius) = bounding_sphere(&mesh);

        println!(
            "Loaded {} faces, {} vertices",
            mesh.faces.len(),
            mesh.vertices.len()
        );

        let baked_mesh = bake_flat_shaded_mesh(&mesh);

        Self {
            mesh,
            centre,
            radius,
            baked_mesh,
        }
    }

    pub fn cpu_mesh(&self) -> CpuMesh {
        self.baked_mesh.clone()
    }
}

/* ============================================================
   FLAT SHADING + BAKING
============================================================ */

pub const LIGHT_DIR: Vec3 = Vec3::new(1.0 * 0.26726124, 3.0 * 0.26726124, 2.0 * 0.26726124);

fn bake_flat_shaded_mesh(mesh: &IndexedMesh) -> CpuMesh {
    let mut positions = Vec::new();
    let mut indices = Vec::new();
    let mut colors = Vec::new();

    for face in &mesh.faces {
        let ia = face.vertices[0];
        let ib = face.vertices[1];
        let ic = face.vertices[2];

        let a = mesh.vertices[ia];
        let b = mesh.vertices[ib];
        let c = mesh.vertices[ic];

        let pa = Vec3::new(a[0], a[1], a[2]);
        let pb = Vec3::new(b[0], b[1], b[2]);
        let pc = Vec3::new(c[0], c[1], c[2]);

        // face normal (flat shading)
        let n = (pb - pa).cross(pc - pa).normalize();

        // YOUR lighting formula:
        let brightness = (n.dot(LIGHT_DIR) * 0.4 + 0.55)
            .clamp(0.0, 1.0);

        let shade = (brightness * 255.0) as u8;
        let color = Srgba::new(shade, shade, shade, 255);

        let base = positions.len() as u32;

        positions.push(pa);
        positions.push(pb);
        positions.push(pc);

        colors.push(color);
        colors.push(color);
        colors.push(color);

        indices.push(base);
        indices.push(base + 1);
        indices.push(base + 2);
    }

    CpuMesh {
        positions: Positions::F32(positions),
        indices: Indices::U32(indices),
        normals: None,
        tangents: None,
        uvs: None,
        colors: Some(colors),
    }
}

/// Recompute the bounding sphere after editing vertices.
pub fn bounding_sphere(mesh: &IndexedMesh) -> (Vec3, f32) {
    let mut lo = Vec3::new(
        f32::INFINITY,
        f32::INFINITY,
        f32::INFINITY,
    );

    let mut hi = Vec3::new(
        f32::NEG_INFINITY,
        f32::NEG_INFINITY,
        f32::NEG_INFINITY,
    );

    for v in &mesh.vertices {
        let p = Vec3::new(
            v[0],
            v[1],
            v[2],
        );

        lo.x = lo.x.min(p.x);
        lo.y = lo.y.min(p.y);
        lo.z = lo.z.min(p.z);

        hi.x = hi.x.max(p.x);
        hi.y = hi.y.max(p.y);
        hi.z = hi.z.max(p.z);
    }

    let centre = (lo + hi) * 0.5;
    let radius = (hi - lo).magnitude() * 0.5;

    (centre, radius)
}