// This file was mostly generated by AI

//! JS <-> WASM message bridge (wasm-bindgen based).
//!
//! Three logical channels:
//!   1. STL bytes      JS -> Rust   `stl_load(Uint8Array)`
//!   2. JSON commands   JS -> Rust   `json_submit(string)` -> queue -> `next_client_message()`
//!   3. JSON events     Rust -> JS   `push_server_message()` -> queue -> `web_out_next()`
//!
//! No `unsafe`, no raw pointers, no manual alloc. wasm-bindgen does the
//! byte/string marshalling across the boundary; the queues are plain
//! `thread_local!` `VecDeque`s, which is all that's needed on
//! single-threaded wasm32.
//!
//! Cargo.toml:
//!   wasm-bindgen = "0.2"
//!   serde = { version = "1", features = ["derive"] }
//!   serde_json = "1"
//!   console_error_panic_hook = "0.1"   # strongly recommended, see note in main

use std::cell::RefCell;
use std::collections::VecDeque;

use wasm_bindgen::prelude::*;

// ---------------------------------------------------------------------
// Channel 1: raw STL bytes (JS -> Rust)
// ---------------------------------------------------------------------

/// Called from JS as `wasm.stl_load(new Uint8Array(buffer))`.
///
/// wasm-bindgen copies the `Uint8Array` into a fresh `Vec<u8>` for us, so
/// there's no alloc/pointer/submit dance and nothing to get wrong about
/// buffer lengths or stale pointers.
#[wasm_bindgen]
pub fn stl_load(bytes: Vec<u8>) {
    crate::on_stl_loaded(bytes);
}

// ---------------------------------------------------------------------
// Channel 2: JSON control packets (JS -> Rust)
// ---------------------------------------------------------------------

thread_local! {
    static IN_QUEUE: RefCell<VecDeque<ClientMessage>> = const { RefCell::new(VecDeque::new()) };
}

/// Called from JS as `wasm.json_submit(JSON.stringify(obj))`.
///
/// Deserializes and queues. Does *not* act on the message directly: the
/// render loop drains the queue at a frame boundary so command handling
/// always happens somewhere the GPU context is valid.
#[wasm_bindgen]
pub fn json_submit(json: String) {
    match serde_json::from_str::<ClientMessage>(&json) {
        Ok(msg) => IN_QUEUE.with(|q| q.borrow_mut().push_back(msg)),
        Err(e) => push_server_message(&ServerMessage::Error {
            message: format!("bad json packet: {e}"),
        }),
    }
}

/// Pop the next pending command, if any. Call this from your render loop:
///
/// ```ignore
/// while let Some(msg) = web_bridge::next_client_message() {
///     self.handle_client_message(msg);
/// }
/// ```
pub fn next_client_message() -> Option<ClientMessage> {
    IN_QUEUE.with(|q| q.borrow_mut().pop_front())
}

// ---------------------------------------------------------------------
// Channel 3: JSON events (Rust -> JS)
// ---------------------------------------------------------------------

thread_local! {
    static OUT_QUEUE: RefCell<VecDeque<String>> = const { RefCell::new(VecDeque::new()) };
}

/// Call from anywhere in the renderer to notify the page.
pub fn push_server_message(msg: &ServerMessage) {
    if let Ok(json) = serde_json::to_string(msg) {
        OUT_QUEUE.with(|q| q.borrow_mut().push_back(json));
    }
}

/// Polled from JS: `const raw = wasm.web_out_next(); if (raw) {...}`
///
/// Returns the next queued event as a JSON string, or `undefined` on the
/// JS side when the queue is empty. Replaces the old len/ptr/pop trio —
/// one call instead of three, and no pointer validity window to reason
/// about.
#[wasm_bindgen]
pub fn web_out_next() -> Option<String> {
    OUT_QUEUE.with(|q| q.borrow_mut().pop_front())
}

// ---------------------------------------------------------------------
// Message schemas — extend these as you add commands/events
// ---------------------------------------------------------------------

#[derive(serde::Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum ClientMessage {
    Generate { hook_size_mm: f32, diameter_cm: f32, measurements: Vec<crate::process::Measurement> },
    SetSeedPointMode { enabled: bool },
}

#[derive(serde::Serialize, Debug)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum ServerMessage {
    MeshLoaded { vertex_count: u32, face_count: u32 },
    Error { message: String },
    Output { data: Result<crate::process::Output, String> },
    Debug { message: String },
}

impl ServerMessage {
    pub fn output(data: crate::process::Result<crate::process::Output>) -> Self {
        let data = match data {
            Ok(data) => Ok(data),
            Err(err) => Err(err.to_string())
        };

        Self::Output { data }
    }
}