// This file was not generated by AI

use std::{collections::VecDeque, fmt::Display};

use crate::process::{intermediate::Highlight, stitches::{HighlightConf, StitchCommand}};


pub enum Format {
    /// Start with a magic circle with <n> stitches.
    MagicCircle(usize),
    /// Single crochet --
    Sc,
    /// Chain 1 (count as sc) --
    Chain,
    /// Single crochet x<n> --
    Inc(usize),
    /// Chain 1 (count as sc) AND Single crochet x<n-1> --
    ChainInc(usize),
    /// Chain 1 (count as sc) AND Single crochet --
    ChainSc,
    // Single crochet -- (SKIP -- )*<n>
    Dec(usize),
    // Chain 1 (count as sc) -- (SKIP -- )*<n>
    ChainDec(usize),
    // (SKIP -- )*<n>
    Skip(usize),
    /// CAREFUL - check docs for more information
    /// Close off this row with a slip stitch.
    /// --- NEXT ROUND ---
    NextRow,
}

impl Format {
    pub const SEPERATOR: &str = " -- ";

    pub fn from_intermediate(mut vec: VecDeque<StitchCommand>) -> Vec<(Self, Vec<Highlight>)> {
        let mut result = Vec::new();
        let StitchCommand::MagicCircle(circle, highlights) = vec.pop_front().unwrap() else { panic!("Unexpected stitch") };
        result.push((Self::MagicCircle(circle), highlights));
        let StitchCommand::NextRow(highlights) = vec.pop_front().unwrap() else { panic!("Unexpected stitch") };
        result.push((Self::NextRow, highlights));
        let mut convert_to_chain = true;

        for item in vec {
            match item {
                StitchCommand::Inc(n, highlights) => if convert_to_chain {
                    if n == 1 {
                        result.push((Self::Chain, highlights));
                    } else if n == 2 {
                        result.push((Self::ChainSc, highlights));
                    } else {
                        result.push((Self::ChainInc(n), highlights));
                    }
                    convert_to_chain = false
                } else {
                    if n == 1 {
                        result.push((Self::Sc, highlights))
                    } else {
                        result.push((Self::Inc(n), highlights))
                    }
                },
                StitchCommand::Dec(n, highlights) => if convert_to_chain {
                    result.push((Self::ChainDec(n), highlights));
                    convert_to_chain = false;
                } else {
                    result.push((Self::Dec(n), highlights));
                },
                StitchCommand::Skip(n, highlights) => result.push((Self::Skip(n), highlights)),
                StitchCommand::NextRow(highlights) => result.push((Self::NextRow, highlights)),
                StitchCommand::MagicCircle(_n, _highlights) => panic!("Unexpected magic circle."),
            }
        }

        result
    }

    pub fn get_conf(&self) -> HighlightConf {
        match self {
            Format::MagicCircle(_) => HighlightConf::space_seperator(),
            Format::NextRow => HighlightConf::new(String::new(), "\n--- NEXT ROUND ---\n".to_string(), false),
            _ => HighlightConf::default()
        }
    }
}

impl Display for Format {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Format::MagicCircle(n) => write!(f, "Start with a magic circle with {n} stitches."),
            Format::Sc => write!(f, "Single crochet"),
            Format::Chain => write!(f, "Chain 1 (count as sc)"),
            Format::Inc(n) => write!(f, "Single crochet x{n}"),
            Format::ChainInc(n) => write!(f, "Chain 1 (count as sc) AND Single crochet x{}", n-1),
            Format::ChainSc => write!(f, "Chain 1 (count as sc) AND Single crochet"),
            Format::Dec(n) => write!(f, "Single crochet{}", " -- SKIP".repeat(*n)),
            Format::ChainDec(n) => write!(f, "Chain 1 (count as sc){}", " -- SKIP".repeat(*n)),
            Format::Skip(n) => write!(f, "{}", "SKIP -- ".repeat(*n)),
            Format::NextRow => write!(f, "Close off this row with a slip stitch."),
        }
    }
}