// This file was not generated by AI

use std::{collections::VecDeque, fmt::Display};

use crate::process::{intermediate::{Highlight, StitchPoint}, stitches::{HighlightConf, StitchCommand}};


pub enum Format {
    /// Start with a magic circle with <n> stitches.
    MagicCircle(usize),
    /// Single crochet
    Sc,
    /// For the next <m> stitches, put a single crochet in each stitch
    RepSc(usize),
    /// Chain 1 (count as sc)
    Chain,
    /// Put <n> Single crochets into this stitch
    Inc(usize),
    /// Put a Chain 1 (count as sc) AND <n-1> Single crochets <n-1> into this stitch
    ChainInc(usize),
    /// Put a Chain 1 (count as sc) AND a Single crochet into this stitch
    ChainSc,
    /// For the next <m> stitches, put <n> single crochets in each stitch
    RepInc(usize, usize),
    // Skip the next <n> stitches
    Skip(usize),
    // Skip the next stitch
    SkipOnce,
    /// CAREFUL - check docs for more information
    /// Close off this row with a slip stitch.
    /// You should have <m> stitches in this row.
    /// --- ROUND <n> ---
    Row(usize, usize),
    // Close off the final row with a slip stitch.
    // You should have <n> stitches in this row.
    Final(usize),
}

impl Format {
    pub const SEPERATOR: &str = ". ";

    fn skip(n: usize) -> Self {
        if n == 1 {
            Self::SkipOnce
        } else {
            Self::Skip(n)
        }
    }

    pub fn from_intermediate(mut vec: VecDeque<StitchCommand>, final_highlights: Vec<StitchPoint>) -> Vec<(Self, Vec<Highlight>)> {
        let mut result = Vec::new();
        let StitchCommand::MagicCircle(circle, highlights) = vec.pop_front().unwrap() else { panic!("Unexpected stitch") };
        result.push((Self::MagicCircle(circle), highlights));
        let StitchCommand::NextRow(highlights) = vec.pop_front().unwrap() else { panic!("Unexpected stitch") };
        result.push((Self::Row(1, circle), highlights));
        let mut convert_to_chain = true;
        let mut stitches = 0;
        let mut row_number = 2;

        for item in vec {
            match item {
                StitchCommand::Inc(n, mut highlights) => if convert_to_chain {
                    if n == 1 {
                        result.push((Self::Chain, highlights));
                    } else if n == 2 {
                        result.push((Self::ChainSc, highlights));
                    } else {
                        result.push((Self::ChainInc(n), highlights));
                    }
                    convert_to_chain = false;
                    stitches += n;
                } else {
                    if n == 1 {
                        if let Some((Self::Sc, _)) = result.last() {
                            highlights.append(&mut result.pop().unwrap().1);
                            result.push((Self::RepSc(2), highlights));
                        } else if let Some((Self::RepSc(n), _)) = result.last() {
                            let n = *n;
                            highlights.append(&mut result.pop().unwrap().1);
                            result.push((Self::RepSc(n + 1), highlights));
                        } else {
                            result.push((Self::Sc, highlights))
                        }
                    } else {
                        if let Some((Self::Inc(np), _)) = result.last() && *np == n {
                            highlights.append(&mut result.pop().unwrap().1);
                            result.push((Self::RepInc(2, n), highlights));
                        } else if let Some((Self::RepInc(np, m), _)) = result.last() && *np == n {
                            let m = *m;
                            highlights.append(&mut result.pop().unwrap().1);
                            result.push((Self::RepInc(n + 1, m), highlights));
                        } else {
                            result.push((Self::Inc(n), highlights))
                        }
                    }
                    stitches += n;
                },
                StitchCommand::Dec(n, mut highlights) => if convert_to_chain {
                    result.push((Self::Chain, highlights));
                    result.push((Self::skip(n), Vec::new()));
                    convert_to_chain = false;
                    stitches += 1;
                } else {
                    if let Some((Self::Sc, _)) = result.last() {
                        highlights.append(&mut result.pop().unwrap().1);
                        result.push((Self::RepSc(2), highlights));
                    } else if let Some((Self::RepSc(n), _)) = result.last() {
                        let n = *n;
                        highlights.append(&mut result.pop().unwrap().1);
                        result.push((Self::RepSc(n + 1), highlights));
                    } else {
                        result.push((Self::Sc, highlights))
                    }
                    result.push((Self::skip(n), Vec::new()));
                    stitches += 1;
                },
                StitchCommand::Skip(n, highlights) => result.push((Self::skip(n), highlights)),
                StitchCommand::NextRow(highlights) => {
                    result.push((Self::Row(row_number, stitches), highlights));
                    row_number += 1;
                    stitches = 0;
                    convert_to_chain = true;
                },
                StitchCommand::MagicCircle(_n, _highlights) => panic!("Unexpected magic circle."),
            }
        }

        result.push((
            Self::Final(stitches),
            vec![Highlight(
                final_highlights[final_highlights.len() - 1].into(),
                final_highlights[0].into()
            )]
        ));

        result
    }

    pub fn get_conf(&self) -> HighlightConf {
        match self {
            Format::Row(n, m) => HighlightConf::new(String::new(), format!(".\nThis row should have {m} stitches.\n--- ROUND {n} ---\n"), false),
            Format::Final(n) => HighlightConf::new(String::new(), format!(".\nThis row should have {n} stitches."), false),
            _ => HighlightConf::default()
        }
    }
}

impl Display for Format {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Format::MagicCircle(n) => write!(f, "Start with a magic circle with {n} stitches"),
            Format::Sc => write!(f, "Single crochet"),
            Format::RepSc(n) => write!(f, "For the next {n} stitches, put a single crochet in each stitch"),
            Format::ChainSc => write!(f, "Chain 1 (count as sc) AND put a Single crochet into this stitch"),
            Format::Chain => write!(f, "Chain 1 (count as sc)"),
            Format::Inc(n) => write!(f, "Put {n} Single crochets into this stitch"),
            Format::RepInc(n, m) => write!(f, "For the next {m} stitches, put {n} single crochets in each stitch"),
            Format::ChainInc(n) => write!(f, "Chain 1 (count as sc) AND put {} Single crochets into this stitch", n-1),
            Format::Skip(n) => write!(f, "Skip the next {n} stitches"),
            Format::SkipOnce => write!(f, "Skip the next stitch"),
            Format::Row(_, _) => write!(f, "Close off this row with a slip stitch"),
            Format::Final(_) => write!(f, "Close off the final row with a slip stitch"),
        }
    }
}